Medaka update
galaxyproject/tools-iuc pull request #3259
Opened 2020-10-20 20:29 UTC by NatPRoach

FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2020-10-22 21:02 UTC, bgruening commented
@NatPRoach  1.1.3 is out https://anaconda.org/bioconda/medaka/

2020-10-23 16:48 UTC, NatPRoach commented
> @NatPRoach 1.1.3 is out https://anaconda.org/bioconda/medaka/

Yes I will try to get 1.1.3 wrapped shortly. Just trying to fix problems with the current version. I'll try to open a new PR for the new version shortly.

2020-10-26 16:05 UTC, NatPRoach commented
Commenting for record keeping purposes RE: @bgruening 's comment that medaka 1.1.3 is released. It would seem that medaka 1.1.3 makes the switch to tensorflow2 and as such many of it's old models are no longer functional in the new version and are not packaged in the conda package. We therefore decided to update v1.0.3 with the new approach to annotating variants first, then update the wrapper to 1.1.3, such that there is a valid version of medaka on tools-iuc that can do variant calling on reads basecalled with older versions of the basecallers.

2020-10-28 13:18 UTC, wm75 requested changes
I think this PR still contains the now abandoned annotateVCF.py script, which can be removed.

Also note that the convert_VCF_info_fields script would emit now one VCF record per ALT allele, but without splitting the ALT field itself.
AFAIU, medaka will never emit multiallelic records so this won't be an issue then, but since the code tries to be able to deal with such records, it should do so correctly.

2020-10-28 13:18 UTC, wm75 commented on tools/medaka/variant.xml
> +##    && python '$__tool_directory__/annotateVCF.py' '$out_result' mpileup.txt '$out_annotated'
No need to keep these old lines around - remove.

2020-10-28 13:18 UTC, wm75 commented on tools/medaka/variant.xml
> +            </when> -->
remove old code

2020-10-28 13:18 UTC, wm75 commented on tools/medaka/convert_VCF_info_fields.py
> +    return int(round(-10. * log10(pval)))
```suggestion
    return round(-10 * log10(pval))
```

but is also used only once, so could be inlined.

2020-10-28 14:37 UTC, NatPRoach commented
> Also note that the convert_VCF_info_fields script would emit now one VCF record per ALT allele, but without splitting the ALT field itself.
> AFAIU, medaka will never emit multiallelic records so this won't be an issue then, but since the code tries to be able to deal with such records, it should do so correctly.
You're absolutely right, I'll fix that thanks for pointing it out.

2020-10-28 14:48 UTC, NatPRoach commented on tools/medaka/convert_VCF_info_fields.py
> +                continue
I suppose that makes sense. My logic was that "Number=." fields will probably be made in such a way that they will scale the number of entries based on number of variants, but I suppose that's not always true.

2020-11-02 16:31 UTC, bernt-matthias commented
Not sure yet what the problem is over here https://github.com/galaxyproject/tools-iuc/issues/3270 .. but it would be great if it would be solved within this PR :)

2020-11-02 16:45 UTC, NatPRoach commented
> Not sure yet what the problem is over here #3270 .. but it would be great if it would be solved within this PR :)

That's the current plan. Apologies will get to addressing #3270 soon, been slammed with other stuff but it's on the list.

2020-11-03 14:05 UTC, NatPRoach commented
Oh, the issue mentioned in #3270 , that read groups are ignored in medaka_variant pipeline is not an issue on our end. It's a limitation of medaka v1.0.3 : 
Relevant section of `medaka_variant --help`
```
-i  input bam of reads aligned to ref. Read groups are currently ignored,
        so the bam should only contain reads from a single sample.
```

2021-01-03 21:42 UTC, bgruening commented
ping @NatPRoach

2021-01-04 16:53 UTC, NatPRoach commented
> ping @NatPRoach

Hi @bgruening, I think the status on this is where this thread left it previously. The changes @wm75 requested have been addressed I believe but there was no movement on merging it because of this issue with the medaka annotate function https://github.com/nanoporetech/medaka/issues/192 .

I personally think we should move ahead with the merge anyway, both because our current approach to annotating variants fails with large genomes or high depth of coverage because of memory issues, and we should address that in a version of the wrapper with the old models based on tensorflow 1, since the version after this drops a bunch of models in the upgrade to tensorflow 2. The turn around to bumping a wrapper to the next version of medaka should be quite short after that.

2021-01-09 10:39 UTC, bgruening approved these changes

2021-01-09 10:40 UTC, bgruening commented
@wm75 are you ok if we proceed here?

2021-01-09 18:03 UTC, davebx approved these changes

2021-02-03 20:26 UTC, NatPRoach commented
> @wm75 are you ok if we proceed here?
Ping @wm75 . Would appreciate an up or down decision when you get the chance.

2021-02-04 15:00 UTC, wm75 reviewed
Really sorry for not getting round to this again earlier :(

Just tiny comments this time, then everything looks ready to go.

2021-02-10 08:09 UTC, wm75 approved these changes

2021-02-10 08:12 UTC, merged

2021-02-10 08:13 UTC, wm75 commented
Thank you @NatPRoach !