adding raven wrapper
galaxyproject/tools-iuc pull request #3271
Opened 2020-10-30 19:59 UTC by NatPRoach

FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Adds raven assembler for ONT read only assemblies

2020-11-01 21:05 UTC, bernt-matthias requested changes
Nice work.

2020-11-01 21:05 UTC, bernt-matthias commented on tools/raven/raven.xml
> +        <param argument="--weaken" type="boolean" label="use larger (k, w); (for use in assembling highly accurate sequences)" checked="false"/>
Use truevalue and falsevalue attributes. Simplifies also the command section.

2020-11-01 21:05 UTC, bernt-matthias commented on tools/raven/raven.xml
> +        <param argument="--graphical-fragment-assembly" type="boolean" label="output graphical fragment assembly file?" checked="true"/>
Same here

2020-11-01 21:05 UTC, bernt-matthias commented on tools/raven/raven.xml
> +    <tests>
Can you add a test case for the filter in the output? Use expect_num_outputs...

2020-11-02 14:46 UTC, NatPRoach commented on tools/raven/raven.xml
> +        <param argument="--graphical-fragment-assembly" type="boolean" label="output graphical fragment assembly file?" checked="true"/>
How does `truevalue` and `falsevalue` work exactly when you are passing a file to a parameter as we are in this case. Also, how does `truevalue` and `falsevalue` work with tests? If I'm setting `graphical_fragment_assembly` in the test block how do I set it? as the `truevalue` or the `falsevalue`? Is there an option to set checked to true or false in the test block and let it resolve? It's a little unclear in the xml documentation.

2020-11-02 14:58 UTC, bernt-matthias commented on tools/raven/raven.xml
> +        <param argument="--graphical-fragment-assembly" type="boolean" label="output graphical fragment assembly file?" checked="true"/>
You are right, I overlooked that you set the path to the output file with this parameter. So its fine the way it is in this case.

For the test using `value="true"` should work ..

2020-11-02 15:06 UTC, mvdbeek reviewed
This would be my suggestion for (ab)using boolean parameters.

2020-11-02 15:06 UTC, mvdbeek commented on tools/raven/raven.xml
> +        <param argument="--graphical-fragment-assembly" type="boolean" label="output graphical fragment assembly file?" checked="true"/>
You can still do that with `<param argument="--graphical-fragment-assembly" type="boolean" truevalue="--graphical-fragment-assembly out.gfa" label="output graphical fragment assembly file?" checked="true"/>` if you use from_work_dir="out.gfa". I like this style since there's less cheetah involved, but up to you.
```suggestion
        <param argument="--graphical-fragment-assembly" type="boolean" truevalue="--graphical-fragment-assembly out.gfa" falsevalue="" label="output graphical fragment assembly file?" checked="true"/>
```

2020-11-02 15:06 UTC, mvdbeek commented on tools/raven/raven.xml
> +        <data name="out_gfa" format="gfa1" label="${tool.name} on ${on_string} (Graphical Fragment Assembly)">
```suggestion
        <data name="out_gfa" format="gfa1" from_work_dir="out.gfa" label="${tool.name} on ${on_string} (Graphical Fragment Assembly)">
```
If you wanna you use truevalue

2020-11-02 15:06 UTC, mvdbeek commented on tools/raven/raven.xml
> +    --graphical-fragment-assembly '$out_gfa'
```suggestion
$graphical_fragment_assembly:
```

2020-11-04 01:14 UTC, bwlang approved these changes

2020-11-04 07:34 UTC, bgruening reviewed
>  tools/raven/test-data/ERA476754.fastq.gz

This file is a little bit too large, can you please reduce the size?

2020-11-04 15:27 UTC, bgruening approved these changes

2020-11-04 15:27 UTC, merged

2020-11-04 15:28 UTC, bgruening commented
Thanks @NatPRoach!