Adding flair wrapper
galaxyproject/tools-iuc pull request #3283
Opened 2020-11-06 10:34 UTC by heylf

FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2020-11-06 12:43 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<data name="outfile_isoforms_fasta" format="fasta" label="${tool.name} on ${on_string}"/>
If there are multiple outputs the labels should be different

2020-11-06 15:44 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<data name="outfile_isoforms_fasta" format="fasta" label="${tool.name} on ${on_string}"/>
Thank you. I changed it.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
- Can you fix indentation.
- What is kerneltree doing here?

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +        <requirement type="package" version="1.5">flair</requirement>
Can you use a token for the version here and the `<tool>` version attribute.

See for instance here https://github.com/galaxyproject/tools-iuc/blob/6b9df5f3cf2518e48eced93a2904a89776bde02d/tools/stacks2/macros.xml#L5

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +#if str($cond_promotors.input_promotors) == "Yes":
I think this should be `$cond_promotors.shortread_select`

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +#if str($cond_promotors.input_promotors) == "Yes":
Maybe also include a test case for this.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +#if str($cond_promotors.input_promotors) == "Yes":
Maybe even better would be to add `optional="true"` to  `<param name="input_promotors" argument="-p" type="data" format="bed" label="BED File" />` .. then you can remove the conditional.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<param name="input_reads" argument="-r" type="data" format="fasta,fastq" label="FASTA/FASTQ file of raw reads"/>
Also here indentation is messed up.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="True"></option>
Use `selected="true"`

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +        <data name="outfile_isoforms_bed" format="bed" label="${tool.name} on ${on_string}: Isoforms BED"/>
Do users always want all outputs? Having gtf and bed seems redundant. Maybe let the user decide which is wanted.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +        <requirement type="package" version="1.5">flair</requirement>
Also requirements can be done with a xml macro. 

In general, if multiple tools re-use the same xml .. use a macro :)

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +#if str($cond_shortread.shortread_select) == "Yes":
see above.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +        <data name="outfile_2" format="bed12" label="${tool.name} on ${on_string}: Inconsistent Reads"/>
`outfile_2` is not yet mentioned in the command section.

2020-11-06 16:19 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +        <citation type="bibtex">
Also a mcro for the citation would be a good idea. Additionally use just the doi.

2020-11-06 17:28 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
kerneltree is needed for flair. It is not supported by the conda package.

2020-11-06 17:35 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
we can add it to the recipe? or are there reasons against it?

2020-11-06 17:50 UTC, heylf commented on tools/flair/flair_collapse.xml
> +        <data name="outfile_isoforms_bed" format="bed" label="${tool.name} on ${on_string}: Isoforms BED"/>
I think it is a good idea. you need bed and gtf file formats for different tools.

2020-11-06 18:05 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +        <data name="outfile_isoforms_bed" format="bed" label="${tool.name} on ${on_string}: Isoforms BED"/>
You can make it optional depending on the users choice like so: https://docs.galaxyproject.org/en/master/dev/schema.html#tool-outputs-data-filter

2020-11-09 16:13 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
No totally fine

2020-11-09 16:14 UTC, heylf commented on tools/flair/flair_collapse.xml
> +        <requirement type="package" version="1.5">flair</requirement>
added macros to the files

2020-11-09 16:14 UTC, heylf commented on tools/flair/flair_collapse.xml
> +#if str($cond_promotors.input_promotors) == "Yes":
changed

2020-11-09 16:14 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<param name="input_reads" argument="-r" type="data" format="fasta,fastq" label="FASTA/FASTQ file of raw reads"/>
changed

2020-11-09 16:14 UTC, heylf commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="True"></option>
changed

2020-11-09 16:15 UTC, heylf commented on tools/flair/flair_correct.xml
> +        <requirement type="package" version="1.5">flair</requirement>
added macros

2020-11-09 16:15 UTC, heylf commented on tools/flair/flair_correct.xml
> +#if str($cond_shortread.shortread_select) == "Yes":
changed

2020-11-09 16:15 UTC, heylf commented on tools/flair/flair_correct.xml
> +        <data name="outfile_2" format="bed12" label="${tool.name} on ${on_string}: Inconsistent Reads"/>
changed

2020-11-09 16:15 UTC, heylf commented on tools/flair/flair_correct.xml
> +        <citation type="bibtex">
added macros

2020-11-09 16:33 UTC, heylf commented on tools/flair/flair_collapse.xml
> +        <data name="outfile_isoforms_bed" format="bed" label="${tool.name} on ${on_string}: Isoforms BED"/>
included now

2020-11-10 08:04 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" label="Output data type">
I could imagine that fasta and one of the annotation files is desired as output at the same time.

An alternative would be to allow multiple selections with `multiple="true"`. Then one would need three outputs each having a filter.

Or always output fasta and one of gtf/bed (which could be selected here.)

2020-11-10 08:06 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" label="${tool.name} on ${on_string}: Correct Reads"/>
Both outputs are not reflected in the command section, how are they filled with data?

2020-11-10 08:07 UTC, bernt-matthias commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
I still think this should be done in bioconda. Or?

2020-11-10 08:11 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +        <requirement type="package" version="1.5">flair</requirement>
Maybe my example was not the best, since the IUC best practices suggest `@TOOL_VERSION@` (https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

2020-11-10 08:16 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
Done https://github.com/bioconda/bioconda-recipes/pull/25262 .. note that samtools requirement is also not needed here.

2020-11-10 10:31 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<requirement type="package" version="0.0.5">kerneltree</requirement>
ok I will remove it!

2020-11-10 10:39 UTC, heylf commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" label="${tool.name} on ${on_string}: Correct Reads"/>
you can only give flair with -o a name base (defaulf: flair). flair names the files then according to the base: *_corrected.bed and *_inconsistent.bed

2020-11-10 10:46 UTC, heylf commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" label="${tool.name} on ${on_string}: Correct Reads"/>
I changed it, but I am not sure if this is correct

2020-11-10 10:46 UTC, heylf commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
changed

2020-11-10 10:47 UTC, heylf commented on tools/flair/flair_collapse.xml
> +        <requirement type="package" version="1.5">flair</requirement>
changed

2020-11-10 11:18 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" label="${tool.name} on ${on_string}: Correct Reads"/>
Then you should add the `from_work_dir` attribute, i.e. `from_work_dir="flair_corrected.bed"`. Or is it more than these 2 files?

2020-11-10 17:02 UTC, bernt-matthias commented
can you add the missing test file: `EEF1A1.fastq`?

2020-11-10 17:03 UTC, bernt-matthias commented on tools/flair/.shed.yml
> +remote_repository_url: https://github.com/BrooksLabUCSC/flair
I think this should be `remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/flair`

2020-11-10 17:04 UTC, bernt-matthias commented on tools/flair/.shed.yml
> +  -
What would be a good category? Give at least one. You may use any listed in the toolshed.

2020-11-10 17:05 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" multiple="true" label="Output data type">
I guess this parameter also needs to find its way to the command section.

2020-11-10 17:05 UTC, bernt-matthias commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" from_work_dir="flair_corrected.bed" />
Can you restore the label?

2020-11-10 17:06 UTC, bernt-matthias commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
still there. isn't it?

2020-11-10 18:00 UTC, mmiladi commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
kerneltree is already in the falir dependency: https://github.com/bioconda/bioconda-recipes/blob/b2d371c9890c7e19d788e4f01920ecac21e96bc6/recipes/flair/meta.yaml#L38

2020-11-10 18:26 UTC, bernt-matthias commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
True. And therefore you can remove it here. (same for samtools).. Or am I wrong?

2020-11-10 19:23 UTC, heylf commented on tools/flair/flair_macros.xml
> +			<requirement type="package" version="0.0.5">kerneltree</requirement>
sorry. tested something and comitted the wrong version of the macros.

2020-11-10 19:24 UTC, heylf commented on tools/flair/.shed.yml
> +remote_repository_url: https://github.com/BrooksLabUCSC/flair
changed

2020-11-10 19:24 UTC, heylf commented on tools/flair/.shed.yml
> +  -
changed

2020-11-10 19:25 UTC, heylf commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" from_work_dir="flair_corrected.bed" />
changed

2020-11-10 19:28 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" multiple="true" label="Output data type">
I changed it back. The user obtains all three formats automatically. He definitly needs the fasta and bed (eventually the gtf as well). You cannot say to flair.py collapse which files it should produce. It will always produce all three.

2020-11-10 19:42 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" multiple="true" label="Output data type">
Jep. But you can tell the galaxy wrapper which of those files to present to the user. The others will just be discarded. I would consider this as user friendly since the history is not "filled" with data sets that are not needed.

2020-11-13 14:15 UTC, mmiladi commented
@heylf  The test file (hg38.fa) has not been added to the commits.

2020-11-13 15:01 UTC, bernt-matthias commented
Also UCSC_Main_on_Human__knownGene_region.gtf is missing

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +	<description>Defines high-confidence isoforms from flair-corrected reads.</description>
name and description are supposed to form a sentence so you wouldn't capitalize the description.
That said, the description still does not end with a period :)

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +    -p $input_promotors
needs quoting

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +#if str($additional_options.select_uniqueness) != "":
empty string compares False by itself

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			<param name="window" argument="-w" type="integer" min="0" value="100" label="Window Size" help="Window size for comparing TSS/TES (Default=100)" />
Does the zero value play a special role here? Otherwise, a window size of 0 does not seem to make much sense.

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			<param name="support" argument="-s" type="integer" min="0" value="3" label="Supporting Reads" help="Minimum number of supporting reads for an isoform (Default=3)" />
same thing here with the min="0"

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			<param name="stringent" argument="--sringent" type="boolean" value="False" truevalue="--stringent" falsevalue="" label="Use Stringent Mode" help="Specify if all supporting reads need to be full-le
value="False" is wrong syntax for a boolean param. Does planemo lint not complain about it?

It's checked="true" and checked="false", but the latter is the default anyway.
Same goes for all your other booleans.

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			<param name="stringent" argument="--sringent" type="boolean" value="False" truevalue="--stringent" falsevalue="" label="Use Stringent Mode" help="Specify if all supporting reads need to be full-le
There's also a typo in the argument string

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="true"></option>
This one should still have some user-facing text

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			<param name="maxends" argument="--max_ends" type="integer" min="0" value="2" label="Maximum Number of TSS/TES picked per isoform" help="(Default=2)" />
again the question about the meaningfulness of min=0

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="true"></option>
Again there should be user-facing text (like "Do not filter" or something)

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_correct.xml
> +	<description>Corrects misaligned splice sites using genome annotations.</description>
See my remarks for the other wrapper

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_correct.xml
> +samtools faidx '$input_genome' &&
You must create a symlink in the job working directory before doing this!

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_correct.xml
> +    -j $input_shortread
needs quoting

2020-11-13 17:58 UTC, wm75 commented on tools/flair/flair_correct.xml
> +			<param name="window" argument="-w" type="integer" min="0" value="10" label="Window Size" help="Window size for correcting splice sites (Default=10)" />
Again, booleans and question about min=0

2020-11-16 12:32 UTC, heylf commented on tools/flair/flair_collapse.xml
> +	<description>Defines high-confidence isoforms from flair-corrected reads.</description>
check

2020-11-16 12:34 UTC, heylf commented on tools/flair/flair_collapse.xml
> +    -p $input_promotors
check

2020-11-16 12:34 UTC, heylf commented on tools/flair/flair_collapse.xml
> +#if str($additional_options.select_uniqueness) != "":
check

2020-11-16 12:35 UTC, heylf commented on tools/flair/flair_collapse.xml
> +			<param name="window" argument="-w" type="integer" min="0" value="100" label="Window Size" help="Window size for comparing TSS/TES (Default=100)" />
check

2020-11-16 12:36 UTC, heylf commented on tools/flair/flair_correct.xml
> +	<description>Corrects misaligned splice sites using genome annotations.</description>
check

2020-11-16 12:36 UTC, heylf commented on tools/flair/flair_correct.xml
> +    -j $input_shortread
check

2020-11-16 12:37 UTC, heylf commented on tools/flair/flair_collapse.xml
> +			<param name="support" argument="-s" type="integer" min="0" value="3" label="Supporting Reads" help="Minimum number of supporting reads for an isoform (Default=3)" />
check

2020-11-16 12:41 UTC, heylf commented on tools/flair/flair_collapse.xml
> +			<param name="stringent" argument="--sringent" type="boolean" value="False" truevalue="--stringent" falsevalue="" label="Use Stringent Mode" help="Specify if all supporting reads need to be full-le
check

2020-11-16 12:43 UTC, heylf commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="true"></option>
check

2020-11-16 12:43 UTC, heylf commented on tools/flair/flair_collapse.xml
> +			<param name="maxends" argument="--max_ends" type="integer" min="0" value="2" label="Maximum Number of TSS/TES picked per isoform" help="(Default=2)" />
check

2020-11-16 12:43 UTC, heylf commented on tools/flair/flair_collapse.xml
> +				<option value="" selected="true"></option>
check

2020-11-16 12:44 UTC, heylf commented on tools/flair/flair_correct.xml
> +			<param name="window" argument="-w" type="integer" min="0" value="10" label="Window Size" help="Window size for correcting splice sites (Default=10)" />
check

2020-11-19 13:48 UTC, heylf commented on tools/flair/flair_correct.xml
> +samtools faidx '$input_genome' &&
check

2020-11-19 13:48 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" multiple="true" label="Output data type">
check

2020-11-19 13:48 UTC, heylf commented on tools/flair/flair_correct.xml
> +		<data name="outfile_1" format="bed12" label="${tool.name} on ${on_string}: Correct Reads"/>
check

2020-11-19 13:48 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<param name="out_format" type="select" label="Output data type">
check

2020-11-19 13:56 UTC, heylf commented
@wm75 @bernt-matthias @mmiladi Wrapper's finished without fails

2020-11-19 15:17 UTC, wm75 commented on tools/flair/flair_macros.xml
> +			samtools faidx $reference_fasta_fn 2>&1 || echo "Error running samtools faidx for indexing fasta reference for lofreq" >&2 &&
change `lofreq` to `flair` in the error message :)

2020-11-19 15:17 UTC, wm75 commented on tools/flair/flair_macros.xml
> +						<options from_data_table="fasta">
I understand that one of the two tools does not seem to require a fasta index, but you still need to use the `fasta_indexes` table because of the other one. Compare how you're not indexing in the `cached` branch of `@PREPARE_REF@`!

Alternatively you could also just use samtools faidx in the cached genome case specifically in the wrapper that requires the index, but using the indexed genomes table is just fine. Typically, the fasta and fasta_indexed tables list just the same genomes on well-organized servers (because hosting the index is trivial compared to hosting the genome).

2020-11-19 16:31 UTC, heylf commented on tools/flair/flair_macros.xml
> +						<options from_data_table="fasta">
Ah true you are right.

2020-11-19 16:41 UTC, heylf commented on tools/flair/flair_macros.xml
> +						<options from_data_table="fasta">
check

2020-11-19 16:41 UTC, heylf commented on tools/flair/flair_macros.xml
> +			samtools faidx $reference_fasta_fn 2>&1 || echo "Error running samtools faidx for indexing fasta reference for lofreq" >&2 &&
check

2020-11-19 16:55 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +	-n str($additional_options.select_uniqueness)
Can we have consistent 4 space indentation?

2020-11-19 17:01 UTC, bernt-matthias commented on tools/flair/flair_macros.xml
> +			#set $reference_fasta_fn = 'reference.fa'
Maybe remove the variable and use `'reference.fa'` directly?

2020-11-19 17:12 UTC, heylf commented on tools/flair/flair_collapse.xml
> +	-n str($additional_options.select_uniqueness)
I am so sorry that this is happening again. I dont understand why Atom doesn't show it to me. In Atom in looks fine to me. This was also the case for the last identation mistakes.

2020-11-20 16:20 UTC, wm75 commented
@heylf remaining thing to do would be to decrease the size of the chrM.fastq test file.
2.2 MB is way too much for producing empty outputs!

2020-11-20 16:22 UTC, wm75 commented
Either just reduce the size of the current file or, even better, think about a better input that produces at least one line of output.

2020-11-20 17:51 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			</param>
What's super-weird here is that in my local testing, if I don't select any additional outputs, I'm getting both produced. If I'm selecting one of them, I'm getting just this one.

Somehow the `None` situation seems to result in unexpected behavior. @bernt-matthias Do you have an idea what's going on here?

2020-11-20 18:04 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +			</param>
The solution seems to be to use:
`additional_outputs['out_format'] and 'bed' in additional_outputs['out_format']`
and
`additional_outputs['out_format'] and 'fasta' in additional_outputs['out_format']`
in the output filtering elements, but this feels at least like half a bug to me.

2020-11-20 18:13 UTC, wm75 commented on tools/flair/flair_collapse.xml
> +		<param name="input_promotors" optional="true" argument="-p" type="data" format="bed" label="BED File" />
BED File is a really unhelpful label!

2020-11-20 18:13 UTC, wm75 commented on tools/flair/flair_correct.xml
> +		<param name="input_shortread" optional="true" argument="-j" type="data" format="bed" label="BED File" />
BED File is a really unhelpful label!

2020-11-20 19:50 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +			</param>
Yes thats it.

I remember that there was an open issue for `multiple="true"`, but I'm not sure if this was for data inputs. Can't find it.

2020-11-23 16:35 UTC, heylf commented on tools/flair/flair_correct.xml
> +		<param name="input_shortread" optional="true" argument="-j" type="data" format="bed" label="BED File" />
check

2020-11-23 16:35 UTC, heylf commented on tools/flair/flair_collapse.xml
> +		<param name="input_promotors" optional="true" argument="-p" type="data" format="bed" label="BED File" />
check

2020-11-23 16:35 UTC, heylf commented on tools/flair/flair_collapse.xml
> +			</param>
check

2020-11-23 19:17 UTC, mmiladi commented on tools/flair/test-data/chrM.fa
> +>MT dna:chromosome chromosome:GRCh38:MT:1:16569:1 REF
The chrome name should be `chrM`

2020-11-25 12:31 UTC, heylf commented on tools/flair/test-data/chrM.fa
> +>MT dna:chromosome chromosome:GRCh38:MT:1:16569:1 REF
check

2020-11-25 16:26 UTC, heylf commented
@wm75 should be ready now to be merged.

2020-11-27 17:36 UTC, wm75 commented
This may be ready for merging. @bernt-matthias would you like to take one more look at it?

2020-11-27 17:38 UTC, wm75 approved these changes
Looks good to me eventually. Thanks @heylf for all the work you put into this!

2020-11-27 18:04 UTC, merged

2020-11-27 18:04 UTC, bgruening commented
Merci everyone!

2020-11-27 18:05 UTC, bernt-matthias requested changes
Seems that I'm to late @bgruening  ... ?

2020-11-27 18:05 UTC, bernt-matthias commented on tools/flair/flair_collapse.xml
> +			<param name="out_format" value="bed,fasta" />
Optional: Use only one of the two to test the filter at work.

2020-11-27 18:06 UTC, bgruening commented
@bernt-matthias sorry did not see it. If you like stop the github action and we can add your changes.

2020-11-27 18:08 UTC, bernt-matthias commented
> @bernt-matthias sorry did not see it. If you like stop the github action and we can add your changes.

Was just a matter of seconds. I have seen that you merged it just as I wanted to submit my review.

2020-11-27 18:10 UTC, bgruening commented
Should I just fix the indentation and add the profiles?

2020-11-27 18:10 UTC, bernt-matthias commented
OK :)

2020-11-27 18:17 UTC, bgruening commented
@bernt-matthias https://github.com/galaxyproject/tools-iuc/pull/3355 :)

2020-11-29 23:06 UTC, mmiladi commented
Thanks much everyone, especially thanks @heylf for going through all of that ;-)!