Pear update
galaxyproject/tools-iuc pull request #3284
Opened 2020-11-09 03:56 UTC by mthang

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2020-11-12 14:21 UTC, bernt-matthias requested changes

2020-11-12 14:21 UTC, bernt-matthias commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
Please change to the more consistent label: `"${tool.name} on ${on_string}: log"`

Please make the indentation consistent.

What exactly is the action doing? We also would need a test for this.

What are the

2020-11-13 07:15 UTC, mthang commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
HI @bernt-matthias,
Thank you for looking after this! I just updated the pear.xml wrapper at my end and uploaded a file (F3D0.log) to the test-data folder. https://github.com/QFAB-Bioinformatics/tools-iuc/blob/pear_update/tools/pear/pear.xml 

To answer your question about "what exactly is the action doing"?, the additional code added to the pear.xml is used to capture the console output of the pear program and output it as a text/log file instead of just printing the console output in the history. You can see the example output in the F3D0.log as a physical file in the test-data folder in my repo.

I am not sure if I need to make the open pull request again for the latest changes.

Many thanks,
Mike

2020-11-13 08:47 UTC, bernt-matthias commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
Now you redefine the `name` attribute of the output (see linter error). 

> to capture the console output of the pear program

I have to ask "capture it where"? Unfortunately I still do not get the intention of the action. 

Currently the stdout of pear is redirected to `logout` over here: https://github.com/galaxyproject/tools-iuc/blob/e8e64dbfd6cc5b73e37c5417be63777f505a5ce0/tools/pear/pear.xml#L50

If you like to you may use `| tee '$logout'` then the output goes to the data set in the history and you still see it in stdout. 

Btw. Currently the file input and output parameters are either unquoted or use double quotes. Could you change this to single quotes?

What I can suggest is to add the file that you are referring to to the `<test>` - this definitely makes sense.

> I am not sure if I need to make the open pull request again for the latest changes.

You can keep adding commits to this branch. They will appear in this PR.

2020-11-17 00:30 UTC, mthang commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
Hi @bernt-matthias,
Thank you for your quick response !  I can update the pear.xml wrapper to use single quotes instead of the double quotes or unquoted. I understand that my request of the enhancement of this pear wrapper can be confusing. The main reason why I need that enhancement is to create an aggregate statistic of all paired-end file processed by pear. I have made another tool to do the aggregation after the main pear wrapper. 

The example output of my tool can be seen here https://raw.githubusercontent.com/QFAB-Bioinformatics/metaDEGalaxy/master/pear_stats/test-data/test_output.txt . As you see, my tool retrieves only few lines from the pear stdout, but the existing pear wrapper does not have the console output printed to a physical file. Therefore, my pear can't be used without the pear stdout in physical files. does it make sense ?

2020-11-17 08:58 UTC, bernt-matthias commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
I understand. But the problem is that the log file is already added to the history, isn't it? So the action is not needed at al in my opinion.

Furthermore the action seems nonsensical to me. In case the conditional select is `library.type` is `"paired"` the filter checks again if `library.type=="paired" (which is always true in this case) .. same for `"paired_collection"`. 

So my suggestion would be:

- restore the original state for `logout`
- extend the test to check `logout` against the file `F3D0.log` ()
- improve the quoting of input and output files in the command block

2020-11-17 10:01 UTC, mthang commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
Hi @bernt-matthias,
Thank you for quick response! You are correct. The log output of pear is added to the history (please see the attached screenshot), but I do not have a clue how to parse the data out of the history. Perhaps, you can give a pointer on how to parse data from the pear log in the history. I am not entirely sure how to create a tool to retrieve the data between "format fastsanger, database?" and "PEAR v0.9.6 [January 15,2015] section in the history. if there is already a tool to do that, please let me know. I am happy to use the official IUC pear wrapper and just update my wrapper to parse the pear log using your method.

![PEAR_History](https://user-images.githubusercontent.com/19919190/99374445-4f33ae00-290e-11eb-95ff-21d9a3a2c96f.PNG)

Many thanks,
Mike

2020-11-17 10:06 UTC, bernt-matthias commented on tools/pear/pear.xml
> +        <data name="logout" format="txt" label="${tool.name} on ${on_string}.log">
I guess the following tools can do the task:

- Search in textfiles (grep) 
- Text transformation with sed

when applied to the `log file`. 

Still it would be great if you could finish the PR as I outlined above.

2024-03-07 01:42 UTC, closed without merging