mothur screen.seqs bugfix
galaxyproject/tools-iuc pull request #3289
Opened 2020-11-10 16:41 UTC by pmpcosta

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [X] - This PR does something else (explain below)

Issue: https://github.com/galaxyproject/tools-iuc/issues/3288#issue-740066450

Bugfix: $optimize is a multiple option parameter, and the options must be collated with dashes, not separated with commas. If multiple options are selected for the optimize parameter of screen.seqs, the job will crash.

2020-11-10 16:51 UTC, bernt-matthias requested changes
Could you add a test case for this?

2020-11-11 18:20 UTC, pmpcosta commented
I didn't bother, as it is not a new parameter, but I will try, should be a good learning exercise..

2020-11-20 16:32 UTC, bernt-matthias commented on tools/mothur/screen.seqs.xml
> +            <param name="optimize" value="minlength ,maxlength ,maxhomop"/>
Cool. But I think the spaces befor the `,` are wrong.

2020-11-20 16:35 UTC, pmpcosta commented on tools/mothur/screen.seqs.xml
> +            <param name="optimize" value="minlength ,maxlength ,maxhomop"/>
Iwill check...

2020-11-20 16:46 UTC, pmpcosta commented on tools/mothur/screen.seqs.xml
> +            <param name="optimize" value="minlength ,maxlength ,maxhomop"/>
You are right, no spaces. Will see to it...

2020-11-20 19:23 UTC, bgruening approved these changes

2020-11-20 19:39 UTC, bernt-matthias approved these changes
Should we wait for a review of @shiltemann ?

2020-11-25 12:20 UTC, pmpcosta commented
do we change @WRAPPER_VERSION@ to .1 ?

2020-11-25 16:29 UTC, bernt-matthias commented
> do we change @WRAPPER_VERSION@ to .1 ?

Yep. That sounds good.

2020-12-06 20:05 UTC, bernt-matthias commented
@pmpcosta anything left to do here? otherwise I would merge.

2020-12-07 20:28 UTC, pmpcosta commented
No, I think it is done.

2020-12-08 08:37 UTC, merged

2020-12-08 08:37 UTC, bernt-matthias commented
Thanks @pmpcosta