Missing comma in make.contigs.xml
galaxyproject/tools-iuc pull request #3336
Opened 2020-11-22 15:46 UTC by pmpcosta

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [X] - This PR does something else (explain below)

Bugfix. Actual excerpt from make.contigs logfile:
mothur > 
<-1,gapopen=-2,gapextend=-1,rename=Trueprocessors=4)

Using 1 processors.

After correcting missing comma in "rename" parameter:
mothur > 
<1,gapopen=-2,gapextend=-1,rename=True,processors=4)

Using 4 processors.

Now the tool is able to use multiple cores. No impact in the result itself so much as I could see.

2020-11-22 18:08 UTC, pmpcosta commented
Ouch! "rename sequences" now works, which means all tests will have to be redone...

2020-11-22 19:20 UTC, bernt-matthias requested changes
Good find. Should be ready to go with updated test data.

2020-11-23 13:12 UTC, bernt-matthias approved these changes

2020-11-23 13:12 UTC, bernt-matthias commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
md5 is fine for me .. but I prefer asserts on the contents. I leave this decision to you,

2020-11-23 17:29 UTC, pmpcosta commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
There are already a lot of closely related test files. Since this test only checks for change of sequence names, it seems reasonable to me.

2020-11-23 17:33 UTC, bernt-matthias commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
I meant to add something like:

```
<assert_contents>
    <has_text text="...." />
</assert_contents>
```

to the output tag .. you may have this in addition to the md5 if you like. Then the intention of the test maybe easier to understand compared to the md5. I agree completely that we do not need more test files.

2020-11-23 21:27 UTC, pmpcosta commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
Ah, ok..

2020-11-24 11:05 UTC, bernt-matthias commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
Ah. I guess tabs are not possible in the text, maybe:

```
<assert_contents>
    <has_text_matching expression="...." />
</assert_contents>

```

2020-11-24 13:46 UTC, pmpcosta commented on tools/mothur/make.contigs.xml
> +            <output name="fasta" md5="addcc2f4233df75ab9e5feacadb6850f" ftype="fasta"/>
From the xml docs it seems you can use the xml escape sequence for tabs, lets try..

2020-11-24 14:24 UTC, bernt-matthias commented
One more thing: we need to bump the tool version to `@WRAPPER_VERSION@.1`

2020-11-25 22:03 UTC, bgruening approved these changes

2020-11-25 22:04 UTC, bgruening commented
Cool, thanks a lot!

2020-11-25 22:04 UTC, merged