Bandage update
galaxyproject/tools-iuc pull request #3367
Opened 2020-12-03 11:39 UTC by mthang

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2020-12-03 12:00 UTC, nsoranzo requested changes
This PR includes also commits from https://github.com/galaxyproject/tools-iuc/pull/3284 , which I think is by mistake. Can you remove them?

2020-12-03 21:52 UTC, bernt-matthias commented on tools/bandage/bandage_image.xml
> +		<param argument="--fontsize" type="integer" min="5" optional="True" label="Font size" help="Node font size?"/>
Lower case true.

2020-12-04 07:14 UTC, mthang commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
Hi Nicola,
Thank you for your prompt response ! I have submitted two separate PR works here, and I think I failed to split the pear_update and bandage_update branch to two separate commits. I will try to split up the pear_update and branch_update branch. FYI, I have updated the bandage_image.xml according to your suggestions.

Cheers

2020-12-04 12:34 UTC, nsoranzo commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
@mthang Thanks for your work on this! Unfortunately there are still several tabs (you can see them as light gray rightwards arrows on https://github.com/galaxyproject/tools-iuc/pull/3367/files , while spaces are dots). You should be able to set up your editor/IDE to use 4-spaces instead of tabs for indentation, and use the replace-all function to replace the ones that are already there.

I can rebase out the pear changes once that's done.

2020-12-08 10:56 UTC, mthang commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
@nsoranzo Thanks for your help ! I have fixed up the spaces issues and you are correct about it. It came from my IDE setting. However, the tab setting that I have changed in my IDE didnt help. Anyway, I have fixed the spaces. can you please try it again and let me if that works. Thanks!

2020-12-08 11:20 UTC, nsoranzo commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
Thanks for following up on this! Can please enable "Allow edits and access to secrets by maintainers" for this PR (the checkbox on the right column in this page)? Otherwise I won't be able to rebase the pear changes out of your PR.

2020-12-10 10:18 UTC, bgruening commented
@nsoranzo could you take another look please?

2020-12-10 11:43 UTC, nsoranzo commented
> @nsoranzo could you take another look please?

https://github.com/galaxyproject/tools-iuc/pull/3367#discussion_r538256455 is still standing.

2021-01-03 21:35 UTC, bgruening commented
Ping @mthang

2021-01-11 02:09 UTC, mthang reviewed
Hi @nsoranzo, I would like to follow up on this merge. As mentioned, I can't find the "Allow edits and access to secrets by maintainers" checkbox on my page.

2021-01-11 12:42 UTC, nsoranzo commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
@mthang See the documentation at https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2021-01-18 14:30 UTC, nsoranzo commented on tools/bandage/bandage_image.xml
> +	#if $fontsize:
> @mthang See the documentation at https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

So this is unfortunately not possible because the pull request was open from a fork belonging to an organisation: https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847

2021-01-18 14:32 UTC, nsoranzo commented
As agreed with @mthang, closing in favour of https://github.com/galaxyproject/tools-iuc/pull/3435 .

2021-01-18 14:32 UTC, closed without merging