Add bio.tools IDs to tools
galaxyproject/tools-iuc pull request #3411
Opened 2021-01-03 22:46 UTC by bgruening

This is a WIP. We will try to add some more ideas to our tools, please feel free to push to this branch.

2021-01-04 01:17 UTC, bgruening commented
Ok, done until `f`.

2021-01-05 14:29 UTC, bernt-matthias commented
Would it be possible to do this automatically from the bioconda annotations https://github.com/bioconda/bioconda-recipes/issues/26008?

2021-01-06 10:36 UTC, bgruening commented
Question: Do we want to merge this and stop the CI ... so that those annotations get added when the next tool version bump is happening or do we push it to the TS forcing a tool update (not upgrade) for all the tools?

2021-01-06 11:10 UTC, bernt-matthias commented
Hmm. 

Pro deployment: I expect that many of the tools won't get a PR for a long time. 

Con deployment: One would need to fix all the linter errors. It will need a while until this gets really useful within Galaxy.

2021-01-06 11:45 UTC, bgruening commented
> Con deployment: One would need to fix all the linter errors. It will need a while until this gets really useful within Galaxy.

I guess we can overule the linter here and ignore it.

2021-01-06 11:52 UTC, bernt-matthias commented
> I guess we can overule the linter here and ignore it.

Meaning manual deployment? I'm fine with this. 

I guess a few others from IUC should comment on this as well?

2021-01-06 14:31 UTC, bgruening commented
ping @galaxyproject/iuc

2021-01-06 14:37 UTC, gregvonkuster commented
I don't have the context needed for me to add benefit here.  Is there a ticket or details that provide info about the goal that is being accomplished here?

2021-01-08 18:41 UTC, hexylena commented
Normally I don't like in-place tool upgrades but maybe makes sense here. I'd love to see this so that we can automate the edam annotations, it starts to make https://github.com/galaxyproject/galaxy/pull/10592 which will be in the next release actually useful/interesting.

2021-01-12 10:19 UTC, bernt-matthias commented on missing_biotools.txt
> +annotatemyids
Do we intend to keep this up-to-date? Maybe we should then add a requirement to IUC best practices.

2021-01-12 10:24 UTC, bgruening commented on missing_biotools.txt
> +annotatemyids
Oh, no I will remove this. This is more for @hmenager and @hansioan. I will open an issue on https://github.com/bio-tools/content

2021-01-12 10:29 UTC, bernt-matthias commented on missing_biotools.txt
> +annotatemyids
Still we could add a requirement here https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-cross-references, e.g, if the tool is in bio.tools the it must be annotated in the wrapper?

2021-01-12 10:53 UTC, bgruening commented
I think that most of the tools have been annotated and we could proceed. We have two possibilities here:

1) we write a small script that extracts EDAM ontologies from bio.tools and adds them to the tools
2) we add plumping to Galaxy to actually fetch (and cache) EDAM ontologies from bio.tools on-demand __iff__ there is a bio.tools ID but __no__ EDAM annotation

Adding EDAM directly to tools has the advantage that we could add version-specific annotations. But what are we doing with that? Are different versions than listed in different sections etc ...

If we agree with 2) we could merge this PR, otherwise, I think we should add the EDAM terms before merging.

@mvdbeek @hexylena @galaxyproject/iuc

2021-01-12 10:56 UTC, bgruening commented on missing_biotools.txt
> +annotatemyids
Yes, we should add this and encourage people. We might also lint it and suggest potential IDs.

2021-01-12 12:57 UTC, hexylena commented
@bgruening you said you had a list of pros/cons for each approach?  The main con that comes to my mind is then required internet connectivity to check with bio.tools which doesn't give me a great feeling.

2021-07-10 09:36 UTC, bgruening commented
Ok, that one is ready for review @galaxyproject/iuc

My proposal is we merge that one but do not push to the TS, but let those changes propagate with new tool updates over time.

I settled on only annotating bio.tool IDs, because EDAM ontologies are changing over time and updating them in the tools is cumbersome, especially because they also needs to be updated (by the bio.tools community) in bio.tools.

So my idea would be:

* if a tool has a bio.tools ID __only__ annotate it with bio.tools ID
* if a tool has __no__ bio.tools ID annotate with EDAM ontology directly if possible
* implement in Galaxy a mechanism to retrieve and cache a mapping of bio.tools ID to EDAM ontology and populate tools with annotation on the fly (we could do that even for DOIs and more annotations if we like)

What do you all think about that?

2021-07-10 09:40 UTC, hexylena commented on tools/bedtools/macros.xml
> -    </xml>
is this intentional?

2021-07-10 09:42 UTC, hexylena commented on tools/metaphlan2/metaphlan_hclust_heatmap.xml
> +            <param name="d" value="hamming"/>
new tool?

2021-07-10 09:43 UTC, hexylena approved these changes
Love the annotations! Let's do it. This is way easier than doing edam annotations natively

2021-07-10 10:22 UTC, bgruening commented
I removed the missing bio.tools files and put it on gist: https://gist.github.com/bgruening/08e60450db1a83792b83c6212ea7db47

2021-07-10 10:32 UTC, bgruening commented on tools/metaphlan2/metaphlan_hclust_heatmap.xml
> +            <param name="d" value="hamming"/>
yeah, that was a wrong rebase on my side, thanks for spotting, fixed all the comments :)

2021-07-10 11:30 UTC, hexylena commented
```
+Linting tool /home/runner/work/tools-iuc/tools-iuc/tools/deseq2/deseq2.xml
Failed linting
Applying linter tool_xsd... FAIL
.. ERROR: Invalid XML found in file: tmp8zw0dlmp. Errors [/tmp/tmp8zw0dlmp:24:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'xrefs': This element is not expected.]
```

I think that might be real?

2021-07-10 13:34 UTC, bgruening commented
@hexylena can we make sure those IDs are exposed via the GRT? That would enable a nice mapping for openebench and others.

2021-07-10 13:50 UTC, hexylena commented
It would be nice for sure! If we wanted that information it would require loading the complete galaxy toolbox in the GRT process to get access to that data which we haven't been doing as much (it's slow and complicated.) We could?

I really wish the TS had a better API for this (or even that just a mapping table existed somewhere) which had tool ID → biotools ID, that would be much easier to work with. I don't suppose that's something planemo monitor to scrape + build?

2021-07-10 15:27 UTC, hmenager requested changes
Absolutely awesome to see this, thanks a lot to all contributors!

Only one minor problem with deseq2, where bio.tools ref is included in both the tool XML and as an expanded macro

2021-07-10 15:48 UTC, hmenager commented
> I removed the missing bio.tools files and put it on gist: https://gist.github.com/bgruening/08e60450db1a83792b83c6212ea7db47

It looks like a few of these tools are now available in bio.tools:

```sh
cat missing_bio.tools.txt | xargs -I {} -n 1 wget --spider https://bio.tools/api/t/{} 2>&1 | egrep 'https://bio.tools|response...'
```

It gets me **21** 200 responses, and **86** 404s. Out of these 21, there are probably some false positives (e.g. tool named **cat** in bio.tools), but many seem to be recent additions.

2021-08-08 20:37 UTC, bgruening commented
@galaxyproject/iuc is it ok that we merge this PR. Cancel the build and let the annotation populate over time into the TS and our Galaxy instances?

2021-08-09 07:44 UTC, mvdbeek commented
IMO just update without version bump. What's the downside of not cancelling the upload?

2021-08-09 07:52 UTC, bgruening commented
> IMO just update without version bump. What's the downside of not cancelling the upload?

We create a lot of new tool updates without a new version. I'm always scared when we do that. And it means a lot of tool installation downstream.

2021-08-09 07:58 UTC, mvdbeek commented
> We create a lot of new tool updates without a new version. I'm always scared when we do that. And it means a lot of tool installation downstream.

These are minor bumps, the tools are updated in place on disk using hg update, there will be no new dependency installation and the update will be very quick. I don't think that is a good reason to not deploy.

2021-08-09 08:11 UTC, bgruening commented
I know but in practice :)
If you think its ok to merge and deploy let's do it. The sooner we get these IDs in production the sooner we can play with it in a meaningful way.

2021-08-09 08:42 UTC, mvdbeek approved these changes

2021-08-30 09:42 UTC, hexylena commented
We're getting the new tool panel, let's merge this so they'll be useful! :)

2021-08-30 09:42 UTC, hexylena approved these changes

2021-08-30 09:58 UTC, mvdbeek commented
We have some minor conflicts here, and I expect we'll continue to have lint errors, do we merge anyway ?

2021-08-30 10:11 UTC, bgruening commented
I fixed the merge conflicts I hope, would be great to get this in before I need to rebase again :(

2021-08-30 10:16 UTC, mvdbeek commented on tools/exonerate/exonerate.xml
> +	    <import>macros.xml</import>
@bgruening  There seems to be a tab here ... do you want to fix or ignore this ?

2021-08-30 10:34 UTC, mvdbeek commented on tools/scanpy/macros.xml
> +            <xref type="bio.tools">obitools</xref>
Oh, that looks wrong, doesn't it ?

2021-08-30 10:35 UTC, mvdbeek commented on tools/scanpy/macros.xml
> +            <xref type="bio.tools">obitools</xref>
```suggestion
            <xref type="bio.tools">scanpy</xref>
```
?

2021-08-30 10:36 UTC, mvdbeek commented on tools/scater/macros.xml
> +            <xref type="bio.tools">obitools</xref>
```suggestion
            <xref type="bio.tools">scater</xref>
```

2021-08-30 10:40 UTC, mvdbeek commented on tools/poretools/macros.xml
> +            <xref type="bio.tools">obitools</xref>
```suggestion
            <xref type="bio.tools">poretools</xref>
```

2021-08-30 11:12 UTC, bgruening commented on tools/exonerate/exonerate.xml
> +	    <import>macros.xml</import>
fixing! :) Latest commit. Thanks!

2021-08-30 13:46 UTC, merged

2021-08-30 13:47 UTC, hexylena commented
:tada: !

2021-08-30 13:48 UTC, bgruening commented
Wuhu! Thanks a lot for all the reviews! @jmchilton party time!