Expose genomeSAindexNbases parameter
galaxyproject/tools-iuc pull request #3513
Opened 2021-03-03 13:56 UTC by gallardoalba

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This PR exposes the genomeSAindexNbases parameter.

2021-03-05 11:32 UTC, bernt-matthias requested changes

2021-03-05 11:32 UTC, bernt-matthias commented on tools/rgrnastar/macros.xml
> +        <param argument="--genomeSAindexNbases" type="integer" min="2" max="16" value="14" label="Length of the SA pre-indexing string" help="Typically between 10 and 15. Longer strings will use much
I think you also extend the command section to actually use the parameter. Also some kind of test for the new parameter would be nice.

2021-03-05 15:00 UTC, gallardoalba commented on tools/rgrnastar/macros.xml
> +        <param argument="--genomeSAindexNbases" type="integer" min="2" max="16" value="14" label="Length of the SA pre-indexing string" help="Typically between 10 and 15. Longer strings will use much
Sure, I'll include it.

2021-03-09 14:11 UTC, wm75 commented
There is the related #3496. Maybe @pavanvidem and you @gallardoalba can coordinate which change should go in first, or whether you want to merge your work into one PR?

2021-03-09 15:26 UTC, gallardoalba commented
> There is the related #3496. Maybe @pavanvidem and you @gallardoalba can coordinate which change should go in first, or whether you want to merge your work into one PR?

I can add my modification to Pavan's branch :)

> There is the related #3496. Maybe @pavanvidem and you @gallardoalba can coordinate which change should go in first, or whether you want to merge your work into one PR?

I'll open a PR against the @pavanvidem branch.

2021-03-10 19:44 UTC, closed without merging