Ena upload update
galaxyproject/tools-iuc pull request #3618
Opened 2021-04-22 10:07 UTC by ieguinoa

Update ena_upload:
- Upgrade cli version
- Improved output to collect all metadata provided by the user (needed if they later want to do a consensus submission)
- Add support for paired list as input + test for it
- ..

2021-04-22 11:53 UTC, nsoranzo commented on tools/ena_upload/extract_tables.py
> +This file is json formatted and should be converted to a set of tabular files.
```suggestion
This file is JSON-formatted and should be converted to a set of tabular files.
```

2021-04-22 11:53 UTC, nsoranzo commented on tools/ena_upload/samples_macros.xml
> +                <!--<conditional name="input_select">-->
```suggestion
```

2021-04-22 11:53 UTC, nsoranzo commented on tools/ena_upload/samples_macros.xml
> +                <!--</conditional>-->
```suggestion
```

2021-04-22 11:53 UTC, nsoranzo commented on tools/ena_upload/ena_upload.xml
> +<tool id="ena_upload" name="ENA Upload tool" version="0.4" profile="20.01" license="MIT">
Not sure if there's a goal of syncing the tool version with the `ena-upload-cli`'s one. If yes, you can slow down the version here hoping the requirement version catches up.
```suggestion
<tool id="ena_upload" name="ENA Upload tool" version="0.3.1" profile="20.01" license="MIT">
```

2021-04-23 09:40 UTC, ieguinoa commented on tools/ena_upload/ena_upload.xml
> +<tool id="ena_upload" name="ENA Upload tool" version="0.4" profile="20.01" license="MIT">
that sounds good

2021-04-27 19:44 UTC, ieguinoa commented
@bgruening can you check if the paired input feature fits the format used by the covid19 workflows?

2021-04-27 20:30 UTC, bgruening commented on tools/ena_upload/process_xlsx.py
> +    print('YAML -------------')
should this be removed?

2021-04-27 20:30 UTC, bgruening commented on tools/ena_upload/process_xlsx.py
> +    print('YAML -------------')
remove?

2021-04-27 20:31 UTC, bgruening commented
@ieguinoa should we wait for https://github.com/usegalaxy-eu/ena-upload-cli/pull/10 or should this go into the next version. Estonia needs it as it seems!

2021-04-27 20:43 UTC, ieguinoa commented on tools/ena_upload/process_xlsx.py
> +    print('YAML -------------')
this is actually a feature. We use it to print in the same submission receipt all the metadata that was initially in the excel sheet or filled by the user in the UI. It's as a way of tracking provenance and also we use this receipt later as input for the consensus sequence submission, as it collects all data from user + accessions obtained from ena.

2021-04-27 20:45 UTC, ieguinoa commented
I haven't seen that PR, I'm willing to add it once it's ready in the new cli, but I would merge this version now.

2021-04-28 08:06 UTC, wm75 commented
https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L122

maybe add a `selected="true"` here to make a common case the default.

2021-04-28 08:09 UTC, wm75 commented
https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L137

There exists a **run_alias** field in ENA to let users specify their internal identifier/label of the run. I assume it's possible to specify this in the excel/user table branches? Would be good to offer here, too.
Estonian SARS-CoV-2 genome project samples specify this, for example.

2021-04-28 08:20 UTC, wm75 commented
https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L71
https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L72

The help seems to be wrong for this param: according to the validator and from inspecting existing ENA metadata the date formats seems to use `-` as the separator, not `/`.
In addition, the validator has a typo in `not collected`!

Beyond that, it may be helpful to use *suggested options* (https://docs.galaxyproject.org/en/latest/dev/schema.html#id31) on the text param here.

2021-04-28 09:01 UTC, wm75 commented
> https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L137
> 
> There exists a **run_alias** field in ENA to let users specify their internal identifier/label of the run. I assume it's possible to specify this in the excel/user table branches? Would be good to offer here, too.
> Estonian SARS-CoV-2 genome project samples specify this, for example.

Aha, I understood now that all aliases (at the study, samples, experiment *and* run level) are autogenerated in `extract_tables.py`. Maybe they could all have optional text fields, too?

2021-04-28 10:09 UTC, wm75 requested changes

2021-04-28 10:09 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
This won't work since `$pair.forward.name` and `$pair.reverse.name` will always be `forward` and `reverse`.

Something along the lines of:

```
            #set $safename_reads_file = re.sub('[^\w\-_\.]', '_', $pair.name)
            #set $safename_fwd_reads_file = $safename_reads_file + '_1'
            #set $safename_rev_reads_file = $safename_reads_file + '_2'
```

should work and catch the actual sample identifier.

2021-04-28 11:22 UTC, ieguinoa commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
I think that won't work in this case. I need the exact original identifier of each sample in the paired collection. The pair.name returns the name of the collection and we can't assume any relation with the element identifier, plus the user can just define a new one when creating the collection pair.
But as far as I could test, the $pair.forward.name gives the element identifier, while the $pair.forward.element_identifier always gives "forward" or "reverse" as you mentioned. As opposed to the single end reads (which is the other case of this conditional) that gives the real element identifier when using $file.element_identifier.
This was actually the core problem for me to add the paired end option, that's why I added a specific test for this, which creates a paired end collection and checks that the --data parameter in the command line (iterating over $files_to_upload and printing the elements) correctly lists the element identifiers.

2021-04-28 11:25 UTC, ieguinoa commented on tools/ena_upload/ena_upload.xml
> +    ln -s '$action_options.input_format_conditional.experiments_users_table' $experiments_table_path
added

2021-04-28 11:33 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
You're probably right about the `$pair.forward.element_identifier` vs `$pair.forward.name` distinction, but from a practical point of view, the user normally has the `$pair.name` under their control and not the `$pair.forward.name`.
The `$pair.name` will propagate through WFs that somehow start with a list of identifiers so by ensuring appropriate input, the user will automatically get good `$pair.name`s.
OTOH, a user *can* change the `forward` and `reverse` names, but only extremly tediously - by going to the pencil icon of each individual dataset.
I see the point about the assumption made about the `_1`, `_2` suffix in my suggestion, but this is standard ENA naming and we could just mention in the help that samples should be following that nomenclature in the table/xls.

2021-04-28 11:44 UTC, ieguinoa commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
yes, you are right about the _1 and _2 , and also would definitely be better to have some standardization with this.  I got some comments from people that the _1 and _2 is a standard for ENA but at least for the test servers I was able to push paired data with other names, so not sure what is the strict rule and couldn't find any official documentation on this. Do you have a link for this? or any more details... e.g is _R1 and _R2 allowed too?

2021-04-28 12:45 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
I don't have any documentation link for you, but even if things like `_R1`, `_R2` are allowed it doesn't mean we have to support that in the Galaxy wrapper. All that's needed imo is a help section explaining that no matter what your files were called before you uploaded them to Galaxy, once they are in Galaxy they will be called <paired_collection_name>_1 and <paired_collection_name>_2 and this is how they should be listed in the tabular/xls form.

2021-04-28 12:53 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
I just played this through with a concrete list:paired collection and it just makes more sense. The point is `$pair.forward.name` and `$pair.reverse.name` will initially be the names of the datasets you created the PE collection from. Assuming you haven't set new names for these datasets during and after uploading, these names will correspond to the file names that the user may know from outside Galaxy.
Now, however, imagine that user runs a single processing step inside Galaxy on that PE collection, the names will change depending on the tool. For example after running fastp on the collection, `$pair.forward.name` may be something like `fastp on data 4 and data 3`.

2021-04-29 12:24 UTC, ieguinoa commented on tools/ena_upload/ena_upload.xml
> +            #set $safename_rev_reads_file = re.sub('[^\w\-_\.]', '_', $pair.reverse.name)
ok, that changes things then... I didn't know tools could change the .name value. That's actually the reason why I asked if this feature would fit the way of handling paired lists in the workflows. Anyway, I changed it to fit your proposal and also added the extension to the files because the ena-upload-cli running downstream requires the extension to be in place.

2021-04-29 16:18 UTC, wm75 commented
Cool, I was just going to suggest what you did in that last commit 👍

2021-04-29 16:26 UTC, ieguinoa commented
> https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L71
> 
> 
> https://github.com/galaxyproject/tools-iuc/blob/c88b2e6ab83a055fc40295b14f7369b9f5c5a514/tools/ena_upload/samples_macros.xml#L72
> 
> The help seems to be wrong for this param: according to the validator and from inspecting existing ENA metadata the date formats seems to use `-` as the separator, not `/`.
> In addition, the validator has a typo in `not collected`!
> 
> Beyond that, it may be helpful to use _suggested options_ (https://docs.galaxyproject.org/en/latest/dev/schema.html#id31) on the text param here.

changed the collection_date parameter help, it needs to be separated with '-' and not '/'.
But didnt understand the idea of using options (was that what you meant?) as the date could be any date in the past.

2021-04-29 16:28 UTC, wm75 commented
> But didnt understand the idea of using options (was that what you meant?) as the date could be any date in the past.

I meant for the `not collected`, `not provided`, `restricted access` options.

2021-04-29 19:37 UTC, ieguinoa commented
> > But didnt understand the idea of using options (was that what you meant?) as the date could be any date in the past.
> 
> I meant for the `not collected`, `not provided`, `restricted access` options.

oh ok, done

2021-04-30 09:05 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #else:
The tool accepts also `fastq.bz2`/`fastqsanger.bz2`.
Not sure if ENA allows that, actually, and if what suffix they ask for then, but looks like that case needs handling here or be excluded from the input types.

2021-04-30 09:07 UTC, wm75 commented on tools/ena_upload/ena_upload.xml
> +            #else:
Apart from this, this looks all good to me.

2021-04-30 11:29 UTC, bgruening commented
There are now 3 additional columns available in the newest version (https://github.com/bioconda/bioconda-recipes/pull/28293):

* geographic_location_region
* geographic_location_latitude
* geographic_location_longitude

See here https://github.com/usegalaxy-eu/ena-upload-cli#supported-columns-for-viral-sample-submissions

Your call, if this should go in here or the next version.

2021-04-30 11:36 UTC, ieguinoa commented
I would put it in a separate version. I can start working right away on it and shouldn't be complicated but don't want to break anything for users that may have the metadata templates in this format. 
Also, some of the changes in this PR are part of what the reviewers commented on the paper we sent that uses this tool so I would prefer to have it pushed now.

2021-04-30 11:46 UTC, wm75 approved these changes
Thanks @ieguinoa !

2021-04-30 11:53 UTC, merged