fix pangolin tool
galaxyproject/tools-iuc pull request #3672
Opened 2021-05-16 21:01 UTC by bgruening

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2021-05-16 21:02 UTC, bgruening commented
@pvanheus can you please look at this.

2021-05-16 21:55 UTC, bernt-matthias commented on tools/pangolin/pangolin.xml
> +        && csvtk csv2tab report.csv | tail -n+2 >'$output1'
Can you check this with an assertion?

2021-05-17 19:51 UTC, bgruening commented on tools/pangolin/pangolin.xml
> +        && csvtk csv2tab report.csv | tail -n+2 >'$output1'
Not with the current test-data. I think I would need a mFASTA file. I will see if I find time to add this if you think this is required. Otherwise feel free to merge for this version.

2021-05-17 20:40 UTC, bernt-matthias approved these changes

2021-05-19 11:04 UTC, bernt-matthias requested changes

2021-05-19 11:04 UTC, bernt-matthias commented on tools/pangolin/test-data/test1.tsv
> -Consensus_EB232-crude-prep_S297.primertrimmed.consensus_threshold_0.75_quality_20	B.1.1	1.0	2021-04-14	passed_qc
This file seems unused

2021-05-19 11:38 UTC, bernt-matthias approved these changes

2021-05-19 11:55 UTC, bgruening commented
Sorry @bernt-matthias - Peter just requested a feature in the IUC gitter channel so I added it.

2021-05-19 12:07 UTC, pvanheus approved these changes

2021-05-19 12:10 UTC, bernt-matthias commented
@wm75 For `tabular` the first line is not used a header. A function `get_column_names` is called but it does noting for `tabular`

https://github.com/galaxyproject/galaxy/blob/37a15c5319c8a8643a9ebc59c35e4802d1fd7b66/lib/galaxy/datatypes/tabular.py#L370

I also remember that this worked .. but maybe I dreamed as well.

2021-05-19 13:03 UTC, bgruening commented
please feel free to merge, I'm done :)

2021-05-19 13:18 UTC, merged