Cutadapt: remove duplicated cut option
galaxyproject/tools-iuc pull request #3754
Opened 2021-06-24 16:13 UTC by mblue9

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

An eagle-eyed user noticed that the cut option is present twice. It was in the tool form listed as the short form -u (as -U is the option for Read 2) and it was recently added again as --cut. This PR removes the --cut option and adds `(--cut)` to the help for the -u option to clarify it is the --cut option.

2021-06-25 09:22 UTC, mvdbeek approved these changes
Thanks, that looks good! Can you update the GALAXY_TOOL_VERSION macro ?

2021-06-25 09:32 UTC, mblue9 commented
Ok great, I wasn't sure whether to update the wrapper version as it's a more of a tool form/bug fix but done now. Thanks!

2021-06-25 09:59 UTC, mvdbeek commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
Sorry, upon closer inspection, are these actually the same parameters ? It seems this is `-u`, as indicated by `argument="-u"`, while the parameter you removed is the `--cut` parameter.

2021-06-25 11:08 UTC, mblue9 commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
It's confusing --cut is the long name, -u is the short name, see here https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads

2021-06-28 10:31 UTC, bernt-matthias requested changes
The change seems good to me, but currently the `cut` parameter is not set on the command line. Also it would be nice to use the section in the test definitions.

2021-06-28 13:08 UTC, mblue9 commented
>The change seems good to me, but currently the cut parameter is not set on the command line. 

Thanks for having a look. Isn't it here in the command line as `-u` ? https://github.com/galaxyproject/tools-iuc/blob/2b4ce00ae6554d456850182331d2ad3a073b4188/tools/cutadapt/macros.xml#L66

>Also it would be nice to use the section in the test definitions.

Happy to do that. I think it'll mean adding the r1 or r2 section into all 27 tests so just to check before I do that, is this what you mean?  https://github.com/galaxyproject/tools-iuc/pull/3754/commits/c842f2cdb7ab2f8402bb1cedb759b21ed1bffdc3

2021-06-28 13:20 UTC, bernt-matthias approved these changes
> Happy to do that. 

Yep, that's what I meant.

2021-06-29 06:51 UTC, bernt-matthias commented
@mvdbeek is this one good to go? looks good to me.

2021-06-29 08:56 UTC, mvdbeek commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
```suggestion
                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if paired). If positive, remove bases from the beginning. If negative, remove bases from the end. This is applied *before* adapter trimming (which is controller by --cut)." />
```
is that how it should be ? If you use `argument="-u"` the `-u` will be appended to the end of the help text, so that might be confusing.

2021-06-29 08:57 UTC, mvdbeek commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
Or should this be
```suggestion
                <param name="cut" argument="--cut" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if paired). If positive, remove bases from the beginning. If negative, remove bases from the end. This is applied *before* adapter trimming. (--cut)" />
```

2021-06-29 08:58 UTC, mvdbeek commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
Or 
```suggestion
                <param name="cut" argument="-u/--cut" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if paired). If positive, remove bases from the beginning. If negative, remove bases from the end. This is applied *before* adapter trimming. (--cut)" />
```
? 😆

2021-06-29 10:09 UTC, mblue9 commented on tools/cutadapt/macros.xml
> +                <param name="cut" argument="-u" type="integer" value="0" optional="True" label="Cut bases from reads before adapter trimming" help="Remove bases from each read (first read only if pai
😄 I like the last one the best as it has -u which hopefully makes it obvious that -U is the corresponding option for read 2. But just noticed it looks like this so need to remove one `--cut`
>Remove bases from each read (first read only if paired). If positive, remove bases from the beginning. If negative, remove bases from the end. This is applied *before* adapter trimming. (--cut) (-u/--cut)

2021-07-02 20:21 UTC, bgruening approved these changes

2021-07-02 20:55 UTC, merged