Presto addition
galaxyproject/tools-iuc pull request #3977
Opened 2021-09-21 10:09 UTC by aerijman

FOR CONTRIBUTOR:
* [x ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2021-09-21 19:44 UTC, bgruening commented
@aerijman please update the tool version. https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?highlight=version#tool-versions

2021-09-21 19:56 UTC, bernt-matthias requested changes

2021-09-21 19:56 UTC, bernt-matthias commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output"/>
Argument should be ` -- failed`, or?

2021-09-21 19:56 UTC, bernt-matthias commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output"/>
Hmm you extend a test for this functionality?

2021-09-22 00:41 UTC, aerijman commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output"/>
`--failed` outputs reads that couldn't be synced between the reads fwd and rev. We used those to generate histograms with all the data, not only reads that could be paired.  Without this argument we only get fastqs with reads that could be synced

2021-09-22 07:35 UTC, bernt-matthias commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output"/>
Argument is `argument="failed_fastq` which will lead to adding (failed_fastq) to the parameter's help. This is confusing for the user since the cli parameter seems to be `--failed`.

2021-09-22 07:37 UTC, bernt-matthias commented
Please also add a recent profile to the tools.

2021-09-22 14:33 UTC, aerijman commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output"/>
My apologies if there are more succinct ways of doing this.

2021-09-22 14:35 UTC, aerijman commented
profile reflects newest galaxy release. Let me know if this is ok or should I change it! Danke!

2021-09-22 15:25 UTC, bernt-matthias reviewed
Profile 21.05 is to new. Then users with not so recent installations can not use the tool. Make it 20.05 at most.

2021-09-22 15:25 UTC, bernt-matthias commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output" help="--failed"/>
```suggestion
        <param argument="--failed" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output" />
```

otherwise help will become `"--failed (failed_fastq)"` and you also need to adapt the command block. 

The idea of `argument` is to add the command line argument to the end of the help text. Then users know which command line argument is controlled with the tool parameter. Furthermore the cheetah variable for the command is auto generated (leading dashed are removed and internal dashes replaced by underscore).

2021-09-22 16:45 UTC, aerijman commented on tools/presto/presto_pairseq.xml
> +        <param argument="failed_fastq" type="boolean" value="False" truevalue="--failed" falsevalue="" label="Failed reads fastq output" help="--failed"/>
Thank you for the explanation!!!

2021-09-22 19:34 UTC, aerijman commented
@bernt-matthias ready to merge?

2021-09-23 07:40 UTC, bernt-matthias commented
@aerijman there are still a few of my suggestions open. Please accept them or respond why they should not be accepted...

2021-09-23 16:56 UTC, aerijman reviewed
I don't have the power to approve the changes. I DO accept them

2021-09-24 07:56 UTC, bernt-matthias commented
There is a button `accept changes` below the suggestion. But I will do this for you :)

2021-09-24 08:02 UTC, bernt-matthias commented
@aerijman .. my mistake .. actually I forgot to submit my last review :(

2021-09-24 09:00 UTC, bernt-matthias commented on tools/presto/presto_macros.xml
> +    <token name="@TOOL_VERSION@">0.6.2.1</token>
```suggestion
    <token name="@TOOL_VERSION@">0.6.2</token>
```

2021-09-24 09:55 UTC, bernt-matthias approved these changes

2021-09-25 18:03 UTC, merged