Update Stacks2
galaxyproject/tools-iuc pull request #4316
Opened 2022-01-04 19:22 UTC by gallardoalba

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This PR includes a functionality requested by a user in [GHelp](https://help.galaxyproject.org/t/stacks2-process-radtags-doesnt-have-a-no-barcode-option/7206).

2022-01-20 10:13 UTC, bernt-matthias requested changes
According to the source code this should also work for `shortreads`, so I would prefer to keep the macros.

2022-01-20 10:13 UTC, bernt-matthias commented on tools/stacks2/macros.xml
> +    <xml name="barcode_selector">
I would prefer a solution without an additional conditional .. if possible.

Maybe we simply add an option `disable` to the `barcode_encoding` select and make the `barcode` parameter optional .. adding to the help that the barcode file is only used if `barcode_input != disabled`.

2022-01-20 10:13 UTC, bernt-matthias commented on tools/stacks2/macros.xml
> +            <requirement type="package" version="@TOOL_VERSION@">stacks</requirement>
That's a good idea. Then we should have 2.60 soon :)

2022-04-07 19:26 UTC, gallardoalba commented on tools/stacks2/macros_process.xml
> +        <yield/>
Done!

2022-04-07 19:26 UTC, gallardoalba commented on tools/stacks2/macros.xml
> +    <xml name="barcode_selector">
Done!

2022-04-08 08:32 UTC, bernt-matthias commented
Thanks for working on this @gallardoalba .. once the tests are successful I would like to add the commits from https://github.com/galaxyproject/tools-iuc/pull/4194 .. is this fine for you?

2022-04-08 08:54 UTC, gallardoalba commented
> Thanks for working on this @gallardoalba .. once the tests are successful I would like to add the commits from #4194 .. is this fine for you?

Sure. Thanks you so much for your review.

2022-04-11 08:15 UTC, bernt-matthias commented on tools/stacks2/test-data/shortreads/PopA_01.fq
> -@lane1_fakedata0_0 1:N:0:/1
This test file should not become empty, or? 

Can we extend `test-data/gentest,sh` by calls to `shortreads` and `procrad` which generates these files and then reproduce it witch the Galaxy tools?

2022-04-11 08:58 UTC, gallardoalba commented on tools/stacks2/test-data/shortreads/PopA_01.fq
> -@lane1_fakedata0_0 1:N:0:/1
Sure, I'll have a look at this.

2022-04-13 18:09 UTC, bernt-matthias commented
I added my commits. Lets see if it works.

2022-04-13 19:25 UTC, bgruening approved these changes

2022-04-13 20:54 UTC, bernt-matthias approved these changes

2022-04-13 20:54 UTC, bernt-matthias commented
@gallardoalba could you double check my changes before merging?

2022-04-14 08:27 UTC, gallardoalba commented
> @gallardoalba could you double check my changes before merging?

It seems fine to me.

2022-04-14 08:28 UTC, bernt-matthias approved these changes

2022-04-14 08:28 UTC, merged

2022-04-14 08:28 UTC, bernt-matthias commented
Cool. Thanks @gallardoalba