Updating tools/read_it_and_keep from version 0.1.0 to 0.2.1
galaxyproject/tools-iuc pull request #4384
Opened 2022-02-04 11:21 UTC by planemo-autoupdate

Hello! This is an automated update of the following tool: **tools/read_it_and_keep**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/read_it_and_keep from version 0.1.0 to 0.2.1.

**Project home page:** https://github.com/GenomePathogenAnalysisService/read-it-and-keep/releases

2022-02-04 11:37 UTC, simonbray approved these changes
only change is `Improved MacOS compiler compatibility`

2022-02-04 11:38 UTC, simonbray commented
> only change is `Improved MacOS compiler compatibility`

Sorry, I was too fast; there's also `Adds new command line option --enumerate_names` from version 0.2.0

2022-02-04 21:05 UTC, bgruening commented
ping @mira-miracoli :)

2022-02-07 13:32 UTC, simonbray commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <param name="enumerate_names" value="True" />
```suggestion
            <param name="enumerate_names" value="--enumerate_names" />
```
Is the test passing at the moment? I think you need to specify it like this.

2022-02-07 13:33 UTC, simonbray commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <param name="enumerate_names" type="boolean" truevalue="--enumerate_names" falsevalue="" label="rename the reads 1,2,3,... (for paired reads, will also add /1 or /2 on the end of names))"
```suggestion
            <param name="enumerate_names" type="boolean" truevalue="--enumerate_names" falsevalue="" label="Rename the reads 1,2,3,... (for paired reads, will also add /1 or /2 to the end of names)" />
```

2022-02-07 13:50 UTC, wm75 commented
@mira-miracoli you also need to use the new param somewhere in the command block

2022-02-07 13:54 UTC, wm75 commented
and while you're at it, you may also want to implement a `<version_command>`- `readItAndKeep --version` should be all that's needed.

2022-02-07 14:01 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <param name="enumerate_names" value="--enumerate_names" />
Here, `value="true"` is correct :)
You want to test that the param, when checked, evaluates to its truevalue.
Your current test will also work but it short-circuits the logic so is less conclusive.

2022-02-07 14:04 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <param name="enumerate_names" value="--enumerate_names" />
and, of course, you'll have to adjust the test data since the option will change all read names in the output. It's actually a good thing though to have the test fail once to demonstrate it can catch something, then fix it.

2022-02-07 14:06 UTC, mira-miracoli commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <param name="enumerate_names" value="--enumerate_names" />
ok first version was correct @simonbray 
I'll fix that, too

2022-02-18 12:14 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" file="output_test1.fastq.gz" >
Tests fail because: 

```
Collection element forward of collection output_collection:  different than expected, difference (using diff):
( /tmp/tmpesn8_wjsoutput_test1.fastq.gz v. /tmp/tmpstccecuhoutput_test1.fastq.gz )
Binary data detected, not displaying diff
```

Maybe we can just remove the test files and rely on the size comparison?

2022-02-21 19:01 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" file="output_test3.fastq.gz">
```suggestion
            <output name="output_reads1" file="output_test3.fastq.gz">
```

then it should work

2022-02-21 19:29 UTC, bgruening commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" file="output_test3.fastq.gz">
You can accept this suggestion via the github interface @mira-miracoli

2022-02-22 09:51 UTC, bgruening approved these changes

2022-02-22 10:51 UTC, wm75 commented
@mira-miracoli This is unrelated to your update efforts, but can you check whether this tool can actually handle *uncompressed* fastq input (from a very quick look at the source, it seems it can't, but knows how to handle `fasta.gz` instead).
If that's the case, the `@FASTQ_FORMATS@` token would have to be adjusted (and mayb be renamed to just `@INPUT_FORMATS@`.

Thanks for all your work!

2022-02-22 13:48 UTC, mira-miracoli commented
> @mira-miracoli This is unrelated to your update efforts, but can you check whether this tool can actually handle *uncompressed* fastq input (from a very quick look at the source, it seems it can't, but knows how to handle `fasta.gz` instead).
> If that's the case, the `@FASTQ_FORMATS@` token would have to be adjusted (and mayb be renamed to just `@INPUT_FORMATS@`.
> 
> Thanks for all your work!

Sure, I can do! Would next week be fast enough? Thank you for your reviews :)

2022-02-22 16:14 UTC, wm75 commented
> Sure, I can do! Would next week be fast enough? Thank you for your reviews :)

Of course, take your time :)

2022-03-01 10:10 UTC, mira-miracoli commented
@wm75 I had a look at the source code and the relevant libraries and I think it should be able to handle fastq as well.
I found no specific file format check for the input file in the read-it-and-keep source.
According to the [source](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/zlib.h#L1328) of zlib.h it doesn't matter whether the file is compressed or not. I found similar information about the [kseq.h](http://attractivechaos.github.io/klib/#Kseq%3A%20stream%20buffer%20and%20FASTA%2FQ%20parser) library - kseq should be able to parse both fasta and fastq, compressed or uncompressed.
I can adjust the format tokens now, if you want.

2022-03-01 10:29 UTC, wm75 commented
@mira-miracoli Thanks for checking, and for explaining why that works!
Yes, then just adding fasta and fasta.gz as supported input formats would be awesome.
In addition, it would be good to stick to the input format on output. The current version behaves like the command line tool, i.e. produces gzipped output unconditionally, and you'd have to add a decompression step at the end if the input was uncompressed, plus make the format in the output section input-dependent, too.

2022-03-09 12:41 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            ln -s '$reads.read2.ext' read2.ext &&
With `.ext` you're only getting the typical extension of the input dataset's type, not the full file name of the file.
You could do something like
`ln -s '$reads.read1' read1.${reads.read1.ext}`
where `$reads.read1` would evaluate to some Galaxy-managed .dat file and `${reads.read1.ext}` would be `fasta` for example. However, I don't think this tool looks at the file suffix at all so you can also just symlink the read1 dataset to `read1` and the read2 dataset to `read2` in all cases.

2022-03-09 12:41 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
>          <data name="output_reads1" format="fastqsanger.gz" label="Filtered reads ${on_string} - reads1" from_work_dir="output.reads_1.fastq.gz">
```suggestion
        <data name="output_reads1" format_source="reads.read1" label="Filtered reads ${on_string} - reads1" from_work_dir="output.reads_1.fastq*">
```

This will discover gzipped or uncompressed files and set the format according to the input.
Do the same for the other output cases.

2022-03-11 09:45 UTC, mira-miracoli commented on tools/read_it_and_keep/read-it-and-keep.xml
>          <data name="output_reads1" format="fastqsanger.gz" label="Filtered reads ${on_string} - reads1" from_work_dir="output.reads_1.fastq.gz">
Thank you for your help! :)

2022-03-14 15:09 UTC, mira-miracoli commented
> @mira-miracoli I fixed an issue with `format_source` not handling qualified/nested parameters. I also found that the output suffix of the command line tool reflects the detected input format (i.e. it's .fasta(.gz) for fasta, and .fastq(.gz) for fastq) and included logic to handle this.
> 
> What's missing are additional tests for fasta and uncompressed fastq inputs. Can you add those? Then I think we're done here.

Thank you! Yes I can add those tests.

2022-03-15 14:19 UTC, wm75 commented
Thanks @mira-miracoli !
Final cleanup:
- I think all `output.test1.*` test files are identical to their `output.test2.*` counterparts (cause the only difference between those tests is whether the input comes as two individual datasets or as a paired collection) -> please remove the duplicates
- All `output.*.fasta.gz` are actually plain text fasta files. That's because you're declaring `ftype="fasta"` for the `fasta.gz` inputs in those tests. When you do that, planemo uploads the .gz files to Galaxy, which decompresses them *before* feeding them to the tool. In other words you're not really testing for handling of fasta.gz in the wrapper (only if Galaxy knows how to decompress the format).
- A better way would be the other way round: use the fasta.gz input files in all tests related to Fasta format. Declare `ftype="fasta.gz"` for tests of fasta.gz handling, but `ftype="fasta" for testing fasta handling. This way you can get rid of the uncompressed input files. I assume the same trick should work for fastqsanger tests.

2022-03-17 09:24 UTC, wm75 commented
Thank you @mira-miracoli for bearing with me and my requests for additional changes.
This started out as a simple version bump, but the result now is a significantly enhanced wrapper so thanks for all your work on this!

2022-03-17 09:24 UTC, wm75 approved these changes

2022-03-17 09:34 UTC, bernt-matthias requested changes

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +        <token name="@INPUT_FORMATS@">fasta,fastq,fastq.gz,fasta.gz,fastqsanger,fastqsanger.gz</token>
`fastq` should imply fastqsanger and also the other fastq formats. I think this is unwanted / redundant?

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
`ftype` should be `fasta.gz`

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test3.fastq.gz" ftype="fastqsanger"/>
`ftype` should be `fastqsanger.gz`

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                        <element name="forward" value="test1.fasta.gz" ftype="fasta" />
please check all the `ftype` attributes of test in and outputs

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" decompress="true" file="output.test1.reads_1.fastq" ftype="fastqsanger.gz"/>
`ftype`?

2022-03-17 09:34 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" decompress="true" file="output.test1.reads_1.fastq" ftype="fastqsanger.gz"/>
`decompress`?

2022-03-17 09:40 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                        <element name="forward" value="test1.fasta.gz" ftype="fasta" />
see my explanation above

2022-03-17 09:42 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +            <output name="output_reads1" decompress="true" file="output.test1.reads_1.fastq" ftype="fastqsanger.gz"/>
Here the wrapper is expected to produce "fastqsanger.gz", but the result gets compared to a decompressed fastq used in other tests.

2022-03-17 09:43 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
Not sure if this really works. 

I think the automatic extraction only works if the tool accepts only the uncompressed type and a compressed file is given in the test (then an additional converter job should run). But here the tool accepts compressed and uncompressed. 

I'm not 100% sure. So I would suggest to add `file ...` calls to the tool command to verify what file types the command gets.

If I'm wrong we should document this somewhere (if it isn't already) .. clearly this behavior would be handy.

2022-03-17 09:46 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
Well, the tests themselves kind of prove that's working. The wrapper respects the input format on output and the test is checking the output format -> the tool must have seen fasta.

2022-03-17 09:47 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
Note that Galaxy currently basically does not check `ftype` at all in tests: https://github.com/galaxyproject/galaxy/pull/12073 .. but it's difficult to fix.

2022-03-17 09:59 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
So lets just ask the tests: I've pushed a commit that violates the test assumptions. Lets see if that makes the tests fail.

2022-03-17 10:10 UTC, bernt-matthias commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
Seems really to work :) I checked with `file ...`. Also your argument with `format_source` and checking the output `ftype` is convincing. 

Do you know if this is documented somewhere? This is really cool, because it can save loads of test data size. 

Last thing I noticed is that the version of the python requirement should be specified

2022-03-17 10:25 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
> Do you know if this is documented somewhere? This is really cool, because it can save loads of test data size.

Don't know if it's documented. I thought it's a logical extension of Galaxy's normal upload behavoir (you can do the same thing from the UI Upload data dialog). Never thought of using this in tests before until @mira-miracoli did so by accident in one of her commits :)

2022-03-17 10:28 UTC, wm75 commented on tools/read_it_and_keep/read-it-and-keep.xml
> +                <param name="read1" value="test1.fasta.gz" ftype="fasta" />
Ok, and the tests are just failing now as expected with the expected format complaints.

2022-03-17 10:48 UTC, bernt-matthias approved these changes

2022-03-17 10:49 UTC, merged

2022-03-17 11:03 UTC, bernt-matthias commented
https://github.com/galaxyproject/galaxy/pull/13568