FASTQ-splitter: add output labels to identify forward and reverse
galaxyproject/tools-iuc pull request #4414
Opened 2022-02-19 10:53 UTC by PlushZ

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2022-02-19 16:32 UTC, bgruening approved these changes
Thanks @PlushZ

2022-02-20 23:02 UTC, bernt-matthias requested changes

2022-02-20 23:02 UTC, bernt-matthias commented on tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
> +        <data name="output1_file" format_source="input1_file" label="${tool.name} on ${on_string}: Left-hand reads"/>
Forward and reverse may be more standard?

2022-02-21 07:49 UTC, bebatut commented on tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
> +        <data name="output1_file" format_source="input1_file" label="${tool.name} on ${on_string}: Left-hand reads"/>
I told @PlushZ to put left and right because it is how it is named in the help section. Should we modify here and the help section?

2022-02-21 08:34 UTC, bernt-matthias commented on tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
> +        <data name="output1_file" format_source="input1_file" label="${tool.name} on ${on_string}: Left-hand reads"/>
Would be my preference to also change help.

2022-03-05 10:49 UTC, bgruening approved these changes

2022-03-09 07:57 UTC, bernt-matthias approved these changes

2022-03-09 07:58 UTC, merged

2022-03-09 07:58 UTC, bernt-matthias commented
Thanks @PlushZ