Update bakta to 1.5.1 and database options
galaxyproject/tools-iuc pull request #4947
Opened 2022-11-25 08:34 UTC by pimarin

- Update Bakta tool to the last tool version
- Add a filter option to filter available bakta database

2022-11-25 08:34 UTC, pimarin commented
In the last update maybe, I will add the amrfinderplus database option when the DM will be updated

2022-11-29 14:47 UTC, pimarin commented
?

2022-12-05 10:32 UTC, pimarin commented
I finished to implement test to the last version and also I pre-added the choise of database from bakta-db data manager and amrfinderplus data manager

2022-12-10 21:41 UTC, bgruening approved these changes

2022-12-12 16:01 UTC, pimarin commented
thank you to your patience !

2022-12-14 09:01 UTC, oschwengers commented
Thank you so much @pimarin for all the effort you've put into this, also thanks @bgruening for all your support!

May I kindly ask you to fast-track this PR to [v1.6.1](https://github.com/oschwengers/bakta/releases/tag/v1.6.1) which is a patch release fixing some minor but annoying bugs? Then we can cut corners skipping an additional PR for 1.6.0->1.6.1

2022-12-16 15:54 UTC, bernt-matthias commented on tools/bakta/macro.xml
> +    <token name="@TOOL_VERSION@">1.6.0</token>
```suggestion
    <token name="@TOOL_VERSION@">1.6.1</token>
```

2022-12-16 16:02 UTC, bernt-matthias submitted a review, later dismissed

2022-12-16 16:02 UTC, bernt-matthias commented on tools/bakta/bakta.xml
> +        #if "skip_pseudo" in $workflow.skip_analysis
Just for the fun of it:

```
#echo " ".join(["--"+s.replace("_", "-") for s in $workflow.skip_analysis])
```

might replace all this. 

Alternatively, if you rename the values of the select such that they are equal to the command line options then this would simplify to 

```
#echo " ".join($workflow.skip_analysis)
```

2022-12-16 16:03 UTC, bernt-matthias commented
> May I kindly ask you to fast-track this PR to [v1.6.1](https://github.com/oschwengers/bakta/releases/tag/v1.6.1)

Lets see if this just works out.

@pimarin let us know if this is finished from your side

2022-12-16 16:07 UTC, oschwengers commented on tools/bakta/bakta.xml
> -        #if $annotation.prodigal
No. It was deactivated due to a bug that, however, was fixed by 1.6.1

2022-12-16 16:09 UTC, bernt-matthias commented on tools/bakta/bakta.xml
> -        #if $annotation.prodigal
OK. Then lets keep it.

2022-12-16 16:14 UTC, bernt-matthias requested changes
@pimarin 

could you restore the argument? 

the tests fail because output contains versions and dates .. they will be successful if a few lines of difference are allowed: `lines_diff`. could you adapt this?

2022-12-16 16:33 UTC, bgruening commented
Great work everyone. This work is very well received by the community. On EU we already have more than 1000 tool runs.

2022-12-16 17:14 UTC, pimarin commented
I will change all thank's to your comments !

2022-12-19 09:47 UTC, pimarin commented on tools/bakta/bakta.xml
> +        #if "skip_pseudo" in $workflow.skip_analysis
this is so good !
I updated it !

thank you !

2022-12-19 09:47 UTC, pimarin commented
I take comments and update for database new options (amrfinderplus and bakta DM)
I also change code with your suggestion @bernt-matthias

2022-12-20 19:21 UTC, bgruening approved these changes
Good from my side! Awesome work @pimarin!

2022-12-21 08:50 UTC, bernt-matthias commented on tools/bakta/test-data/TEST_3/TEST_3.log
> -export annotation results to: /tmp/tmpmnqj1xog/job_working_directory/000/6/working
One more minor thing. There is quite a lot of test data that is only changed because of differences in: 

- version
- dates
- paths

I would prefer if this would be reverted and in the test differences would be allowed by `lines_diff`.

2022-12-21 08:51 UTC, bernt-matthias commented on tools/bakta/test-data/TEST_3/TEST_3.log
> -export annotation results to: /tmp/tmpmnqj1xog/job_working_directory/000/6/working
The advantage is that it (hopefully) simplifies future updates.

Also, differences due to date or paths will just fail the weekly CI test running next sunday.

2022-12-21 09:48 UTC, pimarin commented
Thank you to you work also @bernt-matthias for all my PR !

2022-12-21 15:42 UTC, pimarin commented
I update following your comments, 
- I changed number of output but keeping the toolbox, just by default their is a minimum of 4 files

2022-12-21 15:47 UTC, bernt-matthias reviewed
Seems that you restored the changes to the test data (probably you run `planemo test` with `--update-test-data` and just commit everything. 

Can you undo this?

2022-12-21 20:28 UTC, bernt-matthias approved these changes
I removed the unneeded test file changes again. 

Also I removed the svg test data .. its always better to use a size assertion instead of a sim_size comparison.

Also removed unneeded lines_diff from outputs that show no difference.

2022-12-21 20:29 UTC, bernt-matthias commented
Thanks a lot @pimarin.

2022-12-21 20:43 UTC, merged