Ivar annotation as input added
galaxyproject/tools-iuc pull request #5008
Opened 2022-12-16 17:01 UTC by tuncK

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2022-12-16 17:29 UTC, bgruening commented on tools/ivar/ivar_consensus.xml
> +<tool id="ivar_consensus" name="ivar_consensus" version="@TOOL_VERSION@+galaxy@VERSION_SUFFIX@" profile="@PROFILE@">
I would not change the name. The name is exposed to the user - and what does a underscore tells the user?

2022-12-16 17:29 UTC, bgruening commented on tools/ivar/ivar_removereads.xml
> -        <requirement type="package" version="3.8.1">python</requirement>
python is only a dependency for this tool, not the others isn't it?

Moving it to the macro will make it a dependency fo all tools.

2022-12-16 17:29 UTC, bgruening commented on tools/ivar/ivar_trim.xml
> -        <requirement type="package" version="1.15">samtools</requirement>
Is samtools not needed anymore?

2022-12-16 17:33 UTC, tuncK commented on tools/ivar/ivar_trim.xml
> -        <requirement type="package" version="1.15">samtools</requirement>
The tool depends on samtools 1.18 (?), so I dont see why we need to add in an earlier version explicitly.

2022-12-16 17:33 UTC, tuncK commented on tools/ivar/ivar_consensus.xml
> +<tool id="ivar_consensus" name="ivar_consensus" version="@TOOL_VERSION@+galaxy@VERSION_SUFFIX@" profile="@PROFILE@">
Will fix, copy-paste accident.

2022-12-16 17:36 UTC, tuncK commented on tools/ivar/ivar_removereads.xml
> -        <requirement type="package" version="3.8.1">python</requirement>
3 of 5 tools need python, I thought it would be easier to maintain.

2022-12-16 17:36 UTC, bgruening commented on tools/ivar/ivar_trim.xml
> -        <requirement type="package" version="1.15">samtools</requirement>
So the conda packages as a samtools dependency? Then we can remove it here.

2022-12-16 17:37 UTC, bgruening commented on tools/ivar/ivar_removereads.xml
> -        <requirement type="package" version="3.8.1">python</requirement>
its ok, we can do that, less containers I guess.

2022-12-16 18:05 UTC, wm75 commented on tools/ivar/macros.xml
> +  <token name="@VERSION_SUFFIX@">3</token>
This does not make sense. There should not be one version suffix for all wrappers since they do not always get updated all at once. In fact, this change would *downgrade* ivar_trim.

2022-12-16 18:08 UTC, wm75 commented on tools/ivar/ivar_removereads.xml
> -        <requirement type="package" version="3.8.1">python</requirement>
It's ok, but also no big gain, and Python is only a requirement for those subcommands where @pvanheus and me added significant extra logic to the command line tool, i.e., it's not a very native requirement.

2022-12-16 18:09 UTC, wm75 commented on tools/ivar/ivar_removereads.xml
> +        help="BAM dataset, preprocessed with ivar trim, to remove reads from"/>
I would prefer not having all these cosmetic changes. It takes a lot of time inspecting such a non-minimal diff and understand what the *functional* change is in the PR.

2022-12-16 18:19 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +    <expand macro="requirements"/>
Ha, self-defeating argument above ;)
This wrapper relying on ivar's shipped samtools for something non-trivial. Haven't written this wrapper though, but @pvanheus did. Imo, this use here should require a pinned samtools version, but I'm open for other views.

2022-12-16 18:23 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +        <param name="gtf" argument="-g" optional="true" type="data" format="gff" label="Coordinates of ORFs, in GFF3 format (optional)"/>
Have you tested using this option when asking for VCF output. Not sure the wrapper will be able to handle this adequately.

2022-12-16 18:24 UTC, tuncK commented on tools/ivar/ivar_variants.xml
> +        <param name="gtf" argument="-g" optional="true" type="data" format="gff" label="Coordinates of ORFs, in GFF3 format (optional)"/>
Yes, tests 4 &5 check this (or I think they do so)

2022-12-16 18:25 UTC, wm75 commented on tools/ivar/test-data/zika/Z52_a.vcf
> +PRV	5680	.	C	T	.	PASS	DP=35;REF_DP=27;REF_RV=10;REF_QUAL=44;ALT_DP=8;ALT_RV=3;ALT_QUAL=46;AF=0.228571
This might actually be an illustration of what I'm talking about above since the changed count could come from a slightly different pileup produced by the latest version of samtools.

2022-12-16 18:26 UTC, wm75 requested changes
Sorry for the many comments, but ivar being a core tool suite for some of our most important workflows needs to be handled extra-carefully.

2022-12-16 18:30 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +        <param name="gtf" argument="-g" optional="true" type="data" format="gff" label="Coordinates of ORFs, in GFF3 format (optional)"/>
Aha, so test 4 shows that it's working with tabular output and test 5 would actually demonstrate that annotation is non-functional for VCF (cause you didn't have to change that test file).

It doesn't make much sense then to reveal this param for VCF output, but it should be a suboption for tabular only.
VCF files are better annotated after the fact with e.g. SnpEff anyway.

2022-12-16 19:11 UTC, tuncK commented on tools/ivar/ivar_variants.xml
> +        <param name="gtf" argument="-g" optional="true" type="data" format="gff" label="Coordinates of ORFs, in GFF3 format (optional)"/>
Good idea, done.

2022-12-16 19:38 UTC, tuncK commented on tools/ivar/macros.xml
> +  <token name="@VERSION_SUFFIX@">3</token>
Did not think of it, fixed.

2022-12-16 20:03 UTC, tuncK commented on tools/ivar/test-data/zika/Z52_a.vcf
> +PRV	5680	.	C	T	.	PASS	DP=35;REF_DP=27;REF_RV=10;REF_QUAL=44;ALT_DP=8;ALT_RV=3;ALT_QUAL=46;AF=0.228571
I am not sure if this can explain the change in output. The deployed version uses samtools without specifying its version (https://github.com/galaxyproject/tools-iuc/blob/8487d2c73793be0afa5b34388b122e686ac8a094/tools/ivar/ivar_variants.xml#L7). Only trimming does. Regardless, I added a samtools v1.16 to the entire container to avoid such risks.

2022-12-17 15:06 UTC, wm75 requested changes

2022-12-17 15:06 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +                <param name="gtf" argument="-g" optional="true" type="data" format="gff" label="Coordinates of ORFs, in GFF3 format (optional)"/>
It would be good to have some help here to inform the user what these coordinates will be used for.

2022-12-17 15:18 UTC, wm75 commented
While you're at it: could you polish the output handling of ivar variant a bit.
The current way of copying the .tsv file to its final location and of leeting the python script write the VCF to the final destination results in rather long command lines.
A modern, better way would be to use `from_work_dir` in the output section and pick up variants.tsv and variants.vcf files by their names.

2022-12-17 16:26 UTC, tuncK commented on tools/ivar/macros.xml
> +  <token name="@PROFILE@">22.05</token>
Can you name a suitable profile? 20.01? 

I am aware that newer profile causes additional problems, so I tested from 19.?? up to 22.05. I thought it was backwards-compatible, as other people had asked me to bump it in the past.

2022-12-19 15:38 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +                -g $gtf
This needs quoting.

2022-12-19 15:43 UTC, wm75 commented on tools/ivar/macros.xml
> +  <token name="@PROFILE@">22.05</token>
`ivar_trim`, in the previous version, declared 21.01 as the profile version so seems reasonable to just require that everywhere.

New profile versions usually bring improvements with them so we're trying to update the requirements from time to time, but they are a requirement on the Galaxy server side, and asking for 22.05 for a tool that doesn't benefit from it just seems rather aggressive.

2022-12-19 15:57 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +                <action name="column_names" type="metadata" default="REGION,POS,REF,ALT,REF_DP,REF_RV,REF_QUAL,ALT_DP,ALT_RV,ALT_QUAL,ALT_FREQ,TOTAL_DP,PVAL,PASS,GFF_FEATURE,REF_CODON,REF_AA,ALT_CODO
when the $gtf option is in use, there are additional "column_names", aren't they?

2022-12-19 15:59 UTC, wm75 commented on tools/ivar/ivar_variants.xml
> +            <output name="output_variants_tabular" file="zika/Z52_a_annotated.tsv" ftype="tabular" lines_diff="10"/>
why the lines_diff in this and the following test's output check?

2022-12-20 08:08 UTC, tuncK commented on tools/ivar/ivar_variants.xml
> +                -g $gtf
Done

2022-12-20 08:12 UTC, tuncK commented on tools/ivar/ivar_variants.xml
> +                <action name="column_names" type="metadata" default="REGION,POS,REF,ALT,REF_DP,REF_RV,REF_QUAL,ALT_DP,ALT_RV,ALT_QUAL,ALT_FREQ,TOTAL_DP,PVAL,PASS,GFF_FEATURE,REF_CODON,REF_AA,ALT_CODO
No. They are already included in the current version: GFF_FEATURE,REF_CODON,REF_AA,ALT_CODON,ALT_AA

If you dont provide a gtf, these are filled with "NA". We could perhaps remove these 5 columns from non-gtf to save storage, but then some user-specific codes that rely on the number of columns might break.

2022-12-20 09:08 UTC, tuncK commented on tools/ivar/ivar_variants.xml
> +            <output name="output_variants_tabular" file="zika/Z52_a_annotated.tsv" ftype="tabular" lines_diff="10"/>
I copied it from the existing code and dont know why exactly it was needed :) I eliminated.

2022-12-20 10:29 UTC, tuncK commented
All tests work here, but 1 test times out on Github for some reason, maybe a rerun is all it needs? ("Timed out after 900.25 seconds waiting on tool test run.")

2022-12-20 19:26 UTC, bgruening commented
restarted the tests :)

2022-12-21 05:37 UTC, tuncK commented
Restarting the test indeed did the trick, thanks Björn.

@wm75, all good now?

2023-01-11 09:20 UTC, wm75 approved these changes

2023-01-11 09:28 UTC, merged

2023-01-11 09:29 UTC, wm75 commented
Thanks @tuncK for a good number of small improvements that make this tool suite better :heart: