Add new tool: frameshift_deletions_checks from smallgenomeutilities
galaxyproject/tools-iuc pull request #5015
Opened 2022-12-19 11:20 UTC by moeezmalik

### About the tool

This pull request adds the tool frameshift_deletions_checks from the repository smallgenomeutilities. The smallgenomeutilities are a collection of scripts that is useful for dealing and manipulating NGS data of small viral genomes.

The tool frameshift_deletions_checks detects frameshifts indels and stop codons in the provided viral consensus sequences and generate a report of the event.

#### Diclaimer
The above mentioned descriptions about the repository and the tool are taken directly from the authors of the tool.

### Tests
There are 4 tests in total for the tool. The tests focus on optional parameters that can be provided when running the tool. 

### Resources

- [smallgenomeutilites Github Repo](https://github.com/cbg-ethz/smallgenomeutilities)
- [smallgenomeutilites Bioconda Package](https://bioconda.github.io/recipes/smallgenomeutilities/README.html)

### For Contributor
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2022-12-19 15:16 UTC, wm75 requested changes
Thanks for starting this! Doesn't look too bad, but a couple of requests/ things to look at:
1. Why does git think the tsv files are binary? Same for the ._reference_file.fasta?
     Is this because of the leading `.`? Just use simple file names.
2. The `input_bam_file.bam` is way to large, in general for this repo, but definitely for such a simple tool.
     Please downsample the file. Maybe it's enough to provide the tool with reads around framshift positions?
3. Why is `consensus_file.fasta` so large? Shouldn't it be similar in size to `reference_file.fasta`?

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +<tool id="frameshift_deletions_checks" name="Frameshift Deletions Checks" version="0.3.9">
Can you define a @TOOL_VERSION@ token and use it as version please?
This will enable an autupdate bot to suggest version updates when a new version becomes available from bioconda.

Just look at any other recent wrapper to see how that's done (can be defined in this file here).

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +<tool id="frameshift_deletions_checks" name="Frameshift Deletions Checks" version="0.3.9">
Please also add a description here (look at other tools on usegalaxy.eu/.org for inspiration).

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +
remove empty lines

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +            Use 0-based (python) instead of 1-based (standard) seq positions
All these param descriptions should become param help strings in the <inputs> section.

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <![CDATA[
We usually do not indent the help section (again look at other wrappers).

2022-12-19 15:16 UTC, wm75 commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="orf1ab" type="text" value="cds-YP_009724389.1" label="ORF1AB" />
This is an optional param at the commandline, isn't it? If so, then it should also be optional here.

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="gff" type="data" format="gff" label="GFF" />
Is it `gff3`?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/test-data/gff_file.gff
> +##gff-version 3
The hidden files in the test-data folder should be removed.

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="english" argument="-e" type="boolean" truevalue="-e" falsevalue="-E" checked="true" label="Write English Summary Diagnosis?" />
Maybe just `write summary diagnosis`?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="zero_based" argument="-0" type="boolean" truevalue="-0" falsevalue="" checked="false" label="Use 0-based Sequence Positions?" />
Any idea how this could be useful?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +<tool id="frameshift_deletions_checks" name="Frameshift Deletions Checks" version="0.3.9">
Would prefer to have the tool in a directory `smallgenomeutilities`. And the `.shed.yml` (which is missing at the moment) define a suite. Then we are safe if someone adds more of these tools

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +            **Columns Signification:**
Column specification?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <requirement type="package" version="0.3.9">smallgenomeutilities</requirement>
According to the docs: In addition to the modules, frameshift_deletions_checks currently requires [mafft](https://mafft.cbrc.jp/alignment/software/) being installed -- it is also [available on bioconda](https://bioconda.github.io/recipes/mafft/README.html).

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="input" type="data" format="bam" label="Input BAM" />
Is sorted BAM needed? The Galaxy `bam` datatype implies that?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="reference" type="data" format="fasta" label="Reference" />
Probably not so relevant for small genomes, but: is `fasta.gz` input supported?

2022-12-19 18:35 UTC, bernt-matthias commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="orf1ab" type="text" value="cds-YP_009724389.1" label="ORF1AB" />
A validator or sanitizer might be a good idea.

2022-12-20 11:50 UTC, moeezmalik commented on tools/frameshift_deletions_checks/test-data/gff_file.gff
> +##gff-version 3
Hidden files have now been removed.

2022-12-20 11:52 UTC, moeezmalik commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="gff" type="data" format="gff" label="GFF" />
I have looked into the tool help and it does not specify the GFF version.

2022-12-20 11:53 UTC, moeezmalik commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="reference" type="data" format="fasta" label="Reference" />
The tool's help section indicates only FASTA being supported.

2022-12-20 16:48 UTC, moeezmalik commented on tools/frameshift_deletions_checks/frameshift.xml
> +<tool id="frameshift_deletions_checks" name="Frameshift Deletions Checks" version="0.3.9">
Token version has been added along with description for the tool.

2022-12-20 16:48 UTC, moeezmalik commented on tools/frameshift_deletions_checks/frameshift.xml
> +
Empty lines removed.

2022-12-22 09:15 UTC, moeezmalik commented on tools/frameshift_deletions_checks/frameshift.xml
> +        <param name="orf1ab" type="text" value="cds-YP_009724389.1" label="ORF1AB" />
The command line specifies this argument as required but infact if you don't specify it takes a default value which I put in here. This layout made the most sense to me. Could you expand a little on what alternative layout are you looking for? 

Check the image below taken from the command-line help section for the tool.
![image](https://user-images.githubusercontent.com/44679231/209099830-ef8e11d4-ced8-499d-9b56-58b66954906c.png)

2022-12-22 23:09 UTC, wm75 commented
We still need a much smaller BAM test file. You can use `samtools view` (command line or Galaxy tool) to subsample the current file or restrict it to a region of interest - just see what minimal content still gives a successful tool run that can be tested for.

2023-05-30 16:19 UTC, DrYak commented
I've combined this PR into my own work to add smallgenomeutilities' frameshift_deletions_checks into Galaxy: #5335

2023-07-04 11:21 UTC, wm75 commented
Superseded by #5335.

2023-07-04 11:21 UTC, closed without merging