Update get_organelle_from_reads.xml to handle paired collections correctly
galaxyproject/tools-iuc pull request #5301
Opened 2023-05-11 20:14 UTC by o-william-white

Hello, 

Today I found that get_organelle_from_reads.xml was not able to work with "paired_collections" as input. 

I was able to find a couple of potential issues: 
- spelling of "in1_name1" 
- the paired_collection paramter name "fastq_input1" did not match the name used in the command block "paired_input".  

I thought this might fix my issue but I still get the error below: 

```
NameMapper.NotFound: cannot find 'paired_input' while searching for 'fastq_input.paired_input.forward.ext'
```

@bernt-matthias can you see where i might have gone wrong here? 

Fix errors with paired collection parameters

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2023-05-11 20:42 UTC, bernt-matthias commented
Also con't spot a problem. Could you add a test for this case (e.g. just take the existing input and change select of the conditional and the fastq input to a paired collection).

2023-05-12 10:11 UTC, o-william-white commented
Hi @bernt-matthias thanks for the suggestion, I added the test using a paired collection but it passed when I ran it locally.

2023-05-12 10:56 UTC, o-william-white commented
[tool_test_output.html.txt](https://github.com/galaxyproject/tools-iuc/files/11462937/tool_test_output.html.txt)

2023-05-12 10:59 UTC, o-william-white commented
Html of test attached, I had to change the file ending to .txt so it could be uploaded. 

Can you see an issue with my test? It seems to pass, but when I run the same data using the Galaxy GUI, I get the same error as before.

2023-05-12 11:13 UTC, bgruening commented on tools/getorganelle/get_organelle_from_reads.xml
> +            <param name="paired_input">
this needs to be inside a conditional

2023-05-12 11:15 UTC, bgruening commented on tools/getorganelle/get_organelle_from_reads.xml
> +            -1 '${$in1_name}' -2 '${$in2_name}'
Mh, those selectors are wrong I think ... its either `${foo}` or `$foo`. I'm not aware that `${$foo}` will work?

2023-05-12 11:18 UTC, o-william-white commented on tools/getorganelle/get_organelle_from_reads.xml
> +            -1 '${$in1_name}' -2 '${$in2_name}'
Ah that's a silly mistake! Thanks for spotting!

2023-05-12 11:28 UTC, o-william-white commented on tools/getorganelle/get_organelle_from_reads.xml
> +            <param name="paired_input">
Would you be able to point me to an example of this? I used fastp https://github.com/o-william-white/tools-iuc/blob/master/tools/fastp/fastp.xml as an example to set this up.

2023-05-12 11:29 UTC, bernt-matthias commented on tools/getorganelle/get_organelle_from_reads.xml
> +            -1 '${$in1_name}' -2 '${$in2_name}'
Odd that this worked at all. But, this is in all branches of the if statement...

2023-05-15 06:49 UTC, bernt-matthias commented
@o-william-white can you check if the version of my latest commit works as you would expect?

2023-05-15 11:47 UTC, o-william-white commented
Hi @bernt-matthias many thanks for the changes, much appreciated. 

I made some additional changes to the tests and both pass now when I use planemo. 

Think this looks a lot better!

2023-05-15 12:00 UTC, bernt-matthias commented on tools/getorganelle/get_organelle_from_reads.xml
> +        <test expect_num_outputs="3">
Can you adapt the test to check for the content of the 3rd output .. or such that test has 2 outputs again?

2023-05-15 16:36 UTC, o-william-white commented on tools/getorganelle/get_organelle_from_reads.xml
> +        <test expect_num_outputs="3">
Test adapted, does this look ok?

2023-05-15 16:47 UTC, bernt-matthias approved these changes

2023-05-16 05:45 UTC, bernt-matthias requested changes
Please bump the tool version

2023-05-16 08:22 UTC, o-william-white commented
Hi @bernt-matthias, I checked the getorganelle version and it is using the most up to date version. Do you mean galaxy tool version? Where would I change this?

2023-05-16 09:12 UTC, bernt-matthias approved these changes

2023-05-16 09:13 UTC, bernt-matthias commented
Like so https://github.com/galaxyproject/tools-iuc/pull/5301/commits/ce2b9a1b77f81217e47ba4ffd296a7bf506d1902 would be the IUC way to bump the galaxy tool version.

2023-05-16 09:15 UTC, o-william-white commented
Awesome, thanks for explaining!

2023-05-16 09:21 UTC, merged