Picard update v.3.0.0
galaxyproject/tools-iuc pull request #5348
Opened 2023-06-06 18:48 UTC by gallardoalba

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2023-09-01 15:35 UTC, gallardoalba commented
Everything seems to be fine, except the wrapper piccardCollectRnaSeqMetrics.xml, which shows the following error:

`Job in error state.. tool_id: picard_CollectRnaSeqMetrics, exit_code: 127, stderr: /tmp/tmp4rglmtho/job_working_directory/000/8/tool_script.sh: line 9: picard: command not found
`
Could you have a look? @bgruening @bernt-matthias? I reviewed it, but I'm not able to find the problem. Thanks   a lot!

2023-09-02 01:04 UTC, bgruening commented on tools/picard/picard_AddOrReplaceReadGroups.xml
> +      <output name="outFile" file="picard_ARRG_test1.bam" ftype="bam" compare="sim_size" delta="600"/>
do not use sim_size on BAMs

2023-09-07 06:23 UTC, bgruening commented on tools/picard/test-data/picard_CASM_test1.tab
> +## HISTOGRAM	java.lang.Integer
That file does not look like a .tab anymore. Or it looks like 2 files in one. Is that expected?

2023-09-07 06:23 UTC, bgruening commented on tools/picard/test-data/picard_CollectWgsMetrics_test1.tab
> +16568	2.915862	3.835741	2	2	0	0	0	0	0.000041	0.008069	0	0.00811	0.684633	0.240464	0.055831	0.02541	0.010985	0	0	0	0	0	0	0	0	0	?	?	?	0.544024	3
Are those ? expected?

2023-09-07 06:23 UTC, bgruening commented on tools/picard/test-data/pos_details
> +picard_ARRG.bam	picard_ARRG.bam	A	C	AAA	58	0	857	0	0	0	0	100
sample-a tumar-a looked better in the last version as two times the file-name, do we know why this is happening?

2023-09-07 06:23 UTC, bgruening commented on tools/picard/test-data/pos_summary
> +picard_ARRG.bam	picard_ARRG.bam	A	C	35	TAA	26	CAN	34	NAA	28	NA
same here

2023-09-07 06:23 UTC, bgruening commented on tools/picard/picard_macros.xml
> +    <token name="@TOOL_VERSION@">3.0.0</token>
```suggestion
    <token name="@TOOL_VERSION@">3.1.0</token>
```

Does that version also work?

2023-09-07 10:19 UTC, bgruening commented
Lets try the 3.1 version. If it fails, feel free to revert it.

2023-09-08 13:13 UTC, bernt-matthias commented
Picard uses `format="sam,bam"` at many places. This should probably be `sam,unsorted.bam`.

2023-09-09 13:09 UTC, mvdbeek commented
> This should probably be `sam,unsorted.bam`.

After checking that this doesn't change runtime and memory characteristics negatively (i think there's a good chance it would) this could be done in another PR.

2023-09-09 13:27 UTC, bernt-matthias requested changes

2023-09-09 13:27 UTC, bernt-matthias commented on macros/read_group_macros.xml
> +        <param name="do_auto_name" type="select" label="Auto-assign" help="Use dataset name or collection information to automatically assign this value">
Please revert this change. The macro does not affect picard, but will certainly affect tools using it (which seems to be bowtie2 only).

2023-09-26 14:21 UTC, bgruening approved these changes
Awesome work @gallardoalba

2023-09-26 14:25 UTC, gallardoalba commented
> Awesome work @gallardoalba

Test didn't run again at all, not sure why

2023-09-26 14:53 UTC, gallardoalba commented
This is the problem:
`.. WARNING: Conditional [read_group_lb_conditional] first param of type="boolean" is discouraged, use a select
`

2023-09-26 14:55 UTC, bgruening commented
We can igrnore this lint error.

But this is also failing now:

```
Output outFile:  different than expected, difference (using diff):
( /tmp/local_bam_converted_to_sam_m_mvyp3v.sam v. /tmp/history_bam_converted_to_sam_61d2szdz.sam )
--- local_file
+++ history_data
@@ -1,345 +1,345 @@
 @HD	VN:1.6	SO:coordinate
 @SQ	SN:gi|251831106|ref|NC_012920.1|	LN:16569
-@RG	ID:picard_ARRG.bam	LB:picard_ARRG.bam	PL:ILLUMINA	SM:picard_ARRG.bam	PU:run-1
+@RG	ID:id-1	LB:tumor-a	PL:ILLUMINA	SM:sample-a	PU:run-1
 @PG	ID:bwa	PN:bwa	VN:0.7.10-r837-dirty	CL:bwa mem -t 1 -v 1 localref.fa /Users/anton/galaxy-central/database/files/000/dataset_526.dat /Users/anton/galaxy-central/database/files/000/dataset_527.dat
-M01368:8:000000000-A3GHV:1:1101:6911:8255	73	gi|251831106|ref|NC_012920.1|	1	60	71S180M	=	1	0	ATCTGGTTCCTACTTCAGGGCCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATT	BCCCCFFFFFFFGGGGGGGGGGGHHHHGHGHHHHHHHHHGGGGGGHHHHGHHHHHHHHHHGHHHHHHGGHGGHHHGHHHHFHHGHHHHHHHHHGHEHEFFGHHEGGCEFGGFHHHBGHHGHHHHGHFHHHGHGHGHGGCDFDDACGGGGGGGAAFFFFFFFFFBAFFFFFB;FFFFFFADDFFFFFFFFFFEFFFFFFFFFFBFFFFFFFFFFFFFFEFFFFFFFFBFEFFFFEFE;DFFFDFBFF/9BFB	SA:Z:gi|251831106|ref|NC_012920.1|,16499,+,71M180S,60,2;	MD:Z:72A107	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:175	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:6911:8255	133	gi|251831106|ref|NC_012920.1|	1	0	*	=	1	0	TCGCCTTACCGCTACTCACCCACGGCGGCCATCAGCCGATACTAAGTTTGGGGTATGGTGGGGGGGATAATGAATTAGGTTGTGGGGGAGGGTTTGTGGTTGAGAGAAACACAAAAAACAATCTTATATATGGGTAGTCGTTTTGTATTGGTTTTTTGTTTTGTTTGTGTTTTGAGTGTCGGTTTAGTTCGGTGTACTAGGGGGGGTGGATGGGGTCGGCTGGTGAGGGGGTCTTAGTGTATTGAGTGTGG	1>11111@11111A111A100000000////011110//>>/12@1@22B/////1@>21/>>/-----9/;////9////--;-;-;-----;--------9/-/-///9-;-------9//////9/////-//-/9-;-;9--/////99-;--9-:-;----/---/-----////---9-/////--;A-//////---------9/-----;-----/-/-----;--;//////////9;///-	RG:Z:picard_ARRG.bam	AS:i:0	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:14518:9998	163	gi|251831106|ref|NC_012920.1|	1	60	10S241M	=	1	242	CATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATAA	CCCCCFCCCCCFGGGGGGGGGGHHHHHHHHHHHHHHHHGFHHHHGGGGGHGFHHHHHHHHHHHHHHHHHHHGHGGEHGGGGCGGGHHGGCGGGGGHHGHHHGGGGGGGG.BFFFGAGADFGAFDGFGGCFFF;DDFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFF09FFFE00;BE@;DABBFFFFFBBFB00;F:9;FFBFFF9BFFFFFFFFFFFFF90/::BFFFBF0	MD:Z:72A168	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:236	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:18422:19051	99	gi|251831106|ref|NC_012920.1|	1	60	80S171M	=	1	228	GTATCCGACATCTGGTTCCTACTTCAGGGTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACG	CCCCCFDDDDDFGGGGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHFHHHHGGGGHHHHHHHHHGHHHHHHHHHHHHGGHGGHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHGCGGGHHHHHHHHHHHHHHHHHHHHHHGFDHGFHCFGGGGFGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;FFFFFFFFFFFFFFFFFFFFFFFFFFFFEFBFFFFFFFFFF:FFF.	SA:Z:gi|251831106|ref|NC_012920.1|,16490,+,80M171S,60,1;	MD:Z:72A98	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:166	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:25545:21098	163	gi|251831106|ref|NC_012920.1|	1	60	113S138M	=	1	216	GCCCATAACACTTGGGGGTAGCTAAAGTGAACTGTATCCGACATCTGGTTCCTACTTCAGGGTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTTCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCAACCTATGTCGCAGTATCTGTCTTTGAT	3AAA34BFFFFFGCGGCGGGCGHHHGHHHHCGHFGHFHGFGGCDGGBD5FGFFFHFHGGGHAEBFGHHHEHGGFHBGGFHHHGGGEEFHHHFHFFHDHGHGHHHHFFHHGGFAEGFFFFFBGHHHFFHHHHHHHFHFHHFHGFHGHGA/<@EFHEHH1GGHFFFHG1>=FGHFHGF.GE//-<BB?9.9BFFFB==AA/FFFFFA-@BA.;;D?F9FAB;---./99BFFFBBAE-.9B/BFB9F/9BFBB	SA:Z:gi|251831106|ref|NC_012920.1|,16457,+,113M138S,60,1;	MD:Z:72A1G36C26	RG:Z:picard_ARRG.bam	NM:i:3	AS:i:123	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:5446:12248	163	gi|251831106|ref|NC_012920.1|	1	60	78S173M	=	1	213	ATCCGACATCTGGTTCCTACTTCAGGGTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTT	CCDDDCCCCFFFGGGGGGGGGGHHHHHGHHHHHHHHGHHHHHHGHHHHGGGGHHHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHGFGHHHHHHHHHHHHHHHHHGHHHHHGGGGGHHHHHHHHHHHHHHHGHHHHHHGHGHGHHGGGGGGGGGGGFFFFFFFFFFFFFFAFFFFFFFFFFFFFBFC?.EAFFFFFFFFAFFFFFFFFFFFFFFFEFFFF0FFFFFFF0BFFFFFFFFF?.BDCFFEDA/	SA:Z:gi|251831106|ref|NC_012920.1|,16492,+,78M173S,60,1;	MD:Z:72A100	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:168	XS:i:0
-M01368:8:000000000-A3GHV:1:1101:5861:6452	163	gi|251831106|ref|NC_012920.1|	1	60	80S171M	=	1	236	TTATCCGACATCTGGTTCCTACTTCAGGGTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACG	BCCCCFBBCCCFGGGGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHHHHHHGGGGHHHHHHHHGHHHHHHHHHHHHHGGHGGHHHHHHHGHHHHHHHHHHHHHHHHHHHGGHHHHGGGGGGEHGHHHHHHHHHHHGHHHHHHGHGHGHGGGGCGGGGGFFFFFFFFFFFFFFFFFFFFFFFF?FFEAF:DAEF9DEFFFFFFF-A.BFFFFFEFFFFEFFFFFFFF0FFEB0FFFFBFFFFFFADEFCF0/.	SA:Z:gi|251831106|ref|NC_012920.1|,16490,+,80M171S,60,2;	MD:Z:72A98	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:166	XS:i:0
-M01368:8:000000000-A3GHV:1:1102:10403:6021	99	gi|251831106|ref|NC_012920.1|	1	60	121S130M	=	1	151	CGCTCCGGGCCCATAACACTTGGGGGTAGCTAAAGTGAACTGTATCCGACATCTGGTTCCTACTTCAGGGTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTG	>A@AAAAD2ADDFFGGGGGFGGHA?EAEFBEAGHFABFGG5FDF5DB1EEGAFDFB53FF5FH@G5FFEHGHEFHFFHBE333GF43GCGGGGE@0?BFGGB0B?FHGFDGGHHHBFFDEGGHGFFFDFE@<1>@FFFGHHHHFHEFGDABFFGG/@DCE<CG1<GF0/DD000=<DHGBDFDCECE/:AC?-;-;9B/ABBB-AD9BFB99AB?BDFBAD-.9..@;=;;..9..9/9;BEF;A:9/BFF	SA:Z:gi|251831106|ref|NC_012920.1|,16449,+,121M130S,60,1;	MD:Z:72A57	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:125	XS:i:0
-M01368:8:000000000-A3GHV:1:1102:10677:23253	99	gi|251831106|ref|NC_012920.1|	1	60	22S213M16S	=	1	213	CCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTCTGTCTCTTATACACA	ABBBBFFFFFFFGGGGGGGCGGGHHHHHGHHHHHHHHHGHHHHHHHHHHHGHHHHHGGGGGHGHHHHHHHHHHHHHBGFHHHHGHGHGGHGGGCGGGHHHGGGGGGGHHHGHGGGGGGGGGGGGGGGGGGGGFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFEDBDFFFFFFFEFFFE0F0FBFFFF0FFFFFFFFFFFFFFFFF:	MD:Z:72A140	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:208	XS:i:0
-M01368:8:000000000-A3GHV:1:1102:13809:1733	163	gi|251831106|ref|NC_012920.1|	1	60	50S179M22S	=	1	179	NATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATCTGTCTCTTATACACATCTGAC	#>AABBFFCFFFGGGFGGGGGGGGHHHHHHHHHHHHHHHHHHGHHHGGEGGFFHHHHHHGHGHGHHHHHEHFHGHHHHEFHHGHGGGGGHHHHGHHHHHHHHHGFGHHHHHGHGHGHHGGGCCGGGGFGGGGGGDGGGGFGDGGGFFFFFFEFFFFFFFBAF:9AF//;BEF-DD/FFFFBFFFFFFFFFEBFF?FB;/;//BFFEFFE/::..9;-:B9:FBFFFFFFBFB/9/FFF/B///99/:B///	SA:Z:gi|251831106|ref|NC_012920.1|,16520,+,50M201S,60,2;	MD:Z:72A106	RG:Z:picard_ARRG.bam	NM:i:1	AS:i:174	XS:i:0
-M01368:8:000000000-A3GHV:1:1102:17584:10050	163	gi|251831106|ref|NC_012920.1|	1	60	52S138M61S	=	1	138	GTCATAAAACCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATCTGTCTCTTATACACATCTGACGCTGCCGACGAGCGATCTAGTGG [...]

2023-09-26 16:40 UTC, bgruening commented
:( still failing

2024-02-19 09:58 UTC, closed without merging