add new tool suite dimet - first ommit
galaxyproject/tools-iuc pull request #5400
Opened 2023-07-19 13:44 UTC by bdartigues

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2023-07-19 14:00 UTC, bgruening reviewed
Hi @bdartigues,

please do not ship the underlying tool inside the Galaxy tool. 
Its better to create a conda package for your underlying tool, so this repo only contains the wrappers.

The entire config, data and src dir should be shipped as a conda depency.

2023-07-20 05:42 UTC, bernt-matthias requested changes
Thanks for the contribution. My biggest concern with this is that the tool should be distributed in a separate repo (and installable via bioconda).

2023-07-20 05:42 UTC, bernt-matthias commented on tools/dimet/.shed.yml
> +  description: "A suite of Galaxy tools designed to work with version 1.9 of the bcftools package."
Seems wrong

2023-07-23 12:58 UTC, bgruening reviewed
The config folder can also be removed isn't it?

2023-07-23 13:30 UTC, bgruening commented on tools/dimet/dimet_pca_analysis.xml
> +    mkdir -p '${report.extra_files_path}'/raw &&
You are creating those dirs and then removing them again. `extra_files_path` is potentially in an expensive storage as it is Galaxy file DB. I would prefer if you generate those tmp dirs and files  inside your JWD, so the current job_working directory and only copy it to extra_files_path when everything is done.

2023-07-23 14:02 UTC, bdartigues commented on tools/dimet/dimet_pca_analysis.xml
> +    mkdir -p '${report.extra_files_path}'/raw &&
config folder have to be there i think. Users fill each config file using xml parameter. Concerning your trick with biocontainer, i still cannot install dimet and have an error

2023-07-23 14:06 UTC, bdartigues commented on tools/dimet/dimet_pca_analysis.xml
> +    mkdir -p '${report.extra_files_path}'/raw &&
I'm not sure I understand what you mean. usually, we copy the results stored in report.extra_file_path to JWD. please tell me if I'm wrong, I have to create the raw and output folders in JWT? and then copy the whole thing to report.extra_file_path? isn't that the opposite of what we usually do?

2023-07-24 11:34 UTC, hechth reviewed
First round of comments - with these changes the tools actually run with planemo, I'm just not sure whether I actually have the correct input data.

2023-07-24 11:34 UTC, hechth commented on tools/dimet/macros.xml
> +            <citation type="doi">10.3389/fbinf.2022.867111</citation>
```suggestion
            <citation type="bibtex">
            @software{Galvis_Rodriguez_DIMet,
                author = {Galvis Rodriguez, Johanna  and Guyon, Joris and Dartigues, Benjamin and Specque, Florian and Daubon, Thomas and Karkar, Slim and Nikolski, Macha},
                license = {MIT},
                title = {{DIMet}},
                url = {https://github.com/cbib/DIMet}
            }
            </citation>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="7"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="9"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_multigroup_analysis.xml
> +            <output name="report" file="report.html" count="3"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_enrichment_plot.xml
> +            <output name="report" file="report.html" count="8"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_isotopologues_plot.xml
> +            <output name="report" file="report.html" count="9"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_metabologram.xml
> +            <output name="report" file="report.html" count="5"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_pca_analysis.xml
> +            <output name="report" file="report.html" count="26"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_abundance_plot.xml
> +                _target_:data.DatasetConfig,
```suggestion
                _target_:dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_abundance_plot.xml
> +                _target_: method.AbundancePlotConfig,
```suggestion
                _target_: dimet.method.AbundancePlotConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_analysis.xml
> +                _target_: data.DatasetConfig,
```suggestion
                _target_: dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_analysis.xml
> +                _target_: method.DifferentialAnalysisConfig,
```suggestion
                _target_: dimet.method.DifferentialAnalysisConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_multigroup_analysis.xml
> +                _target_:data.DatasetConfig,
```suggestion
                _target_:dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_differential_multigroup_analysis.xml
> +                _target_: method.MultiGroupComparisonConfig,
```suggestion
                _target_: dimet.method.MultiGroupComparisonConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_enrichment_plot.xml
> +                _target_:data.DatasetConfig,
```suggestion
                _target_:dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_enrichment_plot.xml
> +                _target_: method.MeanEnrichmentLinePlotConfig,
```suggestion
                _target_: dimet.method.MeanEnrichmentLinePlotConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_isotopologues_plot.xml
> +                _target_:data.DatasetConfig,
```suggestion
                _target_:dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_metabologram.xml
> +			_target_: data.DataIntegrationConfig,
```suggestion
			_target_: dimet.data.DataIntegrationConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_pca_analysis.xml
> +                _target_: method.PcaAnalysisConfig,
```suggestion
                _target_: dimet.method.PcaAnalysisConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_pca_plot.xml
> +                _target_:data.DatasetConfig,
```suggestion
                _target_:dimet.data.DatasetConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_pca_plot.xml
> +            <output name="report" file="report.html" count="38"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_timecourse_analysis.xml
> +                _target_: method.TimeCourseAnalysisConfig,
```suggestion
                _target_: dimet.method.TimeCourseAnalysisConfig,
```

2023-07-24 11:34 UTC, hechth commented on tools/dimet/dimet_timecourse_analysis.xml
> +            <output name="report" file="report.html" count="14"/>
```suggestion
            <output name="report" file="report.html"/>
```

2023-07-24 13:00 UTC, hechth commented on tools/dimet/.shed.yml
> +  description: "A suite of Galaxy tools designed to work with version 1.9 of the bcftools package."
Can you be a bit more specific on what is wrong here?

2023-07-24 13:01 UTC, bernt-matthias commented on tools/dimet/.shed.yml
> +  description: "A suite of Galaxy tools designed to work with version 1.9 of the bcftools package."
The description is for `bcftools` .. probably a copy paste error.

2023-07-24 15:07 UTC, bdartigues commented on tools/dimet/dimet_timecourse_analysis.xml
> +            <output name="report" file="report.html" count="14"/>
@bernt-matthias many thanks for all your comments and corrections

2023-07-24 16:38 UTC, bdartigues commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="9"/>
I got this error if i remove the count atttribute
ERROR: Test 2: test output 'report' must have a 'count' attribute and/or 'discovered_dataset' children

2023-07-24 16:38 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
I got this error if i remove the count atttribute
ERROR: Test 2: test output 'report' must have a 'count' attribute and/or 'discovered_dataset' children

2023-07-24 22:51 UTC, hechth commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="7"/>
This is weird, I don't get this error. Which version of planemo and Galaxy are you using?

2023-07-24 22:56 UTC, hechth commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
@bdartigues Are these tools supposed to create a single report.html otuput or a collection? You are mixing two things up here - `discover_datasets` is to create a collection AFAIK, which is why the test complains - but then you are expecting a single file in the test, which can't have the `count` attribute.

2023-07-24 22:57 UTC, hechth commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
Also, you can use github to apply suggested commits, which makes tracking changes while reviewing a lot easier.

2023-07-25 01:09 UTC, hechth commented
@bdartigues it seems that some of the tools doing plot and analysis could actually be combined into a single tool which just outputs both - this would make the tools significantly simpler I think.

2023-07-25 01:52 UTC, hechth commented
@bdartigues you could also use parameterized macros to re-use code which does the hydra configuration since the config files are all available.

2023-07-25 06:27 UTC, bernt-matthias requested changes
Few more comments from my side.

2023-07-25 06:32 UTC, bernt-matthias commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
> @bdartigues Are these tools supposed to create a single report.html otuput or a collection? You are mixing two things up here - `discover_datasets` is to create a collection AFAIK, which is why the test complains - but then you are expecting a single file in the test, which can't have the `count` attribute.

You can also use `discover_datasets` to discover separate datasets. See https://docs.galaxyproject.org/en/latest/dev/schema.html#id352 and linked planemo docs.

But often a collection is more appropriate.

2023-07-25 06:35 UTC, hechth commented on tools/dimet/dimet_pca_plot.xml
> +        cp '$isotop_prop_file' '${report.extra_files_path}'/raw/isotop_prop.csv &&
@bdartigues and @bernt-matthias this is already fixed in the PR I opened to this branch

2023-07-26 09:19 UTC, bdartigues commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="7"/>
I mean I got this error on tools-iuc when checking the xml files (lint) after committing these changes. On my mac, I have version 0.75.7 and the galaxy version I think is 20.05. I also have this error now for the lint of dimet_pca_analysis.xml
.. ERROR: Test 1: test output report does not correspond to a 'data' output, but a 'collection'
.. ERROR: Test 1: test output 'report' must have a 'count' attribute and/or 'discovered_dataset' children

2023-07-26 09:24 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
I was wondering what the best compromise was, as some tools produce quite a lot of output and I had thought that a single results folder might be better to lighten the history in galaxy. But you're right, I must have mixed up two concepts. So, what do you think is the best way to proceed?

2023-07-27 19:45 UTC, bdartigues commented on tools/dimet/dimet_abundance_plot.xml
> +            <output name="report" file="report.html" count="7"/>
Finally it works for me! i updated planemo and i succeeded to make it work directly with conda

2023-07-27 19:47 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <output name="report" file="report.html" count="6"/>
Collections are perfect container for dimet outputs. Thanks for highlight it for me !!

2023-07-28 15:33 UTC, bdartigues commented on tools/dimet/dimet_pca_analysis.xml
> +    mkdir -p '${report.extra_files_path}'/raw &&
Done. followed recommendations from @hechth

2023-07-28 15:35 UTC, bdartigues commented on tools/dimet/test-data/report.html
Done

2023-07-28 15:36 UTC, bdartigues commented on tools/dimet/dimet_pca_plot.xml
> +        #silent $impute_values['mean_enrichment']=re.sub('"', '', "min")
Done replaced         
#silent $impute_values['mean_enrichment']=re.sub('"', '', "min") 
by    
#silent $impute_values['mean_enrichment']='min'

2023-07-30 23:51 UTC, hechth reviewed
Thanks for the updates! Maybe the tests can be simplified even more, to check only for the number of outputs? With the current setup, there is a large number of test files and I'm not sure if that is really necessary. If the tool creates the expected number of files, and the files are there, I think that is fine. You can also check the tables for number of rows etc., so the tests can be a bit more refined without needing to upload the actual test outputs.

2023-07-30 23:51 UTC, hechth commented on tools/dimet/dimet_timecourse_analysis.xml
> +        -cp '$__tool_directory__/config'
why the switch in command line argument identifier?

2023-07-30 23:51 UTC, hechth commented on tools/dimet/dimet_timecourse_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tsv"/>
If the files are actually tsv formatted they should also have this as a file extension and not `csv`.

2023-07-30 23:51 UTC, hechth commented on tools/dimet/macros.xml
I think the blank lines make the file more readable.

2023-07-31 07:04 UTC, bernt-matthias commented
> If the tool creates the expected number of files, and the files are there, I think that is fine.

I would not assume that!

But I agree that well-designed content assertions are often better (more robust) than plain diff wo files. But they often need a lot of time to develop. But at least double-check that all files are used by tests.

2023-10-08 10:39 UTC, bdartigues commented
> Few more comments from my side.

I don't know how to made changes for this old request ?

2023-10-09 08:19 UTC, hechth reviewed
This is great progress! Just some questions - are really all files in test-data used in the tests? Is it really all 200 files?

Otherwise, tool descriptions and maybe some parameters should be updated to include more information. Outcommented code could be removed to make the files easier to understand.

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +    <token name="@TOOL_VERSION@">1.0.0</token>
The tool version should match with the version of the package, so should be 0.1.4 in this case and should use the same macro

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +    </xml>
Maybe some of the sections in the help text at the bottom could be moved here to explain specific parameters in a bit more detail?

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +                </param>
Is this exactly the same statistical test as the previous one? If so, it could be re-used into a macro, but this is just a"nice to have" I think

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +            </param>
It seems like the options depending on which choice is made are still very similar - you think it would be possible to make this a bit more concise, maybe by having the same parameters but having a description that describes the difference in the select?

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +            <validator type="length" min="1" message="Please enter at max 2 compartments"/>
If there is a min field, is there also a max field since the maximum seems to be 2?

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +<!--    ]]></token>-->
outcommented things could be removed in general

2023-10-09 08:19 UTC, hechth commented on tools/dimet/macros.xml
> +<!--    </xml>-->
remove

2023-10-09 08:24 UTC, bdartigues commented on tools/dimet/macros.xml
> +<!--    </xml>-->
Oh yes, sorry i forgotten to clean the commented lines;-(

2023-10-09 08:26 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
No the help is different for each tool

2023-10-09 08:28 UTC, bdartigues commented on tools/dimet/dimet_enrichment_plot.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
We updated each description but it is the same for each tools. OK we will add a specific description for each tool

2023-10-09 08:28 UTC, bdartigues commented on tools/dimet/dimet_differential_multigroup_analysis.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
same as previous

2023-10-09 08:34 UTC, bdartigues commented on tools/dimet/macros.xml
> +<!--    ]]></token>-->
Done

2023-10-09 08:35 UTC, bdartigues commented on tools/dimet/macros.xml
> +            <validator type="length" min="1" message="Please enter at max 2 compartments"/>
No it is an error, it is only 1 min

2023-10-09 08:38 UTC, bdartigues commented on tools/dimet/macros.xml
> +            </param>
i think we need to keep this because i made differents things depending on the value. mainly when i parse for metabolites in the files, there are not at the format in abundance or in isotopologue files. but maybe i do not understand your remark ?

2023-10-09 08:39 UTC, bdartigues commented on tools/dimet/macros.xml
> +                </param>
Ok i will add a macro stat_test

2023-10-09 08:48 UTC, bdartigues commented on tools/dimet/macros.xml
> +    <token name="@TOOL_VERSION@">1.0.0</token>
done

2023-10-09 08:48 UTC, bdartigues commented on tools/dimet/macros.xml
> +            <validator type="length" min="1" message="Please enter at max 2 compartments"/>
Done

2023-10-09 08:48 UTC, bdartigues commented on tools/dimet/macros.xml
> +<!--    </xml>-->
Done

2023-10-09 08:58 UTC, bdartigues commented on tools/dimet/macros.xml
> +    </xml>
I think the description is too complex to include in the help for each parameter. Perhaps a sentence to direct the user to the help below?

2023-10-09 09:06 UTC, bdartigues commented on tools/dimet/dimet_timecourse_analysis.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:06 UTC, bdartigues commented on tools/dimet/dimet_pca_plot.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:06 UTC, bdartigues commented on tools/dimet/dimet_pca_analysis.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:06 UTC, bdartigues commented on tools/dimet/dimet_metabologram.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:07 UTC, bdartigues commented on tools/dimet/dimet_isotopologues_plot.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:07 UTC, bdartigues commented on tools/dimet/dimet_abundance_plot.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:07 UTC, bdartigues commented on tools/dimet/dimet_differential_multigroup_analysis.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:07 UTC, bdartigues commented on tools/dimet/dimet_enrichment_plot.xml
> +        DIMet: Differential analysis of Isotope-labeled targeted Metabolomics data
Done

2023-10-09 09:45 UTC, bdartigues commented on tools/dimet/macros.xml
> +    </xml>
I've added a short description in the help section of each input file. I've left the same thing in the help to help the user in case he starts by reading the help.

2023-10-10 06:18 UTC, bdartigues commented
Dear @bgruening , @hechth, @bernt-matthias,
I think i made all changes requested. I wait now for your validation in order to terminate the migration process.
Many thanks in advance,

2023-10-10 07:57 UTC, bgruening commented on tools/dimet/dimet_metabologram.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
I'm a bit confused. Here you say its an PDF, but the tests are all SVG.

Why does Galaxy not fail in the tests? Strange. Should it be SVG or PDF?

2023-10-10 07:59 UTC, bgruening commented on tools/dimet/dimet_pca_plot.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
Here as well. I guess you can remove the "format". But please check it with planemo serve if you get actually annotated SVG or PDF files.

2023-10-10 08:03 UTC, bgruening commented on tools/dimet/dimet_timecourse_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tsv"/>
here you use tsv in other tools csv ... isn't that confusing for the users?

Please use tabular instead of tsv

2023-10-10 08:04 UTC, bgruening commented on tools/dimet/macros.xml
> +            <requirement type="package" version="0.1.4">dimet</requirement>
You could use there the @TOOL_VERSION@

2023-10-10 08:20 UTC, bdartigues commented on tools/dimet/dimet_metabologram.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
You're absolutely right, I was asking myself the same question but as it worked, I didn't push it any further, I can modify the test to match the pdf if you'd like?

2023-10-10 08:21 UTC, bdartigues commented on tools/dimet/dimet_pca_plot.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
yes i get annotated svg, so it seems that it doesn't follow this instruction

2023-10-10 08:21 UTC, bdartigues commented on tools/dimet/dimet_timecourse_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tsv"/>
OK i will change it

2023-10-10 08:22 UTC, bdartigues commented on tools/dimet/macros.xml
> +            <requirement type="package" version="0.1.4">dimet</requirement>
Done

2023-10-10 08:28 UTC, bdartigues commented on tools/dimet/dimet_metabologram.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
it could be either .svg or .pdf. there is an option to select

2023-10-10 08:47 UTC, bgruening reviewed
If you like you can also use https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-creator-organization

Is this part of EOSC4Cancer?

2023-10-10 09:10 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
Ok i will test it

2023-10-10 09:13 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
No it is not EOSC 4 Cancer but i will see With Macha if we mention our lab

2023-10-10 09:42 UTC, bgruening commented on tools/dimet/dimet_metabologram.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="figures" format="pdf"/>
If its both use `__designation_and_ext__` but without format. That sould hopefully work.

2023-10-10 09:57 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
Dear @bgruening, if i used pattern="__designation__", now i got this error;-(

`Output collection 'report': failed to find identifier 'abundances--T0--cell--label-n_pc' in the tool generated elements ['abundances--T0--cell--label-n_pc.svg', 'abundances--T0--cell--label-y_pc.svg', 'abundances--T0--cell_var.svg', 'abundances--T0--med--label-n_pc.svg', 'abundances--T0--med--label-y_pc.svg', 'abundances--T0--med_var.svg', 'abundances--T2h--cell--label-n_pc.svg', 'abundances--T2h--cell--label-y_pc.svg', 'abundances--T2h--cell_var.svg', 'abundances--T2h--med--label-n_pc.svg', 'abundances--T2h--med--label-y_pc.svg', 'abundances--T2h--med_var.svg', 'abundances--cell--label-n_pc.svg', 'abundances--cell--label-y_pc.svg', 'abundances--cell_var.svg', 'abundances--med--label-n_pc.svg', 'abundances--med--label-y_pc.svg', 'abundances--med_var.svg']`

So as i seen in other tools i tried for abundance plot, for example, to let only : 
<output_collection name="report" type="list" count="2"/>
instead of 
<output_collection name="report" type="list" count="2">
       <element name="bars_endo_Fru1P-total_abundance" ftype="svg" compare="sim_size" delta="100"/>
</output_collection>
but i lost the capability to compare by sim-size isn't it ?

2023-10-10 10:03 UTC, bgruening commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
Why you see here is that your element ID changes. You would need to rename the element-ID in your test from `abundances--T2h--med_var` to `abundances--T2h--med_var.svg` ...

But as I commented above. For the SVG/PDF case you can leave it with `__destignation_and_ext__` just remove the ``format="pdf"`, because the format will be detemind from the file extension. SVG or PDF.

However, this trick does not work for `tabular` as your files are not ending with `.tabular` I assume. In this case, and because you only have tabular files in this dir (I assume), you can use here `__destignation__` and determine the format with `format="tabular"`.

I hope I got this all correct :)

2023-10-10 10:08 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
OK i will do this. get back to you in a few minutes

2023-10-10 10:17 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
if i changed with __destination__ and let tabular as format 

Dataset metadata verification for [file_ext] failed, expected [tsv] but found [tabular].

here is what i put for exmaple
```
<collection name="report" type="list">
            <discover_datasets pattern="__designation__" directory="tables" format="tabular"/>
        </collection>
```

```
<output_collection name="report" type="list" count="4">
                <element file="abundance--cell-Control-T2h-Control-T0-Tt.tsv"  name="abundance--cell-Control-T2h-Control-T0-Tt.tsv" ftype="tsv"/>
                <element file="abundance--cell-L-Cycloserine-T2h-L-Cycloserine-T0-Tt.tsv"  name="abundance--cell-L-Cycloserine-T2h-L-Cycloserine-T0-Tt.tsv" ftype="tsv"/>
                <element file="abundance--med-Control-T2h-Control-T0-Tt.tsv" name="abundance--med-Control-T2h-Control-T0-Tt.tsv" ftype="tsv"/>
                <element file="abundance--med-L-Cycloserine-T2h-L-Cycloserine-T0-Tt.tsv" name="abundance--med-L-Cycloserine-T2h-L-Cycloserine-T0-Tt.tsv" ftype="tsv"/>
            </output_collection>
```


for figures tools, it seems to work

2023-10-10 10:17 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
maybe put tabular ftype ?

2023-10-10 10:19 UTC, bdartigues commented on tools/dimet/dimet_differential_analysis.xml
> +            <discover_datasets pattern="__designation_and_ext__" directory="tables" format="tabular"/>
yes it works

2023-10-10 11:33 UTC, bgruening approved these changes
Cool, lets ship it.

2023-10-10 11:34 UTC, merged

2023-10-10 11:34 UTC, bgruening commented
Thanks @bdartigues!

2023-10-10 11:38 UTC, bdartigues commented
Dear @bgruening, @hechth , @bernt-matthias,
Thank you so much for all your help and comments, which have made this tool so complete and so clean. We couldn't have done it without you!
Kindest regards,
Benjamin