Add compleasm v.0.2.2
galaxyproject/tools-iuc pull request #5664
Opened 2023-12-04 17:16 UTC by rlibouba

Hi, I've started wrapping for compleams tool. 

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2023-12-11 09:56 UTC, rlibouba commented
Compleams is divided into 5 modules. I wrote an xml file for three of them (miniprot, run and analyze), to facilitate use on Galaxy. When I run tests, only one of the modules appears.

2023-12-11 12:35 UTC, bernt-matthias commented
The tools have syntax errors: ` galaxy.tools.parameters.basic.ParameterValueError: parameter 'min_diff': the attribute 'value' must be an integer` you can find them if you check the `planemo test ` output (I admit that they are quite hidden). They should also be shown of you call `planemo lint` on the tool XML files (I guess that also `vscodium` shows an error .. if you use this software for editing .. ).

2023-12-13 13:53 UTC, rlibouba commented
The miniprot module had an execution problem, so I opened a way out. The problem has been corrected. I also asked if it was possible to make a release to update the conda package.  (https://github.com/huangnengCSU/compleasm/issues/14)

2024-01-22 14:02 UTC, rlibouba commented
Hello, 
The tests do not seem to have been passed for the datamanager. I can't understand what the problem is. Do you have any ideas?

2024-01-31 06:45 UTC, abretaud requested changes
Thanks @rlibouba, some minor cosmetic stuff, and a little change in the data manager option

2024-01-31 06:45 UTC, abretaud commented on data_managers/data_manager_compleasm/.shed.yml
> +  This datamanager downloads the lines available for Compleasm.
```suggestion
  This data manager downloads the lineages available for Compleasm.
```

2024-01-31 06:45 UTC, abretaud commented on data_managers/data_manager_compleasm/data_manager/compleasm.xml
> +        This datamanager downloads the lines available for Compleasm.
```suggestion
        This data manager downloads the lineages available for Compleasm.
```

2024-01-31 06:45 UTC, abretaud commented on tools/compleasm/.shed.yml
> +long_description: " It’s a tool for evaluating genome completeness form miniprot alignment but also form genome assembly"
```suggestion
long_description: "A tool for evaluating genome completeness form miniprot alignment but also form genome assembly"
```

2024-01-31 06:45 UTC, abretaud commented on data_managers/data_manager_compleasm/data_manager/compleasm.xml
> +        <param name="name" type="text" label="lineage name" value="" />
It would be nice to have a select box with the list of possible lineages, and to be able to select multiple/all lineages at once

2024-02-02 08:49 UTC, abretaud reviewed
almost there!

2024-02-02 08:49 UTC, abretaud commented on tools/compleasm/compleasm.xml
> +        <param name="lineage" label="Choose the BUSCO lineage to be used" type="select" multiple="false" help="Eukaryota is the default line">
Get this from the data table now that you have a data manager

2024-02-02 08:49 UTC, abretaud commented on data_managers/data_manager_compleasm/data_manager/compleasm.py
> +            "value": base_name,
You need a value for the `version` column too (0.2.5 I guess)

2024-02-03 14:39 UTC, bgruening commented on tools/compleasm/tool-data/compleasm.loc.sample
> +# mb_downloads	eukaryota	1.0	${__HERE__}/
```suggestion
# mb_downloads	eukaryota	1.0	/path/to/compleasm/data/
```

2024-02-03 14:41 UTC, bgruening commented on tools/compleasm/tool_data_table_conf.xml.test
> +        <file path="${__HERE__}/test-data/compleasm.loc"/>
```suggestion
        <file path="${__HERE__}/test-data/compleasm.loc.test"/>
```

Maybe, to indicate this is the test file?

2024-02-03 14:42 UTC, bgruening commented on tools/compleasm/test-data/compleasm.loc
> +# mb_downloads	eukaryota	1.0	${__HERE__}/
You don't point to any data here? In your test you are using `eukaryota`, but its not listed here. 
Sorry, if I'm missing something.

2024-02-03 14:43 UTC, bgruening commented on tools/compleasm/.shed.yml
> +long_description: " A tool for evaluating genome completeness form miniprot alignment but also form genome assembly"
```suggestion
long_description: "A tool for evaluating genome completeness from miniprot alignment but also form genome assembly"
```

2024-02-05 14:44 UTC, rlibouba commented on tools/compleasm/test-data/compleasm.loc
> +# mb_downloads	eukaryota	1.0	${__HERE__}/
By default, all lineages are downloaded and installed in a mb_downloads folder. By simply entering the lineage name (on the command line), compleasm is able to check if data for this lineage is present in the folder. It is possible de change the name of this folder. 
My tests all passed. I'm trying to modify the wrapper xml so that the list of lineage listed in the data manager xml can be retrieved. For the moment, it's not working. I get this error : `parameter 'name': requires a value, but no legal values defined`

2024-02-13 09:59 UTC, abretaud commented on tools/compleasm/compleasm.xml
> +<tool id="compleasm" name="compleasm" version="@TOOL_VERSION@+galaxy0" profile="20.01">
Need a better looking name/description

2024-02-13 09:59 UTC, abretaud commented on tools/compleasm/compleasm.xml
> +        <param name="lineage" type="select" label="Lineage">
Isn't this redundant with the `busco_database` param?

2024-02-13 15:36 UTC, rlibouba commented
I've made some changes to respond to comments

2024-02-13 15:55 UTC, bgruening commented on tools/compleasm/compleasm.xml
> +        <param argument="--specified_contigs" type="text" label="Specify the contigs to be evaluated" optional="true" help="e.g. chr1 chr2 chr3. If not specified, all contigs will be evaluated"/>
Should we only allow inputs here that are characters, numbers or spaces?

2024-02-13 15:55 UTC, bgruening commented on tools/compleasm/macros.xml
> +    <token name="@TOOL_VERSION@">0.2.5</token>
maybe add VERSION_SUFFIX here as well?

2024-02-13 15:55 UTC, bgruening commented on tools/compleasm/macros.xml
> +            <citation type="doi">10.1101/2023.06.03.543588 </citation>
```suggestion
            <citation type="doi">10.1101/2023.06.03.543588</citation> 
```

2024-02-13 15:56 UTC, bgruening reviewed
Looks very good! 2 small questions inline

2024-02-14 14:08 UTC, rlibouba commented
Hi, I've made some new changes

2024-02-14 14:13 UTC, bgruening approved these changes

2024-02-14 14:14 UTC, merged

2024-02-14 14:14 UTC, bgruening commented
Thanks a lot @rlibouba