JBrowse2: manually merged @abretaud #3997 into #5695
galaxyproject/tools-iuc pull request #5697
Opened 2024-01-08 00:27 UTC by fubar2

* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR adds a new tool or tool collection

#### Merges #5695 derived from @hexylena JBrowse1 tool with most of the improvements made in @abretaud #3997 such as adding track controls to the tool form. Sad I didn't know about #3997 until after repeating a lot of the same updates - but that PR included all the track formatting UI form code that #5695 was missing.

Adds:
- all working json construction without calls to jbrowse cli
- tests for common track types
- working default session 
- Form controlled track options including colour/styling for different track types. 

Removes all #3997 failing tests - most still had JB1 elements so need updating. 
Fixes the failure testing in biocontainers when Jbrowse is copied - different path in Conda. 

Available for testing from the [toolshed](https://toolshed.g2.bx.psu.edu/view/fubar/jbrowse2dev/af3fba6c21aa)

Screenshot shows test bed bam vcf maf bigwig gff sample data tracks
![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/82d4e93b-9fe5-43b9-9125-671f110aec96)

and HiC
![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/a440c644-610c-42c2-af6c-3fe62d52dd0e)

- SPARQL and paf remain to be implemented.
- Needs a test for each track input type

2024-01-08 11:06 UTC, hexylena commented
It will take some time to review. Would it be possible to re-base your work atop #3997 and retain the commits? @abretaud has been working on this for a long time, it would be a pity to lose those commits and authorship attribution fully. It would really help the reviewing process, it'd be clearer what was new, relative to the work Anthony has already done, so he could say whether the changes made sense or what might still be needed.

2024-01-08 11:44 UTC, hexylena requested changes
Some comments in line, i'm really excited for jb2, but there's a lot of small details to get the tool optimal.

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/servejb2.py
> +# borrowed from https://github.com/danvk/RangeHTTPServer
you must reproduce the license in this file then.

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/static/images/bam.png
this is a jb1 screenshot

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/static/images/blast.png
this rendering is from the BlastXML plugin which is jb1 only, not sure if we migrate that or replace the rendering. Perhaps just using the MAF rendering is the better choice, and providing a new converter, blatsxml to maf.

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/static/images/sections.png
more jb1

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/test-data/index.html
> +            var dojoConfig = {
dojo is also jb1, so, this index is wrong.

thus also the test is wrong or this isn't being tested, both of which are sub-optimal.

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/maf2bed.pl
this probably needs a license header due to importing it from the plugin

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/jbrowse2.xml
> +will serve the unarchived JBrowse2 configuration, so it can be browsed by pointing a web browser to localhost:8080
oof. This is unfortunate. Maybe we rename it just `server.py` or something more clear, it's in a jb2 folder it doesn't need to be named jb2.

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/jbrowse2.xml
> +One extra step is required before they can be viewed. A local python web server must be started using a script included in each archive.
```suggestion
One extra step is required before they can be viewed. A local web server must be run in order to access the contents, for example using an existing webserver, or the included python script in each archive.
```

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/macros.xml
> +    <token name="@DATA_DIR@">\$GALAXY_JBROWSE_SHARED_DIR</token>
Is this not used?

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/macros.xml
> +This Galaxy tool relies on the JBrowse, maintained by the GMOD Community. The Galaxy wrapper is developed by the IUC
```suggestion
This Galaxy tool relies on the JBrowse2, maintained by the GMOD Community. The Galaxy wrapper is developed by the IUC
```

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/jbrowse2.py
> +        self.subprocess_check_call(cmd)
logging is already handled by the check_call wrapper, why duplicate it ehre?

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/jbrowse2.py
> +                    "url": "https://unpkg.com/jbrowse-plugin-mafviewer/dist/jbrowse-plugin-mafviewer.umd.production.min.js",
please pin the version, otherwise this won't be reproducible (from an end user perpsective)

2024-01-08 11:44 UTC, hexylena commented on tools/jbrowse2/jbrowse2.py
> +        self.subprocess_check_call(cmd)
I think we need to go back to how we did it in jb1 -  a copy of the source code included in the conda package that was copied based on the jbrowse source directory.

Per their description of this command:

> This fetches the latest version of jbrowse-web and unzips it to a folder named "jbrowse2" from github (https://github.com/GMOD/jbrowse-components/releases), you could run this step manually if you wanted to instead.

which makes the job unreproducible, jbrowses generated at different times could behave differently. I'd much rather see a copy of the source baked into the conda package like we used to, to ensure it's reproducible. I get that this was easier though.

2024-01-08 16:37 UTC, abretaud commented
I still have to look into details but for now:

> URLs are used wherever easy to do to minimise the size of JBrowse2 files folder so these are much smaller than jb1 where all were copied. (from #5695)

That can be a problem, ie the output dataset is no longer self-containing but depends on the existence/sharing of other ones, that can be problematic. And I have a use case where I use galaxy to generate jbrowse archives that I can download/deploy on another server.
Having at least an option for that would be helpful

The default session / track styling was still largely WIP, I remember I wasn't sure of the proper way to implement this, and opened a discussion there: https://github.com/GMOD/jbrowse-components/discussions/3568
I don't know if there wer changes in jb code to make this easier since my last try

2024-01-09 01:15 UTC, fubar2 commented on tools/jbrowse2/servejb2.py
> +# borrowed from https://github.com/danvk/RangeHTTPServer
ok - good point - copy of apache2 added

2024-01-09 01:19 UTC, fubar2 commented on tools/jbrowse2/static/images/blast.png
that's the gff display using jb1 code modified to write json. Better rendering is not something I know anything about but at least it does produce a track...so can be improved if somone knows how.

On MAF - awaiting Brad Chapman accepting a PR to fix bcbio-gff for latest biopython - once that's in, the maf code basically from JBI will work well. AFAIK broken and not currently on the track menu in JB1.

2024-01-09 01:20 UTC, fubar2 commented on tools/jbrowse2/macros.xml
> +    <token name="@DATA_DIR@">\$GALAXY_JBROWSE_SHARED_DIR</token>
not used - uses the jbrowse create command to avoid path differences between conda and biocontainers.

2024-01-09 01:21 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +        self.subprocess_check_call(cmd)
Agree with the downside - need to adjust for biocontainers - will take a look.

2024-01-09 01:23 UTC, fubar2 commented on tools/jbrowse2/static/images/bam.png
all were just copied - now removed from repo and help until the help is redone.

2024-01-09 01:24 UTC, fubar2 commented on tools/jbrowse2/test-data/index.html
> +            var dojoConfig = {
No longer used. Removed.

2024-01-09 01:27 UTC, fubar2 commented
No longer used as too unreliable - depending on the history being published and the server being anonymously accessible - otherwise breaks badly.

> I still have to look into details but for now:
> 
> The default session / track styling was still largely WIP, I remember I wasn't sure of the proper way to implement this, and opened a discussion there: [GMOD/jbrowse-components#3568](https://github.com/GMOD/jbrowse-components/discussions/3568) I don't know if there wer changes in jb code to make this easier since my last try

2024-01-09 01:30 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +                    "url": "https://unpkg.com/jbrowse-plugin-mafviewer/dist/jbrowse-plugin-mafviewer.umd.production.min.js",
was following the author's recipe of course - good point. Will fix.

2024-01-09 01:36 UTC, fubar2 commented
>Would it be possible to re-base your work atop https://github.com/galaxyproject/tools-iuc/pull/3997 and retain the commits?

@hexylena: done. Interesting experience.

2024-01-09 01:40 UTC, fubar2 commented on tools/jbrowse2/maf2bed.pl
same apache2_license.txt is now referenced in that header.

2024-01-09 01:43 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.xml
> +will serve the unarchived JBrowse2 configuration, so it can be browsed by pointing a web browser to localhost:8080
this is probably not needed but as you will. Renamed to webserver.py since that's what it does...

2024-01-09 01:54 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +        self.subprocess_check_call(cmd)
left over from some bug ridden anxiety or other. 
Many eyeballs required to get this stuff right ...fixed.

2024-01-09 02:28 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +        self.subprocess_check_call(cmd)
now pinned with
`JB2REL="v2.10.0"` for use in the -t parameter for release tag

2024-01-10 03:19 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.xml
> +One extra step is required before they can be viewed. A local python web server must be started using a script included in each archive.
change committed - thanks..

2024-01-10 17:28 UTC, hexylena commented on tools/jbrowse2/jbrowse2.xml
> +will serve the unarchived JBrowse2 configuration, so it can be browsed by pointing a web browser to localhost:8080
Let's do this instead: [redbean2](https://justine.lol/redbean2/)

- runs on most platforms we'll care about (windows/linux/MacOS)
- single static file
- can serve files
- it's a polyglot binary, the same binary works across all those platforms.
- can automatically open the index page in the user's browser.

it's 2.3M just stuff it in the tool directory and copy from there to the output dir for "full" outputs.

Running `./redbean.com -D . ` will serve the local directory, just include the following as `.init.lua` and she'll be right.

```
-- /.init.lua is loaded at startup in redbean's main process
HidePath('/usr/share/zoneinfo/')
HidePath('/usr/share/ssl/')

-- open a browser tab using explorer/open/xdg-open
LaunchBrowser('/index.html')

function OnServerListen(fd, ip, port)
   unix.setsockopt(fd, unix.SOL_TCP, unix.TCP_SAVE_SYN, true)
   return false
end

function OnClientConnection(ip, port, serverip, serverport)
   syn, synerr = unix.getsockopt(GetClientFd(), unix.SOL_TCP, unix.TCP_SAVED_SYN)
end

-- this intercepts all requests if it's defined
function OnHttpRequest()
   if GetHeader('User-Agent') then
      Log(kLogInfo, "client is running %s and reports %s" % {
             finger.GetSynFingerOs(finger.FingerSyn(syn)),
             VisualizeControlCodes(GetHeader('User-Agent'))})
   end
   if HasParam('magic') then
      Write('<p>\r\n')
      Write('OnHttpRequest() has intercepted your request<br>\r\n')
      Write('because you specified the magic parameter\r\n')
      Write('<pre>\r\n')
      Write(EscapeHtml(LoadAsset('/.init.lua')))
      Write('</pre>\r\n')
   else
      Route() -- this asks redbean to do the default thing
   end
   SetHeader('Server', 'redbean!')
end
```

2024-01-10 17:30 UTC, hexylena commented
>  An, um, interesting experience since I've never tried it before.

did a bang up job, cheers. really appreciate it!

> There's lots more to do and it needs feedback from users to improve, but arguably useful enough to expose as is so we can get that user feedback.

yeah, i mean, it sounds like there's a lot of pressure from one side to get this shipped, it could be installed just on that server in the current as-is state for better "real life" testing before we get it finalised since, yeah it's a massive tool.

2024-01-11 11:56 UTC, abretaud requested changes
Ok, I've made a first review of the code, with a few comments/changes to do. Can you look into it before merging?
In the meantime I'd like to also make a few tests locally

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +JB2REL = "v2.10.0"
I'm sure we'll forget to update it here :grimacing:
Could you pass it in the command line so that we can use the defines in the macro?

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +# change to accumulating all configuration for config.json based on the default from the clone
isn't it a leftover comment?

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +            if self.debug:
Can you use `logging.basicConfig` at the top of the script to show or not debug messages?

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +                genome_name = genome_name.split()[0]
We'll surely get name collisions here, and meaningless names too, we need a better name cleaning method.
There was some code for that in my PR, I guess you can reuse it somehow

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +        # dsId = trackData["metadata"]["dataset_id"]
can be deleted if I udnerstand correctly, we're back to copying data now?

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +            elif dataset_ext == "bam":
cram is missing, it's very similar to bam, I had a add_xam for both in my PR IIRC

2024-01-11 11:56 UTC, abretaud commented on tools/jbrowse2/jbrowse2.py
> +        self.usejson = True
Is there a reason to keep both methods?

2024-01-13 07:31 UTC, fubar2 commented on tools/jbrowse2/macros.xml
> +            <requirement type="package" version="1.82">biopython</requirement>
Those calls are still being deprecated - just back until then - and need to undo corresponding fixes to the python script. 
Prefer waiting for https://github.com/chapmanb/bcbb/pull/141 before altering at all, because @bgruening had to manually adjust the biocontainer last time!

2024-01-17 07:33 UTC, fubar2 commented
Now somewhat simplified again, but seems to be working with the test data I have.

#### Track details, like colours, can only be configured by the user in the track browser - not on the tool form.

Making them configurable requires hacking the internal _default state_. 
It is not documented, so requires reverse engineering and it has no long term stable guarantees.
It can be done as people find time and users make demands, but not by me.

#### Note to reviewers

Please don't ask me to fix the things listed below as part of a review, because I can't. This needs people who understand paf, cram and sparql which is not me. Jbrowse2 is a very substantial undertaking, and as far as I can tell, this PR is now sufficiently useful to have available as a starting point, to which others can contribute the bits they know and care about.

#### Things remaining:

- testing/fixing PAF synteny tracks - the code is there but untested as I have no data or clue;
- testing/fixing SPARQL tracks - ditto
- modifying the working bam code for cram input. 
  - Whether they are the same function is up to whoever has cram data to test and PR. 
- update to 2.10.1 and bcbbio-gff to restore MAF tracks - awaiting Brad merging a PR to deal with BioPython deprecations
  - Biopython has temporarily restored the deprecation with a warning but only until next release - it will all go then so we need Brad's help. AFAIK @bgruening has to fiddle with the biocontainer? Better to burden him only once, rather than several times in a row?

2024-01-17 08:37 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +            elif dataset_ext == "bam":
PR please. I cannot do this as I have no data or experience.

2024-01-17 08:39 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +        # dsId = trackData["metadata"]["dataset_id"]
yes. just a note to myself. It took a while to figure out so preserved. I think it will be useful but have not had time to make it a reliable alternative input source - it requires duplicating a lot of jbrowse2 internal logic for index file and other accessories.

2024-01-17 08:41 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +                genome_name = genome_name.split()[0]
Now uses a hash for the file name. 
The genome name really matters a lot for MAF where it must match precisely...

2024-01-17 08:41 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +            if self.debug:
all gone now

2024-01-17 08:42 UTC, fubar2 commented on tools/jbrowse2/readme.rst
> +    - UPDATED to JBrowse 2.10.0
done

2024-01-17 08:43 UTC, fubar2 commented on tools/jbrowse2/readme.rst
> +- 2.10.0+galaxy2
see note below. let's wait for Brad and the bcb gff fix for updating dependencies.
I'm done here. If you want to change the pinned version and test it, a PR would be welcomed.

2024-01-17 08:44 UTC, fubar2 commented on tools/jbrowse2/apache2_license.txt
> +   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
note added to the specific code.

2024-01-17 08:49 UTC, fubar2 commented on tools/jbrowse2/macros.xml
> +        <citation type="doi">10.1101/gr.094607.109</citation>
Might as well have both for the same price.

2024-01-17 08:50 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +JB2REL = "v2.10.0"
no but someone who wants to is more than welcome to.

2024-01-17 08:51 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.py
> +# change to accumulating all configuration for config.json based on the default from the clone
probably is. there are quite a few. Some are useful, others not.

2024-01-17 09:03 UTC, fubar2 commented on tools/jbrowse2/jbrowse2.xml
> +will serve the unarchived JBrowse2 configuration, so it can be browsed by pointing a web browser to localhost:8080
A PR would be favourite. It's probably not needed if https://github.com/GMOD/jbrowse-components/discussions/4161#discussioncomment-8024748 works.

2024-01-17 09:32 UTC, hexylena commented
> Track details, like colours, can only be configured by the user in the track browser - not on the tool form.

That's unfortunate, but no, let's not undertake modifying internal state, that sounds fraught. We *should* consider flagging this upstream, since it was a nice feature in the past and gave users a bit of control, but also maybe we can live without it. (I'm saying: I used it and loved it; not sure anyone else did.)

> Advice is wonderful, but I cannot sustain all the work of implementing it.

I mean, yeah...  this is why it took us so long to get here, none of us have been able to allocate the time and energy to implementing such a big change. @abretaud had done all the work up until here, I would have loved to help but haven't been able to find free time. It doesn't help that for many of our use cases, jb1 is still sufficient (especially e.g. apollo.), and there wasn't an immediate need for jb2 even though it's a massive improvement in many many ways.

Sorry you had to find out the hard way :( doubly so, for learning about the existing PR after expending so much energy.

> Please pitch in if you think this tool is worth having.

We definitely do, but "things we think are worth having" and "science-capitalism allocates us available bandwidth to work" are two very, very separate axes.

> Jbrowse2 is a very substantial undertaking, and as far as I can tell, this PR is now sufficiently useful to have available as a starting point

yes, we can look towards merging. I guess you'll have to give @abretaud and I some time to install and test it (but cases like this are also *why* EU has https://github.com/usegalaxy-eu/temporary-tools/, to ship testing tools so they can use it immediately and/or debug a pre-release tool.)

> testing/fixing SPARQL tracks - as above

not a priority.

2024-01-17 11:22 UTC, fubar2 commented
> and I some time to install and test it
That would be wonderful when you can find time. No more I can do at this point.

2024-01-18 16:28 UTC, bgruening commented
@hexylena would it help if I deploy it on EU as test tool?

2024-01-18 18:26 UTC, hexylena commented
@bgruening that would be a fantastic help!!

2024-01-18 19:07 UTC, bgruening commented
@hexylena @abretaud here you go: https://usegalaxy.eu/?tool_id=jbrowse2

2024-01-19 04:03 UTC, fubar2 commented
whoopsie

2024-01-19 04:04 UTC, fubar2 commented
not intended

2024-01-19 05:02 UTC, fubar2 commented
This is being reopened as a new PR as some git repairs went bad.

2024-01-19 09:57 UTC, hexylena commented
Danke sehr @bgruening

2024-01-19 10:03 UTC, hexylena commented
https://usegalaxy.eu/u/helena-rasche/h/jbrowse2-testing looks like some issues unfortunately,  not sure what's happening there.

2024-01-19 10:10 UTC, fubar2 commented
> https://usegalaxy.eu/u/helena-rasche/h/jbrowse2-testing looks like some issues unfortunately, not sure what's happening there.

dependencies were not installed so jbrowse not found :(
I just ran it on EU - please try again?

2024-01-19 10:13 UTC, bgruening commented
please try again, works now for me.

2024-01-19 10:22 UTC, hexylena commented
success-ish

is it expected that no track data is rendering for me? (chrome + firefox on linux)
https://usegalaxy.eu/datasets/4838ba20a6d8676556a41e2bf6a52c7d/preview?__vkey__=1705659579999

![jbrowse with uniformly empty tracks](https://github.com/galaxyproject/tools-iuc/assets/458683/90c6ae00-5bef-4e4c-966d-0960c5419bca)

2024-01-19 11:32 UTC, fubar2 commented
When I choose the *other* NC contig:
![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/066ed72c-2b1a-4bd9-adbf-5e9d4d0a9863)

2024-01-19 11:38 UTC, hexylena commented
Ah that does look better. That absolutely needs to be fixed. Where is `genome.fa` coming from? Is it a URL parameter we can pass based on the first provided contig?

(Also can we re-open this PR, the git history was fine here, the new one less so.)

2024-01-19 11:49 UTC, fubar2 commented
> (Also can we re-open this PR, the git history was fine here, the new one less so.)

I managed to make a real mess of the branch with some maladroit repair work.

2024-01-19 12:41 UTC, hexylena commented
> No idea where that empty genome.fa is coming from. It's not a built in feature that I know of.

No, just a single file, the `genome.fa` is the name of the input file, so, galaxy must be passing that in somehow. It's being referenced in many places as the "assembly".

![image](https://github.com/galaxyproject/tools-iuc/assets/458683/5d257e1f-8ac4-4da0-bc12-9ece779f89b6)

I think this will also be relevant when we want to display multiple genome assemblies together for the synteny view. E.g. we'll need to add a "grape" and "peach" assembly separately, with separate genomes and separate tracks.

I suspect we need a top level `repeat` in the tool to support this use case, where we can give each assembly a name, and then select a genome/fasta file to go with that assembly, as well as tracks. It'll not be relevant for most people, but they can just leave the 'default' assembly there and won't have to modify anything.

I'm flagging this specifically because it will make different versions of the tool very hard to switch between, I think we need to add this now, so when we use in the future, people will be able to "rerun with newer version" without having to completely reconfigure their entire jbrowse. You can set min=1/max=1 on the repeats for now, so you don't have to implement any of the internals for supporting/adding multiple repeats, but I think the options + data need to be there to make users' lives easier as time goes on, and when they want to use a newer version of the wrapp.er 

> Do you have >1 genome selected on the tool form? Never tried that.

this would generate multiple JBrowses.

> I managed to make a real mess of the branch with some maladroit repair work.

Ah, gotcha.

> Review

I miss the option to set big wig scaling (local vs global), but I guess this needs to be filed upstream. And I miss the multibigwig plugin

and some other comments

- [ ] track groupings do not seem to be used, they should be.
- [ ] I don't understand the purposes of the colours. I changed mine, nothing seemed to change in the output. Maybe they aren't passed correctly? I'd like to use them that's a cool feature. 
- [ ] as far as i can tell font size also isn't taking effect. 
- [ ] why does setting the default location break the session? I am no longer loaded directly into jb2 with the track view, instead I'm in a "create a new session" view where i have to select that yes, I really want that file.  Should this be passed via the URL or something instead to prevent that? I just wanted to load a specific location.
      ![image](https://github.com/galaxyproject/tools-iuc/assets/458683/0291d4ac-8c86-4965-9fab-1223e06e08fd)

filed/commented on upstream:

- https://github.com/GMOD/jbrowse-components/issues/1765
- https://github.com/GMOD/jbrowse-components/issues/4173
- https://github.com/GMOD/jbrowse-components/issues/4174


Since you have chosen to continue using the trackXML that we devised, I'd like to propose a very small tool that does a jb1 to jb2 "upgrade", it should take the jbrowse1 HTML output (then look on it's files_path for the galaxy.xml) and pass the galaxy.xml directly to the new configuration script. **If** your script is properly handling missing fields (by ignoring or using a sensible default), then it could be a very easy and cool feature to motivate users to try out the new jb2.

2024-01-20 03:43 UTC, fubar2 commented
@hexylena WRT the genome.fa issue - "genome.fa" is the name of the file in galaxy.xml I see so that part is correct and probably not related to the template name `genome`. Actual reference compressed/index filenames are hashed now to avoid collision as suggested, but the name matters a lot for MAF - must be the primary genome in the maf chromosome identifiers - that may need some fixing but that's why it is used as the name.

That said, the original jb1 code around line 1170 looks like it should pick up the general options default position and fix the disconnect between the refname and the genome name.
I tried setting them in my sample and AFAIK it generates a config.json that seems to as described in the documentation at https://jbrowse.org/jb2/docs/config_guides/default_session/ but does not seem to do the needful. 
Could you please double check in a downloaded archive if the config.json is right but not working?

2024-01-20 07:35 UTC, fubar2 commented
Grrr. Now that I've fixed that, the genome name is wierd. Hang about.

2024-01-20 10:07 UTC, fubar2 commented
> why does setting the default location break the session? 

It doesn't now - but your default location has to be something like `NC_00913.3:1..8999` and that period in the contig name was breaking the old regexp. Pretty sure that will fail in jbrowse1 with that regexp? Added a period and it seems to work for my VGP example.

2024-01-22 09:20 UTC, hexylena commented
> Much remains to do. Question is, when is a big complex tool ready to expose for proper testing?
> So far, only three of us have tried it AFAIK.

I would be open to shipping a first version when:

- [ ] top level is wrapped in an "assembly" repeat, *in planning for* future multiple genome builds, without **any** expectation of that working now/PAF/etc.
- [x] it opens on the first contig

the rest can be skipped. The checklist in my last issue, yeah, they're issues but they can wait, none of them are experience breaking. I do not expect synteny to be done soon, that will probably need some discusison with jbrowse regarding CLI tools for configuration that into a a good user experience in galaxy.

2024-01-22 09:39 UTC, hexylena commented
Oh, good work, colours are there, and it's opening on the locaion correctly!

![image](https://github.com/galaxyproject/tools-iuc/assets/458683/8f3ce510-0555-4bc7-9cde-ae2dfb61bff6)

That is fascinating behaviour though, it really subsets the genome, it doesn't just focus the entire genome's view there, it gives you an actual subset that you cannot scroll past the end of. Note the disabled zoom out box, you cannot zoom out. Hilarious.

Ok, then I change my sine qua non list to be:

- [ ] initial location renamed to "subset to display to new users", because it isn't an initial location, it's an initial subset. You have to change your viewed contig to fix that.
- [ ] Wrap it in an (unused) repeat for "assembly" with min=1/max=1.

2024-01-22 09:43 UTC, hexylena commented
`re.search(r"^(\w+):(\d+)\.+(\d+)$",`

that regex is quite restrictive, what about `re.search(r"^([^:]+):(\d+)\.+(\d+)$"`?

2024-01-22 09:46 UTC, hexylena commented
>  The paf code has been rewritten and so has the genome maker, so syntenic tracks can add genomes. The jbrowseConnector now has a list of genomes for that purpose. It keeps the default genome for non-synteny tracks like vcf that need a genome. It is set when the first assembly is added. May need rethinking but that's what's there. Problem is I have neither a paf file nor a clue about synteny, to test the new synteny track.

I mean, for my use case it would look like this:

- i have a reference genome
- I have a couple of related genomes I want to visualise in synteny
- as a user, I want to go to jbrowse and add my assembly + track, and then additional assemblies with their own datasets, all from my own data.

so, we'll need the ability to provide multiple "assemblies" eventually to the jb2 tool.

I don't think we can do the synteny on a decent time frame now, so, again let's just wrap it all in one big repeat for assemblies, and then in the future we'll tackle that in a good way. I just feel quite certain we'll want to support multiple assemblies, and if the tool already had the XML element for it, it won't break re-run for our users.

2024-01-22 10:59 UTC, fubar2 commented
>  top level is wrapped in an "assembly" repeat, in planning for future multiple genome builds, without any expectation of that working now/PAF/etc.

The code is already a loop for a list, but the XML does not allow multiselect.
 
```
def process_genomes(self):
 
       for genome_node in self.genome_paths:
```
The code isn't changed much so `genome` list at jbrowseConnector construction items will all be compressed and indexed into the browser. The very first one will be used when a vcf or other track wants a genome. I'm not clear what to change - what's the use case? Can a user put tracks with two or more different reference sequences to good use other than synteny? How do the tracks know which reference they are supposed to be related to? Other than synteny, not sure how multiple genomes works. Even MAF all use the same reference.

For synteny, JB2 expects a paf and a list of genomes. It adds any new genomes ready for a track to the list from the paf form choice, ready for display - untested.

2024-01-22 11:04 UTC, fubar2 commented
> so, we'll need the ability to provide multiple "assemblies" eventually to the jb2 tool.

You can. When a paf track is specified, it includes another genome. That gets indexed and added to the directory ready for tracks if the code works right which it probably does not.
![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/b510afd9-7425-461a-b1ea-a2c32d4c5c85)

2024-01-22 11:21 UTC, fubar2 commented
Ah. Here's what I got by rerunning the most recent job in that history, setting the `default location` (name has been changed to subset as requested...) to `NC_000913.3:1..5000`

Remember, `genome.fa` is just your reference or assembly dbkey for MAF or similar uses. 
The display has to be a start..end of one specific contig or chromosome in that assembly.

![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/e70a290c-5205-4488-acaf-c1948e7c1a8c)

2024-01-22 16:11 UTC, hexylena requested changes
My previous review(s) have been looking only at the functionality of the UI/UX as a user, we've reached an agreement on that for all intents and purposes:

- I've ceded a default view as an upstream issue, and *all* of the other potential things I flagged, it's fine, don't do them.
- (except for the repeat I want wrapping the entire inputs section to support 'assemblies' as a top level concept to make it more future proof. If you cannot add this, tell me, I will once we get there. Ignoring for the test cases, it will be a 4 line diff.)

Now I'm looking at the code

Since the rebasing hasn't happened yet (or rather it did, and then was subsequently un-done), I'm looking primarily at a diff of the two branches, to see what's actually changed (`git diff -w pr-3997:tools/jbrowse2/jbrowse2.py pr-5697:tools/jbrowse2/jbrowse2.py`, if you have two appropriately named branches on hand.)

jbrowse.xml diff, compared to #3997

- mostly things that are supported in anthony's branch, are removed (cram)
- some new test cases added (yay!)
- most of the help text deleted (shrug. I don't think anyone was ever reading it.)

jbrowse.py diff

- clearly run through black (yay)
- all of the tracks are manually configured via JSON, rather than using the built in `add-track` command. (This is not good.)
- categories support lost
- assemblies support lost (rather, assemblies are made per-provided .fa file which is not desirable from my view.)

You've added some scripts and utilities and nice stuff (cool! it's nice! the webserver I think would be more generally useful as redbean, but I also don't think anyone will actually use this, so, I do not care, just leave it as is.)

That said, I do not think I can accept this PR, I am -1 on it as it stands.

Anthony's code is significantly cleaner, it has native support for assemblies (in the .py at least, already handling an edge case I noticed of naming collisions when testing myself with the CLI), and more features like CRAM support. I want all of that work to still be included. I can't accept it being dropped. Nor can I accept you asking him to PR his changes into your branch, when it should be the other way around.

The diff over what is currently present in @abretaud's PR is maybe interesting, but the replacement of `add-track` with more brittle json configuration is also sub-optimal, though I suspect a relic of your first PR where you mention using pointing inputs at URLs to avoid copies (I would have rejected that too, sorry, it will fail in far too many environments.). The result however, is that it relies too much on jbrowse2 internals when there's no need and they provide really nice CLI tools, whose cli interface is going to be more stable over time, and doesn't require reverse engineering their internal configuration, which makes adding new formats a cinch because they're already supported by the underlying add-track function.

*I really do want whatever useful changes you've made!!* I'm really happy you're motivated. I've probably killed a lot of that motivation, and I'm sorry for that, but I have my standards for what I approve, and I'd like to see _all_ of our goals met; you, me, GGA, Anthony. You've done great work getting the dependencies updated and worrying about a lot of the little details that needed to be done, Thank you.

Still, I feel really sad at how much code has been written, how *many* commits, how many adventures you've had with git, how many PRs that have been opened and closed, how much stress was generated for all of us. It's not fun for anyone, I'm sorry it happened, that sucks.

As you've told me, this is not a pleasant review process, it's not a pleasant feeling, and I can completely understand and empathise there, I think **all** three of us feel that way. I really had hoped that after the first discussion, this could have been rebased on @abretaud 's PR, and we could review the you know, 5 commits or whatever, and merge it. Instead we've had a lot of miscommunications that lead to long discussions (assemblies), and multiple branches opened and closed, dozens of commits made that have to be re-reviewed, and that has been really unfortunate. I don't know how we could work around that, if you have suggestions here for next time I am very open to what could change.

The way I see to move forward is to:

- open a PR to anthony's branch
- format his code with black as one commit, with no other changes, to make diffs clearer.
- add in the bits of your code that are missing to his, as _one_ big commit. I didn't want you to lose all of your commits, but, maybe rebasing is too complicated due to the very divergent histories.
- leave it, make no more changes, we will review that and try and merge it quickly for you.

Perhaps I shouldn't've suggested rebasing, perhaps I should've suggested something like this from the beginning.

2024-01-22 22:52 UTC, fubar2 commented
@hexylena Thanks!
A lot to digest. 
Might be best to go back to #3997 and get it working properly, unless there's a better suggestion that doesn't involve me doing all the remediation needed for this one.

2024-01-26 00:53 UTC, fubar2 commented
Closing this PR here and moving to https://github.com/usegalaxy-eu/temporary-tools/tree/master/jbrowse2 if anyone wants to contribute. Synteny is now available - see below.

At this point, it seems that at least two things are required that I can not or will not do to satisfy review:

- rebasing this PR to a previous independent pull request
  - #3997 lay idle in a non-working state for most of the year before I started on this code.
  - Annoying I didn't find it before I started, but that's how things have worked out.
  - Got a rebase done after much pfaffing about somehow, and then later screwed up the branch history totally. 
  - A PR to correct the historical record and port any missing fixes from all that work would be welcomed. 
  - I am in favour, but am neither motivated nor competent to do that work. 
- calls to the jbrowse CLI are required to replace most of the generated json. 
  - Generated json works well but at some point, the CLI did not, which is why it was swapped out.
  - The CLI requires less code, so simpler and cleaner approach *if* it can be made to work but otherwise same functionality.
  - The CLI for default session generation has long been known non-functional for at least a year, so json is needed.
  - assemblies seem to need json - even the old PR used it.
  - I have no specific objections to reverting to the CLI where it can be made to function so a PR would be welcomed.
  - I have no motivation to do that work. 
 
![image](https://github.com/galaxyproject/tools-iuc/assets/6016266/d5143223-37bf-4568-9e4b-662861471e64)

2024-01-26 00:53 UTC, closed without merging

2024-01-26 10:20 UTC, hexylena commented
> Will continue development at [usegalaxy-eu/temporary-tools@master/jbrowse2](https://github.com/usegalaxy-eu/temporary-tools/tree/master/jbrowse2?rgh-link-date=2024-01-26T00%3A53%3A54Z) if anyone wants to contribute.

EU's temporary tools repo is **not** intended for outside contributors. It's just used for deploying existing repo (from elsewhere) to EU. I would recommend against it.

It is really unfortunate that you can't contribute on top of Anthony's PR. I guess the two of us will cherry-pick from your branch when we find time to continue that PR.

And in the end we will have two competing jbrowse2 implementations. I don't think that's the best result for the community, but ok, maybe that's the best solution in this case.

> swap out functional generated json for the CLI. 

If it's not always reliable, I think those are upstream issues! The whole community would benefit from us reporting.

> Multiple separate sets of assemblies and their tracks are mandatory for approval. 

I get that you don't have a use case, but I do, I'm sorry we can't reach agreement on that. 

for the record again, I was _not asking for full support for multiple assemblies_, but only a **2 line diff** (ok some some more to fix up test cases but all changes not requiring a lot of work), adding a repeat element I could help fill in later, that would help users in the future.

Thank you for the time spent on this discussion, I wish you much success with your implementation.

2024-01-26 11:12 UTC, hexylena commented
I would recommend changing your toolshed API key

https://github.com/galaxyproject/tools-iuc/pull/5697/files#diff-98cd68d15f58349113186306e07f32d7ffdbe4bd5adeb65d25baf7f1389b2c0e

2024-01-27 01:44 UTC, fubar2 commented
>for the record again, I was not asking for full support for multiple assemblies, but only a 2 line diff (ok some some more to fix up test cases but all changes not requiring a lot of work), adding a repeat element I could help fill in later, that would help users in the future.

If I understand correctly, @hexylena mandates a non-functional repeat, so that when someone who cares gets around to adding all the code needed to make it work, future users will be able to rerun old jobs. Until then, the tool must remain broken, and users filling in the non-functional repeat elements will find they have zero impact. 

The reviewer insists that because I As a consequence of my refusal to break working code for purposes I don't understand, it seems there will be redundant independent re-development from a broken old PR.

Is there anything else that needs to be fixed? If not, why not approve this as is, and submit a PR to make it do exactly what you need when you find time.

2024-02-01 07:30 UTC, abretaud commented
Giving my point of view now as I didn't have much time to follow closely enough before. I have to say I'm very troubled to see this unfortunate turn of events.

First I'm 100% happy to see interest in a jbrowse2 tool, and can't wait to see it working. I need it for different projects, I have no interest in blocking or delaying anything.

I'm guilty of not finishing what I started in #3997, but I've always been completely open to anyone contributing to it, that's exactly why I opened a WIP PR. I think the jb code has also evolved in good ways since then, probably solving a few of the problems I encountered.

It's unfortunate that you hadn't seen #3997 before you started, but it was clearly not hidden, it was evoked at last GCC and various annotation meetings, and on GGA matric channel. But ok, that's how things have worked out, we can't change this now.

So you opened your new PR out of nowhere and have been super pushy to get it reviewed and merged quick. @hexylena and I have spent time reviewing it, although we had other plans. Now what I see is that :
- apart from a first rebase that was then lost in opened/closed PR and forced pushes, you haven't made more efforts to integrate your work with what had already been done in #3997. I know this is a huge PR, and it's not easy to do, but that's how it works: when you contribute you need to adapt to what is existing.
- you declined many of our comments with "A PR from someone more xxx is required" : again, you propose a contribution, you can ask politely for help but you can't just ignore other peoples' use cases
- I don't see how these comments were so hard to address, given that @hexylena proposed to focus on a shortlist, and that for CRAM it works essentially as BAM files and there's working code in #3997  (coded it in like 30min in my PR without ever using CRAM format before), and adding a top level repeat is maybe boring (renaming fields) but without any programming challenge
- you end up with an attack against @hexylena who have spent hours reviewing/testing your work and trying to find solutions constructively
- and finally you seem to continue working on your forked tool on a repo that has never been made for that, which will only bring confusion to us contributors, and to Galaxy users ("wait, which jbrowse2 tool did you use?").

I don't like any of this. I understand that there's pressure to get something out quick, but it's no reason for this kind of turn of events.

So yes, I'm troubled. I'm confident that the latest work from @hexylena will allow us to merge #3997 soon, I just hope that we can integrate your valuable work at some point.

2024-02-01 07:52 UTC, fubar2 commented
This has indeed turned unpleasant but please understand I submitted a functional, useful PR before your work was pointed out. No matter what, I refuse to be bullied into making a change someone else wants that has no impact on what I am busy working on. 

As always, submit a PR, or do whatever you need to do. 
There are [10 track types currently working](https://github.com/fubar2/temporary-tools/tree/nohash/jbrowse2), and when the IUC reproduces that work, I'll use it. Who wrote it is all the same to me.