Add Pairtools sort
galaxyproject/tools-iuc pull request #5910
Opened 2024-03-26 14:04 UTC by diegomics

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [x] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

2024-03-26 14:13 UTC, bgruening commented on tools/pairtools/sort.xml
> +        <data name="output_sorted_pairs" format="pairs,pairsam" label="${tool.name} on ${on_string}: .pairsam" lines_diff="10"/>
lines_diff does not work for outputs, only for test outputs

2024-03-26 14:13 UTC, bgruening commented on tools/pairtools/sort.xml
> +        <param name="pairs_path" type="data" format="pairs" label="Input pairs file" help="Input .pairs/.pairsam file"/>
pairs is not a valid Galaxy format

2024-03-26 14:30 UTC, diegomics commented on tools/pairtools/sort.xml
> +        <param name="pairs_path" type="data" format="pairs" label="Input pairs file" help="Input .pairs/.pairsam file"/>
:(
in the parse xml we have this line and it worked...

`<data name="output_parsed_pairs" format="pairs"`

I can change it to text,tabular. Also pairsam?

2024-03-27 09:47 UTC, SaimMomin12 requested changes
Hi @diegomics,

A small suggestion inline.

2024-03-27 09:47 UTC, SaimMomin12 commented on tools/pairtools/sort.xml
> +        </data>
Repeated ending tag.

```suggestion
```

2024-03-27 09:56 UTC, SaimMomin12 commented on tools/pairtools/sort.xml
> +        <param name="pairs_path" type="data" format="pairs" label="Input pairs file" help="Input .pairs/.pairsam file"/>
I just double checked, .pairs and .pairsam both are tabular format data as per https://pairtools.readthedocs.io/en/latest/formats.html#pairs

If we all agree, we can stick to `"format=tabular"`? If not, we are also happy to include .pairs and .pairsam format to Galaxy.

2024-03-27 10:04 UTC, SaimMomin12 commented on tools/pairtools/sort.xml
> +            <output name="output_sorted_pairs" ftype="pairsam" file="output_sorted_pairs.pairsam" lines_diff="10"/>
Maybe we can change this to tabular? 
```suggestion
            <output name="output_sorted_pairs" ftype="tabular" file="output_sorted_pairs.pairsam" lines_diff="10"/>
```

2024-03-27 10:05 UTC, SaimMomin12 commented on tools/pairtools/sort.xml
> +        <data name="output_sorted_pairs" format="pairs,pairsam" label="${tool.name} on ${on_string}: .pairsam"/>
tabular?

```suggestion
        <data name="output_sorted_pairs" format="tabular" label="${tool.name} on ${on_string}: .pairsam"/>
```

2024-03-27 10:05 UTC, diegomics commented on tools/pairtools/sort.xml
> +        <param name="pairs_path" type="data" format="pairs" label="Input pairs file" help="Input .pairs/.pairsam file"/>
Ok, I'll update all to tabular

2024-03-27 10:06 UTC, SaimMomin12 commented on tools/pairtools/sort.xml
> +        <param name="pairs_path" type="data" format="tabular" label="Input pairs file" help="Input .pairs/.pairsam file"/>
```suggestion
        <param name="pairs_path" type="data" format="text,tabular" label="Input pairs file" help="Input .pairs/.pairsam file"/>
```

2024-03-27 10:20 UTC, bgruening reviewed
We need to decide if we add the PAIR datatype to Galaxy or if we go for tabular for the time being.

2024-03-27 10:20 UTC, bgruening commented on tools/pairtools/sort.xml
> +        pairs_path : Input .pairs or .pairsam file.
```suggestion
```

2024-03-27 10:20 UTC, bgruening commented on tools/pairtools/sort.xml
> +        <data name="output_sorted_pairs" format="tabular" label="${tool.name} on ${on_string}: .pairsam"/>
```suggestion
        <data name="output_sorted_pairs" format="tabular" label="${tool.name} on ${on_string}"/>
```

I guess it makes no sense to specify the datatype again?

2024-03-27 16:55 UTC, SaimMomin12 commented
Resolved: https://github.com/galaxyproject/tools-iuc/pull/5917

2024-03-28 07:56 UTC, diegomics commented
Nice! Yes... both generating part of the files for the test dataset messed up the diff. I'm closing this PR now that #5917 is done

2024-03-28 07:56 UTC, closed without merging