Add Pairtools dedup
galaxyproject/tools-iuc pull request #5911
Opened 2024-03-26 14:15 UTC by diegomics

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [x] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

2024-03-27 12:00 UTC, SaimMomin12 requested changes
Hi @diegomics,

Some of the suggestions and corrections for the current PR inline.

2024-04-02 11:39 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +                'dedup_pairs_stats'
Hi @diegomics,

`dedup_pairs_stats` is redundant here. This is causing the last test no 3 to fail. 
```suggestion
```

2024-04-02 12:01 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +                  --output-stats '$dedup_pairs_stats'
Hi @diegomics,

I checked the PR in my system and the test error is due to the `$dedup_pairs_stats` as we haven't defined it in the output with this name but other name `parsed_pairs_stats`

So if you replace the `$dedup_pairs_stats`  with `$parsed_pairs_stats` this will work out.  
```suggestion
                  --output-stats '$parsed_pairs_stats'
```

2024-04-02 12:02 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +                  --output-stats '$dedup_pairs_stats'
Hi @diegomics,

I checked the PR in my system and the test error is due to the `$dedup_pairs_stats` as we haven't defined it in the output with this name but other name `parsed_pairs_stats`

So if you replace the `$dedup_pairs_stats`  with `$parsed_pairs_stats` this will work out.  
```suggestion
                  --output-stats '$parsed_pairs_stats'
```

2024-04-02 12:47 UTC, diegomics commented on tools/pairtools/dedup.xml
> +                  --output-stats '$dedup_pairs_stats'
I updated all to dedup

2024-04-02 12:51 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +                  --output-stats '$dedup_pairs_stats'
Thanks it worked well!

2024-04-03 13:06 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +<tool id="pairtools_dedup" name="Pairtools dedup" version="@TOOL_VERSION@+galaxy@SUFFIX_VERSION@" profile="22.05" license="MIT">
Updating the profile for accommodating new datatype.

```suggestion
<tool id="pairtools_dedup" name="Pairtools dedup" version="@TOOL_VERSION@+galaxy@SUFFIX_VERSION@" profile="23.2" license="MIT">
```

2024-04-03 13:07 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +        <data name="output_dedup_pairs" format="tabular" label="${tool.name} on ${on_string}: .pairsam"/>
```suggestion
        <data name="output_dedup_pairs" format="4dn_pairsam" label="${tool.name} on ${on_string}: .pairsam"/>
```

2024-04-03 13:08 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +        <data name="output_dups_pairs" format="tabular" label="${tool.name} on ${on_string}: Duplicate Pairs">
```suggestion
        <data name="output_dups_pairs" format="4dn_pairs" label="${tool.name} on ${on_string}: Duplicate Pairs">
```

2024-04-03 13:08 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +            <output name="output_dedup_pairs" ftype="tabular" file="output_dedup_pairs.pairsam" lines_diff="20"/>
```suggestion
            <output name="output_dedup_pairs" ftype="4dn_pairsam" file="output_dedup_pairs.pairsam" lines_diff="20"/>
```

2024-04-03 13:09 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +            <output name="output_dedup_pairs" ftype="tabular" file="output_dedup_pairs_markdups.pairsam" lines_diff="20"/>
```suggestion
            <output name="output_dedup_pairs" ftype="4dn_pairsam" file="output_dedup_pairs_markdups.pairsam" lines_diff="20"/>
```

2024-04-03 13:09 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +            <output name="output_dups_pairs"  ftype="tabular" file="output_dups_pairs_markdups.pairsam" lines_diff="20"/>
```suggestion
            <output name="output_dedup_pairs" ftype="4dn_pairsam" file="output_dedup_pairs_markdups.pairsam" lines_diff="20"/>
            <output name="output_dups_pairs"  ftype="4dn_pairsam" file="output_dups_pairs_markdups.pairsam" lines_diff="20"/>
```

2024-04-03 13:12 UTC, SaimMomin12 requested changes
Hi @diegomics,

We have recently added two new datatypes (4dn_pairs and 4dn_pairsam) to Galaxy to accomodate the Hi-C related data processing.

Could you please accept the changes for this just this tool? I have made changes to others. 

Thanks :)

2024-04-03 15:29 UTC, SaimMomin12 commented
Thanks @diegomics :smiley:

2024-04-03 16:14 UTC, bgruening commented on tools/pairtools/dedup.xml
> +        <param name="input_type" type="select" label="Select the Input file format">
Can we deduce this from the metadata now? Or should we keep this explicitly?

2024-04-03 16:15 UTC, bgruening commented on tools/pairtools/dedup.xml
> +        <data name="output_dedup_pairs" format="4dn_pairsam" label="${tool.name} on ${on_string}: Deduplicated Pairs">
use format_source?

2024-04-04 10:38 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +        <param name="input_type" type="select" label="Select the Input file format">
If the user specifies the format while uploading the data in Galaxy Upload, the need for `input_type` wipes out.

2024-04-04 10:38 UTC, SaimMomin12 commented on tools/pairtools/dedup.xml
> +        <data name="output_dedup_pairs" format="4dn_pairsam" label="${tool.name} on ${on_string}: Deduplicated Pairs">
Done!

2024-04-04 18:15 UTC, bgruening commented
Have you forgotten to commit?

2024-04-04 19:09 UTC, diegomics commented
> Have you forgotten to commit?

Yep :P

2024-04-04 19:30 UTC, bgruening approved these changes

2024-04-04 19:30 UTC, merged