Add JBrowse2
galaxyproject/tools-iuc pull request #6021
Opened 2024-05-21 15:49 UTC by bgruening

This PR is adding JBrowse2. It tries to merge https://github.com/galaxyproject/tools-iuc/pull/5695 with @abretaud work from https://github.com/galaxyproject/tools-iuc/pull/3997/.

I tried my best to keep all the features from both branches, but I'm aware its not perfect.
However, I think it's in a solid state and was tested by various people from the VGP and ERGA projects, so I think we should deploy it properly.

It's a super exciting but complicated tool, so I assume we will see many updates over time as we did with JBrowse1.

One major improvement over version 1 is that we have now proper, more complicated tests. We use the `location` attribute in Galaxy tests now and create complicated tracks. Test data is currently [here](https://usegalaxy.eu/static/share/ebp/jbrowse2/test-data/). The resulting zip file is then extensively "inspected". I think we can use this in the future to increase the test coverage.

A few other things in this PR:
  * HiC, Juicebox HiC, PAF, CRAM ... tracks added
  * The requested repeats from https://github.com/galaxyproject/tools-iuc/pull/5695 are included.
  * I added `<required_files>` so hopefully this helps with Pulsar
  * added `creators` with Ross, Helena and Anthony

Thanks to @abretaud, @erasche and @fubar2 for working on this.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2024-05-22 08:03 UTC, hexylena requested changes
We, appreciate, you trying to resolve this. However, we still feel uncomfortable with this PR, as we've had (internal) discussions around what needs to be part of a jbrowse2 PR.

What you've done here seems to be to incorporate Ross' changes *on top* of the work in https://github.com/galaxyproject/tools-iuc/pull/3997, replacing it in many places.

That code as it was, did not fit with what the genome annotation community feels is important moving forward. I refer you to my review comments in https://github.com/galaxyproject/tools-iuc/pull/5697#pullrequestreview-1836437432, this PR does not address any of those concerns. Namely: it still uses JSON to configure tracks which is fragile and undesirable, when there are solid CLI commands that we can be sure will continue working going forward if they make internal structure changes. Ross reports (unfiled) issues with the CLI tools, we should work to resolve those for the health of the community and use *limited* exceptions where we need things sooner.

by making a separate PR you've taken away from the diff that would be visible, had you made a PR to Anthony's branch in #3997. So it is harder to see what is being added to or changed from that.

If you *really* want the community to accept this, I would request that you:

- [ ] Close this PR and re-open it against [anthony's branch](https://github.com/abretaud/tools-iuc/tree/jbrowse2). This is needed so we can see what changes are being made to that existing extremely solid base of a PR and discuss those on a case by case basis.
- [ ] Revert to using the CLI, rather than JSON blobs that are not as future proof.

We need to review this in more detail,  and I think there are other bits of code smell like the SSL context that give me pause. I've made some small review comments but it is not a full review, I'll save that for when we can see a reduced diff of what has changed against the existing PR.

2024-05-22 08:25 UTC, bgruening commented on tools/jbrowse2/jbrowse2.xml
> +                        tabix bgzip with predictable index file URI</option>
Afaik, this was requested by users to create JBrowse2 (relocateable) archives that point to public data. In this case it was the GenomeArk, where all assembly data from VGP ends up. I think the argumentation was, the data should not be stored on Galaxy for every, so they need to move. But at the same point, there is a need to add a JBrowse2 instance to the GenomeArk that still works. I hope I recalled the feature correctly.

2024-05-22 08:25 UTC, bgruening commented on tools/jbrowse2/jbrowse2.py
> +        }
Maybe, it works so far for the tests that have been done by the VGP/ERGA community. I hope we can make this more stable as we go.

2024-05-22 08:42 UTC, bgruening commented on tools/jbrowse2/jb2_urlconf.py
> +urlbase = "https://galaxy.genomicsvl-students.cloud.edu.au/jbrowse/hum/"
That file was not necessary, I removed it. Thanks for the review.

2024-05-22 08:42 UTC, bgruening commented on tools/jbrowse2/jbrowse2.py
> +                scontext.verify_mode = ssl.VerifyMode.CERT_NONE
Its a fallback. We had some users putting in URLs with invalid certs. By default, the cert is checked. If you prefer I can remove the fallback.

2024-05-27 21:02 UTC, bgruening commented
I just updated to the latest version of JBrowse2, no issues so far, tests are passing :tada: 

@hexylena the repeat you requested in https://github.com/galaxyproject/tools-iuc/pull/5697#issuecomment-1911807744 is also integrated as far as I understood.

2024-06-04 15:53 UTC, closed without merging