Add Seurat v5 tools
galaxyproject/tools-iuc pull request #6022
Opened 2024-05-22 12:34 UTC by MarisaJL

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [x] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

2024-06-05 23:20 UTC, pavanvidem reviewed
Thanks @MarisaJL This looks great! Most of the tests are also green. Keep going!

2024-06-05 23:20 UTC, pavanvidem commented on tools/seurat_v5/reduce_dimensions.xml
> +                <param argument="assay" type="text" value="" optional="true" label="Name of Assay PCA is being run on"/>
please add it to macros. There are also few other params that are used several times

2024-06-05 23:20 UTC, pavanvidem commented on tools/seurat_v5/reduce_dimensions.xml
> +                <param name="return_model" type="boolean" truevalue="TRUE" falsevalue="FALSE" checked="false" label="Return the uwot model"/>
please check this option makes sense if `umap_methos` is not `uwot-learn`. Otherwise, add it under `uwot-learn` conditional case

2024-06-05 23:20 UTC, pavanvidem commented on tools/seurat_v5/reduce_dimensions.xml
> +                <param name="metric" type="text" value="cosine" label="Choose metric to use to measure distances in the input space"/>
please use a select type here

2024-06-05 23:20 UTC, pavanvidem commented on tools/seurat_v5/reduce_dimensions.xml
> +    #if $method.n_epochs != ''
```suggestion
    #if $method.n_epochs
```

2024-06-05 23:20 UTC, pavanvidem commented on tools/seurat_v5/reduce_dimensions.xml
> +                <param name="metric_kwds" type="text" optional="true" value="" label="Add dictionary of arguments to pass on the metric (e.g. for Minkowski distance)"/>
If it is not used often, please leave this out. This is a complex parameter. It takes a dictionary input. So needs repeat of two text params, one for key, second one for value. In the R code, all these params in the repeats should be bundled into a dictionary.

2024-07-17 13:44 UTC, pavanvidem commented
@MarisaJL  Sorry, forgot to push the test-data. They are bigger than 1MB. Please add them to the Zenodo record and remove from the repo.

2024-07-18 12:09 UTC, pavanvidem commented
please merge `searat_read10x` and ìnto `seurat_create` tool

2024-08-01 11:48 UTC, pavanvidem commented
@MarisaJL is there anything else to be added? or ready to review?

2024-08-01 12:32 UTC, MarisaJL commented
> @MarisaJL is there anything else to be added? or ready to review?

It should be ok now! Just needed to fix something small

2024-08-20 14:02 UTC, bgruening reviewed
Thanks @MarisaJL!

A few general comments, the rest inline:

* we need to be super careful to not reuse the tool IDs from: https://github.com/galaxyproject/tools-iuc/blob/main/tools/seurat/seurat.xml
* we probably want to remove the other seurat wrapper when this gets merged
* maybe, really not sure, we should change the ID to `seurat_tng_create` etc
   * I don't want to encore the version into the ID, but also indicate those are the newer wrappers for v5 and potentially v6 ....

2024-08-22 12:17 UTC, MarisaJL commented on tools/seurat_v5/create_seurat.xml
> +                        <param name="matrix" type="data" format="txt,mtx" label="Counts matrix with features as rows, cells as columns (.mtx)"/>
I included it because it was the only format allowed in the EBI version of the tool. I think it just works when an mtx file is misinterpreted as a txt file when you upload it, so it might be better to remove it to avoid confusing people!

2024-08-30 06:15 UTC, MarisaJL commented on tools/seurat_v5/create_seurat.xml
> +                <param argument="pattern" type="text" value="^MT-" label="Calculate percentage of genes matching this naming pattern" help="regex pattern to match"/>
I've added validators for the other text ones but I'm not sure what to put for this one!

2024-08-30 06:16 UTC, MarisaJL commented on tools/seurat_v5/create_seurat.xml
> +                        <param name="minimum" type="integer" optional="true" value="" label="Minimum"/>
I've put min/max in where I know what they are - I could add an impossibly large max here if it needs it?

2024-08-30 09:05 UTC, bgruening commented on tools/seurat_v5/create_seurat.xml
> +                        <param name="minimum" type="integer" optional="true" value="" label="Minimum"/>
No, its ok as it is :) Thanks a lot!

2024-08-30 09:08 UTC, bgruening commented on tools/seurat_v5/create_seurat.xml
> +                <param argument="pattern" type="text" value="^MT-" label="Calculate percentage of genes matching this naming pattern" help="regex pattern to match"/>
There is a validator type specifically for regular expressions: https://docs.galaxyproject.org/en/latest/dev/schema.html#validators-for-textual-inputs-text-select

2024-08-30 14:32 UTC, nilchia requested changes
Thanks @MarisaJL. I really liked this wrapping suite :+1:

2024-08-30 14:32 UTC, nilchia commented on tools/seurat_v5/plot.xml
> +                    <param name="add_noise" type="boolean" truevalue="TRUE" falsevalue="FALSE" checked="false" label="Add a small noise for plotting" help="(add.noise)"/>
```suggestion
                    <param name="add_noise" type="boolean" truevalue="TRUE" falsevalue="FALSE" checked="true" label="Add a small noise for plotting" help="(add.noise)"/>
```

2024-08-30 14:32 UTC, nilchia commented on tools/seurat_v5/plot.xml
> +                    <param name="add_noise" type="boolean" truevalue="TRUE" falsevalue="FALSE" checked="false" label="Add a small noise for plotting" help="(add.noise)"/>
https://satijalab.org/seurat/reference/vlnplot

2024-08-30 14:32 UTC, nilchia commented on tools/seurat_v5/plot.xml
> +            <output name="plot_out_png" location="https://zenodo.org/records/13348494/files/VlnPlot.png" ftype="png" compare="sim_size"/>
You can assert `image_diff`

2024-08-30 14:32 UTC, nilchia commented on tools/seurat_v5/reduce_dimensions.xml
> +            <output name="top_pcs" location="https://zenodo.org/records/13348494/files/top_pcs.txt" ftype="txt"/>
Can you do assert for this please?

2024-08-30 14:37 UTC, bgruening commented on tools/seurat_v5/create_seurat.xml
> +                    <param name="select_metric" type="select" label="Cell metric to filter">
conditionals can not have multiple=true ... but you can add a repeat and include the conditional inside the repeat... So a user can add as many metrics as needed via the repeat.

2024-09-03 08:22 UTC, MarisaJL commented on tools/seurat_v5/macros.xml
> +cp  '$seurat_rds' seurat.rds &&
@bgruening also suggested this, but it made all the tests that use this fail on here. The tests still passed on my laptop, but failed if I used biocontainers. I'm not sure why this happens or if there's a way around it!?

2024-09-03 08:51 UTC, bgruening commented on tools/seurat_v5/macros.xml
> +cp  '$seurat_rds' seurat.rds &&
Its strange, but no showstopper here. Leave it like it is for now. Thanks @MarisaJL

2024-09-05 17:21 UTC, pavanvidem commented on tools/seurat_v5/inspect_and_manipulate.xml
> +                        <param name="add_seurat" type="data" format="rds" label="Seurat object to merge"/>
```suggestion
                        <param name="add_seurat" type="data" format="rds"  multiple="true" label="Seurat object to merge"/>
```

2024-09-05 17:25 UTC, pavanvidem commented on tools/seurat_v5/inspect_and_manipulate.xml
> +        seurat_obj<-merge(x = seurat_obj, y = seurat_obj_2)
```suggestion
    #else if $method.manipulate.manipulate == 'Merge'
        #set files = ','.join([str($file) for $file in $method.manipulate.add_seurat])
        file_paths <- as.list(strsplit($files, ',')[[1]])
        seurat_objects_to_merge <- list()
        for (i in 1:length(file_paths)) {
            seurat_objects_to_merge[[i]]<-readRDS(file_paths[i])
        }
        seurat_obj<-merge(x = seurat_obj, y = seurat_objects_to_merge)
```
I haven't tested this. Something like this should work.

2024-09-05 19:25 UTC, bgruening commented on tools/seurat_v5/plot.xml
> +            <output name="plot_out_tex" location="https://zenodo.org/records/13348494/files/DimPlot.tex" ftype="tex" compare="sim_size"/>
Symsize is bad, please use asserts.

2024-09-09 13:48 UTC, pavanvidem commented on tools/seurat_v5/inspect_and_manipulate.xml
> +        #end for
```suggestion
        seurat_objects_to_merge <- list()
        #for $file in $method.manipulate.add_seurat
            object_to_add<-readRDS('$file')
            seurat_objects_to_merge <- c(seurat_objects_to_merge, object_to_add)
        #end for
        seurat_obj<-merge(x = seurat_obj, y = seurat_objects_to_merge)
```

2024-09-09 15:31 UTC, pavanvidem commented on tools/seurat_v5/inspect_and_manipulate.xml
> +                        <param argument="features" type="text" optional="true" value="" label="Features to keep" help="comma-separated list, leave blank to keep all">
is this used for subsetting a large set of genes? in that case, a file input is better than a list. I'm not sure how useful this function is. Let's keep it as it is for now. If comma separated list is hard to handle, then we will switch to a text file in the next update.

2024-09-09 15:31 UTC, pavanvidem commented on tools/seurat_v5/inspect_and_manipulate.xml
> +            <output name="rds_out" location="https://zenodo.org/records/13732784/files/default.rds" ftype="rds"/>
If you print the `seurat_obj` at the end of the R script, then you can use `<assert_stdout>` to match the text like default assy.

2024-09-09 15:31 UTC, pavanvidem commented on tools/seurat_v5/integrate.xml
> +                <conditional name="integration_method">
```suggestion
                <conditional name="integration">
```
instead of having `integration_method` twice, this sounds easier IMO. If you accept this suggestion, pelase do not forget to chang this thoughout the file.

2024-09-09 17:48 UTC, bgruening commented on tools/seurat_v5/.shed.yml
> +name: seurat_v5
You could remove the old tool. The tool ID is what counts and will make the tool ID. And the old tool is counted 'seurat' and the new one 'seurat_seurat'. I hope.

2024-09-11 09:08 UTC, pavanvidem approved these changes
LGTM. Thanks a lot for this most awaited tool suite in the Galaxy single-cell community! I believe there will be a lot of testers :) 

This suite already supports a lot of advanced single-cell analysis. Great work @MarisaJL!!

@bgruening please merge if it is fine with you.

2024-09-11 09:13 UTC, bgruening commented on tools/seurat_v5/.shed.yml
> +name: seurat_v5
```suggestion
name: seurat
```

Lets change it. But I think this will have no effect as it is a tool suite.

2024-09-11 09:51 UTC, bgruening commented
That is a big and beautiful project! Thanks a lot, @MarisaJL for all your work and for staying with us. We hope you enjoy Freiburg! 

Thanks also to ELIXIR for sponsoring this work with the exchange program.

2024-09-11 09:51 UTC, merged