add chainprenet tool from ucsc/kent
galaxyproject/tools-iuc pull request #6251
Opened 2024-08-18 11:10 UTC by martenson

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [x] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

2024-08-21 07:34 UTC, bgruening reviewed
A test using the datatables would be ace.

2024-08-21 07:34 UTC, bgruening commented on tools/ucsc_tools/chainprenet/chainprenet.xml
> +        <param argument="-dots" type="integer" optional="true" label="Output a dot every so often" />
min=0?

2024-08-21 07:34 UTC, bgruening commented on tools/ucsc_tools/chainprenet/chainprenet.xml
> +        <param argument="-pad" type="integer" optional="true" label="Extra to pad around blocks to decrease trash" help="Default 1" />
min=0

2024-08-25 09:12 UTC, martenson commented on tools/ucsc_tools/chainprenet/chainprenet.xml
> +<tool id="chainprenet" name="chainPreNet" version="@TOOL_VERSION@+galaxy0" profile="21.05" license="MIT">
sure thing!

2024-08-26 20:43 UTC, martenson commented on tools/ucsc_tools/chainprenet/chainprenet.xml
> +        <param argument="-dots" type="integer" optional="true" label="Output a dot every so often" />
I dropped this, it only writes "progress" dots to stderr

2024-08-27 07:14 UTC, bgruening commented on tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
> +            <param name="in_tar_ref_index" value="hg38.chr20.chunk.fasta.fai"/>
```suggestion
            <conditional name="target_reference_index_source"/>
                <param name="target_reference_index_source_selector" value="history" />
                <param name="in_tar_ref_index" value="hg38.chr20.chunk.fasta.fai"/>
            </conditional>
```

2024-08-27 07:14 UTC, bgruening commented on tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
> +            <param name="in_que_ref_index" value="mm39.chr2.chunk.fasta.fai"/>
```suggestion
            <conditional name="query_reference_index_source">
                <param name="query_reference_index_source_selector" value="history" />
                <param name="in_que_ref_index" value="mm39.chr2.chunk.fasta.fai"/>
            </conditional>
```

2024-08-27 07:14 UTC, bgruening commented on tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
> +            <param name="que_ref_index_file" value="mm39.chr2.chunk"/>
```suggestion
            <conditional name="target_reference_index_source"/>
                <param name="target_reference_index_source_selector" value="cached" />
                <param name="tar_ref_index_file" value="hg38.chr20.chunk"/>
            </conditional>
            <conditional name="query_reference_index_source">
                <param name="query_reference_index_source_selector" value="cached" />
                <param name="que_ref_index_file" value="mm39.chr2.chunk"/>
            </conditional>
```

2024-08-27 07:14 UTC, bgruening approved these changes

2024-08-27 09:54 UTC, SaimMomin12 requested changes
@martenson There are two minor linting errors in the `chainprenet.xml` file. The changes can be accepted to pass the CI tests.

2024-08-27 09:54 UTC, SaimMomin12 commented on tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
> +            <conditional name="target_reference_index_source"/>
```suggestion
            <conditional name="target_reference_index_source">
```

2024-08-27 09:54 UTC, SaimMomin12 commented on tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
> +            <conditional name="target_reference_index_source"/>
```suggestion
            <conditional name="target_reference_index_source">
```

2024-08-27 10:14 UTC, bgruening approved these changes

2024-08-27 10:14 UTC, bgruening commented
That was my fault.

2024-08-27 10:17 UTC, merged