Update InferCNV: control number of threads and downgrade profile
galaxyproject/tools-iuc pull request #6263
Opened 2024-08-22 09:23 UTC by pcm32

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [x] This PR does something else (explain below)

Minor change in the wrapper to control number of threads. It also downgrades the profile for wider compatibility.

2024-08-22 09:24 UTC, pcm32 commented
I will test installation as is first to see if the API based installation with higher profile than the instance works.

2024-08-22 18:36 UTC, bgruening commented on tools/infercnv/infercnv.xml
> +                                #num_threads = num_threads_galaxy_slots,
```suggestion
                                #num_threads = num_threads_galaxy_slots,
```

You need to put the `os.environ.get('GALAXY_SLOTS', 1)` into this script.

2024-08-22 20:16 UTC, pcm32 commented on tools/infercnv/infercnv.xml
> +                                #num_threads = num_threads_galaxy_slots,
You mean I should grab the GALAXY_SLOT from R at level with `Sys.getenv('GALAXY_SLOT')` or use the cheetah construct `$os.environ.get('GALAXY_SLOTS', 1)` directly here? Won't I still need the cheetah `import os` which might be breaking things? Thanks.

2024-08-22 20:23 UTC, bgruening commented on tools/infercnv/infercnv.xml
> +                                #num_threads = num_threads_galaxy_slots,
You can not use cheetah, you need to get the envs from within the script. In that case your R script.

2024-08-22 20:27 UTC, pcm32 commented on tools/infercnv/infercnv.xml
> +                                #num_threads = num_threads_galaxy_slots,
I see... I found a potential way in another tool, tried before I saw your response, if it doesn't work will switch to the R way.

2024-08-22 21:33 UTC, pcm32 commented
...finally....

2024-08-22 21:34 UTC, pcm32 commented on tools/infercnv/infercnv.xml
> +                                #num_threads = num_threads_galaxy_slots,
Moved now to full R logic for grabbing GALAXY_SLOTS. Thanks!

2024-08-23 07:57 UTC, pcm32 commented
Looking in more detail, this tool is receiving a non-sparse matrix in tsv format, that is prohibitive for large datasets. The tool should instead receive a sparse matrix format, ideally matrix market or a seurat object. Otherwise this means exploding very large matrices.

2024-08-23 08:07 UTC, bgruening commented
LGTM. Do you want to add the matrix-market ...?

2024-08-23 14:51 UTC, pcm32 commented
Yes, almost there with the sparse matrix support.

2024-08-23 15:05 UTC, pcm32 commented
I'm once again somehow offending the Cheetah gods... 

```
Job in error state.. tool_id: infercnv, exit_code: None, stderr: .
Job in error state.. tool_id: infercnv, exit_code: None, stderr: .
Output collection 'infercnv_results': failed to find identifier 'infercnv.heatmap_thresholds' in the tool generated elements []
```

new test passes, but previous ones don't - could you please advice @bgruening ? Thanks.

2024-08-23 19:59 UTC, nilchia requested changes

2024-08-23 19:59 UTC, nilchia commented on tools/infercnv/infercnv.xml
> +        #if $input_mat.mtx and $input_mat.mtx_genes and $input_mat.mtx_barcodes:
```suggestion
        #if str($input_mat.format) == "mtx":
```

2024-08-23 19:59 UTC, nilchia commented on tools/infercnv/infercnv.xml
> +            #if $input_mat.mtx and $input_mat.mtx_genes and $input_mat.mtx_barcodes:
```suggestion
            #if str($input_mat.format) == "mtx":
```

2024-08-23 20:15 UTC, pcm32 commented
Thanks @nilchia for the suggestions!

2024-08-23 20:32 UTC, nilchia commented
You're welcome @pcm32 !
Thanks for the update.

2024-08-23 20:35 UTC, nilchia approved these changes

2024-08-24 11:34 UTC, bgruening commented on tools/infercnv/infercnv.xml
> +                <param name="mtx_genes" type="data" format="tsv,tabular" label="Genes file" help="The genes file for matrix market matrix, a two column symbol - symbol or gene_id - symbol tab separat
tabular and tsv? I guess tabular is enough: https://github.com/galaxyproject/galaxy/blob/e9c6a071c73ec764ddb0963c87b0e4e829138872/lib/galaxy/datatypes/tabular.py#L1512

2024-08-27 12:41 UTC, pcm32 commented on tools/infercnv/infercnv.xml
> +                <param name="mtx_genes" type="data" format="tsv,tabular" label="Genes file" help="The genes file for matrix market matrix, a two column symbol - symbol or gene_id - symbol tab separat
Agreed. Added txt in exchange, sometimes on upload some of those files end up as text and then is less hassle to use the tool/pipeline.

2024-08-27 12:48 UTC, bgruening approved these changes

2024-08-27 12:59 UTC, merged